// 情境資料產生器。
//
// **一個真名都不會出現**（CLAUDE.md 的鐵則，tests/no-secrets.test.js 盯著）。
// 客戶一律叫「客戶A」「客戶B」…，需要跟字數有關的規則時用「王小明」。
//
// 主檔直接借 domain/seed.js 那一份 —— 自己另外編一套的話，
// 測試會在一組「她的資料庫裡永遠不會出現」的課程上跑。

import { SEED, DEFAULT_SETTINGS } from '../../public/js/domain/seed.js';

export const TODAY = '2026-08-29';

export const addDays = (iso, n) => {
  const [y, m, d] = iso.split('-').map(Number);
  const dt = new Date(Date.UTC(y, m - 1, d + n));
  return dt.toISOString().slice(0, 10);
};

/** 主檔：課程、診間、治療師與醫師、器材、點滴品項、營養品、方案，加上設定值。 */
export function masterDocs(settings = {}) {
  const docs = [{ path: 'config', id: 'app', data: { ...DEFAULT_SETTINGS, ...settings } }];
  for (const [type, rows] of Object.entries(SEED)) {
    for (const row of rows) {
      const { id, ...data } = row;
      docs.push({ path: `config/app/${type}`, id, data: { ...data, active: true } });
    }
  }
  return docs;
}

export function customer({ id, name, marks = [], flags = [], priority = 3, ...rest }) {
  return {
    path: 'customers',
    id,
    data: {
      name, marks, flags, priority,
      phone: null, chartNo: null, note: null, ...rest,
    },
  };
}

export function entitlement(customerId, {
  id, label, type = 'single', courseId = null, totalQty = 10,
  doneCount = 0, bookedCount = 0, optionEquipmentIds = null, ...rest
}) {
  return {
    path: `customers/${customerId}/entitlements`,
    id,
    data: {
      label, type, courseId, totalQty, doneCount, bookedCount,
      optionEquipmentIds, durationMin: null, frequencyRule: null,
      sourcePlanName: null, purchasedAt: null, expiresAt: null,
      lastReconciledAt: null, ...rest,
    },
  };
}

export function visit({
  id, customerId, customerName, date, status = 'pending_confirm', slots = [], ...rest
}) {
  return {
    path: 'visits',
    id,
    data: { customerId, customerName, date, status, slots, note: null, ...rest },
  };
}

/** 課程 id → 名字。時段上的 `courseName` 是**跟著存**的（主檔改名不影響歷史）。 */
const COURSE_NAME = Object.fromEntries(SEED.courses.map((c) => [c.id, c.name]));

export const slot = ({
  courseId, entitlementId, startsAt, endsAt, equipmentId = null,
  therapistId = null, doctorId = null, roomId = null, bed = null,
  ivProductId = null, followupForVisitId = null, followupNth = null,
  attended = undefined,
}) => {
  const s = {
    courseId,
    // 少了它畫面上會印「（沒有課程）」—— `visitCourseLabel()` 讀的是這個快照，
    // 不是回頭去查主檔。種子少寫這一欄會讓每一支測試都在看一個不寫實的畫面。
    //
    // **n返 的名字不是主檔上那一個**（它借二返那個課程，但畫面上要印「三返」），
    // 所以有返數時照返數組（同 `domain/nthFollowup.js` 的 `nthSlotFields()`）。
    courseName: followupNth ? `${NTH_NAMES[followupNth] ?? ''}返` : (COURSE_NAME[courseId] ?? ''),
    entitlementId, startsAt, endsAt,
    equipmentId, therapistId, doctorId, roomId, bed, ivProductId, followupForVisitId,
  };
  // 二返身上沒有這個欄位，所以只有 n返 才寫進去 —— 一律寫 null 的話，
  // 「有沒有填過」這個判斷（`isNthSlot()`）在種子與真的資料上會不一樣。
  if (followupNth != null) s.followupNth = followupNth;
  if (attended !== undefined) s.attended = attended;
  return s;
};

/** 3 → 三。`domain/nthFollowup.js` 有同一份，這裡是種子用的最小複本。 */
const NTH_NAMES = { 2: '二', 3: '三', 4: '四', 5: '五', 6: '六', 7: '七', 8: '八', 9: '九', 10: '十' };

export function task({
  id, customerId, customerName, kind, dueDate, visitId = null,
  done = false, doneAt = null, autoGenerated = true, note = null,
}) {
  return {
    path: 'tasks',
    id,
    data: { customerId, customerName, kind, dueDate, visitId, done, doneAt, autoGenerated, note },
  };
}

export function note({
  id, text, done = false, date = null, customerId = null, customerName = null,
  entitlementId = null, doneAt = null,
}) {
  return {
    path: 'notes',
    id,
    data: { text, done, date, customerId, customerName, entitlementId, doneAt },
  };
}

export function event({
  id, title, category = 'personal', startDate, endDate = null, allDay = true, color = null,
}) {
  return {
    path: 'events',
    id,
    data: { title, category, startDate, endDate: endDate ?? startDate, allDay, color },
  };
}

/**
 * 一份備忘錄（ADR-0067）。`sections` 收簡寫：`['事前|前情提醒|飯後打針']`
 * 這種形狀在測試裡讀起來比一疊物件清楚。
 */
export function playbook({
  id, title, tag = null, courseIds = [], pinned = false, sections = [],
}) {
  return {
    path: 'playbooks',
    id,
    data: {
      title,
      tag,
      courseIds,
      pinned,
      sections: sections.map((raw) => {
        if (typeof raw !== 'string') return raw;
        const [when, heading, body] = raw.split('|');
        return { when: when || null, heading: heading ?? '', body: body ?? '' };
      }),
    },
  };
}

export function availability(customerId, {
  id, rawText, validFrom, validTo, rules = [], source = null, collectedAt = null,
}) {
  return {
    path: `customers/${customerId}/availability`,
    id,
    data: { rawText, validFrom, validTo, rules, source, collectedAt: collectedAt ?? validFrom },
  };
}

// ---------- 現成的情境 ----------

/**
 * 基本盤：一位買了「筋骨強身」的客戶A，身上有復能（擇一池）與靜脈。
 * 沒有任何來訪、沒有任何任務 —— 從這裡開始走一條龍。
 */
export function scenarioFresh() {
  return [
    ...masterDocs(),
    customer({ id: 'cust-a', name: '客戶A', priority: 4 }),
    entitlement('cust-a', {
      id: 'ent-a-recovery', label: '復能', type: 'pool', totalQty: 12,
      optionEquipmentIds: ['eq-laser', 'eq-sis', 'eq-indiba'], durationMin: 60,
    }),
    entitlement('cust-a', {
      id: 'ent-a-vein', label: '靜脈', type: 'single', courseId: 'course-iv-laser',
      totalQty: 20, durationMin: 60,
    }),
  ];
}

/**
 * examine 鏈的起點：客戶B 買了 2 次 examine，已經配好二返額度，
 * 而且**第一次 examine 已經做完了**（所以「追蹤健檢報告」該長出來）。
 */
export function scenarioExamineChain({ examDate = addDays(TODAY, -5) } = {}) {
  return [
    ...masterDocs(),
    customer({ id: 'cust-b', name: '客戶B', priority: 3 }),
    entitlement('cust-b', {
      id: 'ent-b-exam', label: '8萬健檢', type: 'single', courseId: 'course-checkup',
      totalQty: 2, doneCount: 1, bookedCount: 0, tier: '8萬', durationMin: 120,
    }),
    entitlement('cust-b', {
      id: 'ent-b-followup', label: '二返（8萬健檢）', type: 'single',
      courseId: 'course-followup', totalQty: 2, doneCount: 0, bookedCount: 0,
      followupForEntitlementId: 'ent-b-exam', durationMin: 30,
    }),
    visit({
      id: 'visit-b-exam1', customerId: 'cust-b', customerName: '客戶B',
      date: examDate, status: 'done',
      slots: [slot({
        courseId: 'course-checkup', entitlementId: 'ent-b-exam',
        startsAt: '09:00', endsAt: '11:00', roomId: 'room-t3', attended: true,
      })],
    }),
  ];
}

/**
 * 營養品：客戶C 買了一包 5000 元、四款、兩個月的營養品，
 * 提醒掛在下一次來訪那天。
 */
export function scenarioProducts({ giveDate = addDays(TODAY, 2) } = {}) {
  const items = [
    { productId: 'prod-yetaimei', name: '夜態美' },
    { productId: 'prod-sushanjing', name: '速膳淨' },
    { productId: 'prod-linengkang', name: '粒能康' },
    { productId: 'prod-gaba', name: 'GABA' },
  ];
  return [
    ...masterDocs(),
    customer({ id: 'cust-c', name: '客戶C' }),
    entitlement('cust-c', {
      id: 'ent-c-recovery', label: '復能', type: 'pool', totalQty: 10,
      // 底下那一筆來訪是「已確認」，所以已排未上是 1。計數欄位要跟它對得起來，
      // 不然每一支測試的畫面上都會掛著一句「計數欄位與來訪對不起來」。
      bookedCount: 1, optionEquipmentIds: ['eq-laser', 'eq-sis', 'eq-indiba'], durationMin: 60,
    }),
    entitlement('cust-c', {
      // 經過「加購」存下來的 label 長這樣（`components/buy.js` 的 `autoLabel()`
      // → `domain/products.js` 的 `productLabel()`）。金額進名字裡是刻意的。
      id: 'ent-c-prod', label: '營養品 5,000（夜態美＋速膳淨＋粒能康＋GABA）',
      type: 'product', totalQty: 2, amountTwd: 5000, items, deliveries: [],
    }),
    note({
      id: 'note-c-give', text: '給客戶C營養品：夜態美＋速膳淨＋粒能康＋GABA',
      date: giveDate, customerId: 'cust-c', customerName: '客戶C',
      entitlementId: 'ent-c-prod',
    }),
    visit({
      id: 'visit-c-next', customerId: 'cust-c', customerName: '客戶C',
      date: giveDate, status: 'confirmed',
      slots: [slot({
        courseId: 'course-recovery', entitlementId: 'ent-c-recovery',
        startsAt: '10:00', endsAt: '11:00', equipmentId: 'eq-indiba', therapistId: 'staff-tw',
      })],
    }),
  ];
}

/**
 * 醫療禁忌：客戶D 體內有金屬，所以超磁場與高能量雷射要被硬性鎖死，
 * 三選一的擇一池只剩 INDIBA。
 */
export function scenarioContraindication() {
  return [
    ...masterDocs(),
    customer({ id: 'cust-d', name: '客戶D', flags: ['體內金屬'] }),
    entitlement('cust-d', {
      id: 'ent-d-recovery', label: '復能', type: 'pool', totalQty: 12,
      optionEquipmentIds: ['eq-laser', 'eq-sis', 'eq-indiba'], durationMin: 60,
    }),
  ];
}

/**
 * 資料對不起來：計數欄位被寫歪了（doneCount 說 5，來訪只算得出 1）。
 * 資料健檢的「次數對帳」與客戶詳情的差異提示都該抓到。
 */
export function scenarioBrokenCounts() {
  return [
    ...masterDocs(),
    customer({ id: 'cust-e', name: '客戶E' }),
    entitlement('cust-e', {
      id: 'ent-e-vein', label: '靜脈', type: 'single', courseId: 'course-iv-laser',
      totalQty: 20, doneCount: 5, bookedCount: 3,
    }),
    visit({
      id: 'visit-e-1', customerId: 'cust-e', customerName: '客戶E',
      date: addDays(TODAY, -10), status: 'done',
      slots: [slot({
        courseId: 'course-iv-laser', entitlementId: 'ent-e-vein',
        startsAt: '14:00', endsAt: '15:00', roomId: 'room-ilib4',
      })],
    }),
  ];
}
