// §2.2 已完成的待辦被「清掉」（軟刪除）之後，同一筆來訪再存一次，那幾張會重新長出來。
//
// `data/tasks.js` 的 `listByVisit()` 走 `repo.list()`，一律濾掉 `deletedAt` ——
// 所以 `syncTasksForVisit()` 看到的「這筆來訪現有的任務」裡沒有它們。
// 這一支不碰 IO：直接把「軟刪除過的那幾張」餵給 domain，問它會不會再長一次。
//
// 畫面上「清掉」那一道寫著「做過的事本身沒有被改掉 —— 清掉的只是這一列」。

import { test, describe } from 'node:test';
import assert from 'node:assert/strict';

import { syncTasksForVisit, cancelTasksFor } from '../../public/js/domain/taskRules.js';
import { SEED } from '../../public/js/domain/seed.js';

const TODAY = '2026-09-16';
const coursesById = Object.fromEntries(SEED.courses.map((c) => [c.id, c]));

const REHAB = 'course-rehab';   // A 類 → Examine、耀聖
const ILIB = 'course-iv-laser'; // C 類 → 只有 Abovee

const slot = (courseId, status, startsAt) => ({
  courseId, entitlementId: 'ent-1', startsAt, endsAt: startsAt, status,
  courseName: coursesById[courseId].name,
});

const visitOf = (slots, status = 'confirmed') => ({
  id: 'v-1', customerId: 'c-1', customerName: '客戶A', date: '2026-09-20', status, slots,
});

/** 已經做完、然後被「清掉」的那一張（軟刪除）。 */
const cleared = (t) => ({ ...t, id: `${t.kind}-1`, done: true, doneAt: TODAY, deletedAt: TODAY });

describe('§2.2 清掉已完成的待辦之後再存一次', () => {
  describe('取消一段之後，那一張「取消 Abovee」被清掉了', () => {
    const visit = visitOf([
      slot(ILIB, 'cancelled', '09:00'),
      slot(ILIB, 'confirmed', '10:00'),
    ]);
    const existing = [cleared({
      kind: '取消 Abovee', visitId: 'v-1', customerId: 'c-1', slotIndexes: [0], autoGenerated: true,
    })];

    test('沒清掉之前再存一次：不會多長', () => {
      const alive = [{ ...existing[0], deletedAt: null }];
      assert.deepEqual(cancelTasksFor(visit, alive, coursesById, TODAY), []);
    });

    // ↓ 紅。清掉之後同一段又長一張，而且死線已經過了。
    test('清掉之後再存一次：那一段已經有人收過了，不可以再長', () => {
      assert.deepEqual(
        cancelTasksFor(visit, existing, coursesById, TODAY).map((t) => t.kind),
        [],
      );
    });
  });

  describe('A 類已確認，Examine／耀聖勾掉之後被清掉了', () => {
    const visit = visitOf([slot(REHAB, 'confirmed', '09:00')]);
    const existing = [
      cleared({ kind: 'Examine', visitId: 'v-1', customerId: 'c-1', autoGenerated: true }),
      cleared({ kind: '耀聖', visitId: 'v-1', customerId: 'c-1', autoGenerated: true }),
    ];

    test('沒清掉之前改個時間再存：不會多長', () => {
      const alive = existing.map((t) => ({ ...t, deletedAt: null }));
      const { create } = syncTasksForVisit(visit, alive, { coursesById, today: TODAY });
      assert.deepEqual(create.map((t) => t.kind), []);
    });

    // ↓ 紅。清掉之後改個時間再存，Examine 與耀聖又各長一張 ——
    //    那兩件她在外面的系統上早就做完了。
    test('清掉之後改個時間再存：登記過的不可以再長一次', () => {
      const { create } = syncTasksForVisit(visit, existing, { coursesById, today: TODAY });
      assert.deepEqual(create.map((t) => t.kind), []);
    });
  });
});
