// 稽核紀錄、今天做了什麼、變更紀錄：一個英文欄位名都不印（issue 14，2026-10-07）。
//
// 名單是 10/7 在模擬器上跑 9 支 spec 量出來的（每一則稽核過 `changedFields()`，
// `label === key` 的就是會原樣印英文的），加上種子主檔上改得到、量的時候沒被改到的那幾格。
// **新增一個欄位**：補進 `FIELD_LABELS`（她改得到的，用設定頁那一格的字）；
// 系統自己記的另外進 `QUIET_IN_SENTENCE`（句子不講、稽核頁的表照列 —— ADR-0071，不可以進 `NOISE_FIELDS`）。

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

import { fieldLabel, changedFields, describeEvent, describeAction } from '../public/js/domain/audit.js';

/** 她在畫面上改得到的。 */
const HERS = [
  'partners', 'tier', 'membershipMonths',
  'preferredRoomIds', 'durationChoices', 'needsRecord', 'needsTreatmentForm', 'assigns',
  'allowedRoomTypes', 'lineName', 'followupCourseId',
  'capacity', 'contraindications', 'color', 'fill', 'hint',
  'messageTemplates', 'sortWeights', 'slotGapMin', 'sheetSync',
  // 審查補的：已完成那一天的更正、額度上買的那一款點滴、AI 用量的設定
  'lastCorrection', 'ivProductId', 'monthlyCapUsd', 'paused',
];

/** 系統自己記的：她沒有改它，那一則紀錄講的也不是它。 */
const SYSTEMS = [
  'customerId', 'visitId', 'statusAt', 'confirmedAt', 'cancelledAt', 'importedFrom',
  'autoGenerated', 'slotIndexes', 'reason',
  'sourcePlanName', 'sourcePlanQty', 'sourcePlanSets', 'purchaseId', 'followupForEntitlementId',
  'targetMonth', 'lastDeviceHint',
];

test('每一個量到的欄位都有中文名字', () => {
  const english = [...HERS, ...SYSTEMS].filter((k) => fieldLabel(k) === k);
  assert.deepEqual(english, []);
});

test('系統自己記的：稽核頁的表照列（ADR-0071），只是不再是英文', () => {
  for (const key of SYSTEMS) {
    const rows = changedFields({ action: 'visits.update', before: {}, after: { [key]: 'x' } });
    assert.equal(rows.length, 1, key);
    assert.notEqual(rows[0].label, key);
  }
});

test('系統自己記的不擠進那一句話', () => {
  const line = describeEvent({
    action: 'visits.update',
    targetPath: 'visits/v1',
    before: { date: '2026-10-07', status: 'pending', customerName: '客戶A' },
    after: { status: 'confirmed', statusAt: 'x', confirmedAt: 'y' },
  });
  assert.ok(line && !/時間/.test(line), line);
});

test('只動到購買來源的那一則額度，不講成「對帳過了」', () => {
  const line = describeEvent({
    action: 'customers/c1/entitlements.update',
    targetPath: 'customers/c1/entitlements/e1',
    before: { label: '復能-SIS(60)' },
    after: { sourcePlanName: '某方案', purchaseId: 'p1' },
  });
  assert.ok(!/對帳/.test(line ?? ''), line);
});

test('只動到對帳時間的那一則照舊是「對帳過了」', () => {
  const line = describeEvent({
    action: 'customers/c1/entitlements.update',
    targetPath: 'customers/c1/entitlements/e1',
    before: { label: '復能-SIS(60)', lastReconciledAt: 1 },
    after: { lastReconciledAt: 2 },
  });
  assert.match(line, /對帳過了/);
});

// `data/backup.js` 匯出完那一句（`describeCounts()`）也印它；那一支 import firebase，所以掃原始碼。
test('畫面上找不到「壓表批次」四個字', () => {
  assert.doesNotMatch(describeAction('batches.create'), /批次/);
  for (const path of ['public/js/domain/audit.js', 'public/js/data/backup.js']) {
    const quoted = readFileSync(path, 'utf8').match(/'[^'\n]*壓表批次[^'\n]*'/g) ?? [];
    assert.deepEqual(quoted, [], path);
  }
});

// 兩份名單綁在一起（審查 2026-10-07）：系統自己記的有中文名之外，**也要真的不進句子** ——
// 只補了 `FIELD_LABELS` 的話，那一句會變成「改了 哪幾段」。
test('系統自己記的每一個都不出現在那一句話裡', () => {
  for (const key of SYSTEMS) {
    const line = describeEvent({
      action: 'visits.update', targetPath: 'visits/v1',
      before: { date: '2026-10-07', customerName: '客戶A' }, after: { [key]: 'x' },
    }) ?? '';
    assert.ok(!line.includes(fieldLabel(key)), `${key}：${line}`);
  }
});
