// 改了 設定 → 課程 的「壓哪幾個系統」或「寫紀錄」，已經談定的來訪要跟著補長或收掉（ADR-0140，
// `.scratch/prelaunch-fixes-2026-10-08/issues/16`）。
//
// 以前存課程只寫課程本身。待辦是存**來訪**時才算的，已經談定的那幾筆要等下次被存 —— 通常就是簽療程單，
// 而那時那一段已經不是「已確認」，掛號那一族就不長了。反過來取消勾選，已經長出來的會一直留著。
//
// 這一支釘的是純函式那一半：哪幾種算「變了」、一筆來訪要跟著怎麼動。
// 「只寫任務、不存來訪」「長的從還開著的來訪出發、收的從還沒勾的任務出發」在 `data/visits.js`，由 E2E `63` 盯著。

import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

import { SEED, seedData } from '../public/js/domain/seed.js';
import {
  changedTaskKinds, tasksAfterCourseChange, syncTasksForVisit, RECORD_TASK_KIND, isCancelKind,
} from '../public/js/domain/taskRules.js';
import { withSlotStatuses, closeVisit } from '../public/js/domain/visits.js';
import { courseChangeConsequences } from '../public/js/domain/consequences.js';
import { fromRoot } from './helpers/paths.js';

const TODAY = '2026-10-08';
const courses = SEED.courses.map((r) => ({ id: r.id, ...seedData(r) }));
const BEFORE = Object.fromEntries(courses.map((c) => [c.id, c]));

/** 把一門課換成改過的樣子。 */
const withCourse = (id, changes) => {
  const after = { ...BEFORE[id], ...changes };
  return { before: BEFORE[id], after, coursesById: { ...BEFORE, [id]: after } };
};

const slot = (courseId, status, over = {}) => ({
  courseId, entitlementId: 'e1', startsAt: '10:00', endsAt: '10:30', status, ...over,
});
const visit = (id, date, slots, over = {}) => withSlotStatuses({
  id, customerId: 'c1', customerName: '王小明', date,
  status: slots.every((s) => s.status === 'cancelled') ? 'cancelled'
    : slots.some((s) => s.status === 'pending_confirm') ? 'pending_confirm'
      : slots.some((s) => s.status === 'confirmed') ? 'confirmed' : slots[0].status,
  slots,
  ...over,
});
const task = (id, visitId, kind, over = {}) => ({
  id, visitId, customerId: 'c1', customerName: '王小明', kind, dueDate: '2026-10-19',
  done: false, doneAt: null, autoGenerated: true, ...over,
});

/** 這一筆來訪照改過的設定要跟著怎麼動。 */
const follow = (v, tasks, change, today = TODAY) =>
  tasksAfterCourseChange(v, tasks, { before: change.before, after: change.after, coursesById: change.coursesById, today });

const AMNION_PLUS = withCourse('course-amnion', { systems: ['Abovee', '耀聖'] });

describe('哪幾種待辦算「變了」', () => {
  test('多勾耀聖 → 耀聖是新長的', () => {
    assert.deepEqual(changedTaskKinds(AMNION_PLUS.before, AMNION_PLUS.after), { grown: ['耀聖'], dropped: [] });
  });

  test('回測報告三個都勾 → 只留 Abovee：Examine、耀聖是不要了的', () => {
    const c = withCourse('course-retest', { systems: ['Abovee'] });
    assert.deepEqual(changedTaskKinds(c.before, c.after), { grown: [], dropped: ['Examine', '耀聖'] });
  });

  test('三個都不勾（不用壓，ADR-0126）→ 確認後那幾種全部不要了', () => {
    const c = withCourse('course-retest', { systems: [] });
    assert.deepEqual(changedTaskKinds(c.before, c.after), { grown: [], dropped: ['Examine', '耀聖'] });
  });

  test('寫紀錄打開／關掉', () => {
    const on = withCourse('course-amnion', { needsRecord: true });
    assert.deepEqual(changedTaskKinds(on.before, on.after), { grown: [RECORD_TASK_KIND], dropped: [] });
    const off = withCourse('course-nutrition-consult', { needsRecord: false });
    assert.deepEqual(changedTaskKinds(off.before, off.after), { grown: [], dropped: [RECORD_TASK_KIND] });
  });

  test('只改了「壓在哪」（Abovee → Examine）：確認之後掛的沒變 → 什麼都沒變', () => {
    const c = withCourse('course-amnion', { systems: ['Examine'] });
    assert.deepEqual(changedTaskKinds(c.before, c.after), { grown: [], dropped: [] });
  });

  test('改的是別的格子（名字、時長、診間）→ 什麼都沒變', () => {
    const c = withCourse('course-amnion', { name: '羊膜注射', durationMin: 45, allowedRoomIds: ['room-t3'] });
    assert.deepEqual(changedTaskKinds(c.before, c.after), { grown: [], dropped: [] });
  });

  test('沒勾過的舊課程（沒有 systems 那一格）存成跟類別推出來一樣的勾法 → 什麼都沒變', () => {
    const { systems, ...old } = BEFORE['course-retest'];
    assert.deepEqual(changedTaskKinds(old, { ...old, systems: ['Abovee', 'Examine', '耀聖'] }), { grown: [], dropped: [] });
  });

  test('新增的課程（沒有改之前的那一份）→ 什麼都沒變：還沒有任何來訪用到它', () => {
    assert.deepEqual(changedTaskKinds(null, BEFORE['course-retest']), { grown: [], dropped: [] });
  });
});

describe('多勾一個系統：已經談定的那幾天補長', () => {
  test('r06 的那一筆：10/20 一段羊膜已經談定 → 多一張耀聖，帶著它掛的那一段', () => {
    const v = visit('v1', '2026-10-20', [slot('course-amnion', 'confirmed')]);
    const out = follow(v, [], AMNION_PLUS);
    assert.deepEqual(out.create.map((t) => [t.kind, t.visitId, t.slotIndexes]), [['耀聖', 'v1', [0]]]);
    assert.equal(out.create[0].dueDate, '2026-10-19', '死線照舊：來訪前一天');
    assert.deepEqual([out.update, out.remove], [[], []]);
  });

  test('長出來的跟「改完設定之後才談定」的那一筆一模一樣（同一支算的）', () => {
    const v = visit('v1', '2026-10-20', [slot('course-amnion', 'confirmed')]);
    const fresh = syncTasksForVisit(v, [], { coursesById: AMNION_PLUS.coursesById, today: TODAY }).create;
    assert.deepEqual(follow(v, [], AMNION_PLUS).create, fresh);
  });

  test('那一天已經過了 → 不長（ADR-0113）；當天照長', () => {
    const past = visit('v1', '2026-10-07', [slot('course-amnion', 'confirmed')]);
    assert.deepEqual(follow(past, [], AMNION_PLUS).create, []);
    const today = visit('v2', TODAY, [slot('course-amnion', 'confirmed')]);
    assert.deepEqual(follow(today, [], AMNION_PLUS).create.map((t) => t.kind), ['耀聖']);
  });

  test('還沒談定（待確認）的段不長 —— 照舊等客人說可以', () => {
    const v = visit('v1', '2026-10-20', [slot('course-amnion', 'pending_confirm')]);
    assert.deepEqual(follow(v, [], AMNION_PLUS).create, []);
  });

  test('同一天兩段：只有談定的那一段長，待確認那一段等它自己談定', () => {
    const v = visit('v1', '2026-10-20', [
      slot('course-amnion', 'confirmed'),
      slot('course-amnion', 'pending_confirm', { startsAt: '14:00', endsAt: '14:30' }),
    ]);
    assert.deepEqual(follow(v, [], AMNION_PLUS).create.map((t) => t.slotIndexes), [[0]]);
  });

  test('同一天有別門課的段：那一門沒改，一張都不多', () => {
    const v = visit('v1', '2026-10-20', [
      slot('course-amnion', 'confirmed'),
      slot('course-retest', 'confirmed', { startsAt: '14:00', endsAt: '14:30' }),
    ]);
    // 回測報告那一段本來就該有 Examine、耀聖 —— 耀聖這一種兩段共用一張，蓋的是「還沒被蓋到的」那幾段
    const existing = [task('t1', 'v1', 'Examine', { slotIndexes: [1] }), task('t2', 'v1', '耀聖', { slotIndexes: [1] })];
    const out = follow(v, existing, AMNION_PLUS);
    assert.deepEqual(out.create.map((t) => [t.kind, t.slotIndexes]), [['耀聖', [0]]]);
    assert.deepEqual(out.remove, []);
  });

  test('已經做完、已經取消的段不長', () => {
    const v = visit('v1', '2026-10-20', [
      slot('course-amnion', 'done'),
      slot('course-amnion', 'cancelled', { startsAt: '14:00', endsAt: '14:30' }),
      slot('course-eecp', 'confirmed', { startsAt: '16:00', endsAt: '17:00' }),
    ]);
    assert.deepEqual(follow(v, [], AMNION_PLUS).create, []);
  });

  test('那一張清掉過（勾過又刪掉）→ 做過了，不再長；復原掉的（沒勾過）→ 照長', () => {
    const v = visit('v1', '2026-10-20', [slot('course-amnion', 'confirmed')]);
    const cleared = task('t1', 'v1', '耀聖', { done: true, deletedAt: '2026-10-07', slotIndexes: [0] });
    assert.deepEqual(follow(v, [cleared], AMNION_PLUS).create, []);
    const undone = task('t1', 'v1', '耀聖', { deletedAt: '2026-10-07', slotIndexes: [0] });
    assert.deepEqual(follow(v, [undone], AMNION_PLUS).create.map((t) => t.kind), ['耀聖']);
  });
});

describe('取消勾選：還沒做的收掉，勾過的不動', () => {
  const LESS = withCourse('course-retest', { systems: ['Abovee', '耀聖'] });

  test('還沒勾的那一張 Examine 收掉、耀聖留著；理由講得出是課程改了', () => {
    const v = visit('v1', '2026-10-20', [slot('course-retest', 'confirmed')]);
    const out = follow(v, [task('t1', 'v1', 'Examine', { slotIndexes: [0] }), task('t2', 'v1', '耀聖', { slotIndexes: [0] })], LESS);
    assert.deepEqual(out.remove.map((r) => r.id), ['t1']);
    assert.match(out.remove[0].reason, /回測報告/);
    assert.match(out.remove[0].reason, /設定/);
    assert.deepEqual([out.create, out.update], [[], []]);
  });

  test('勾過的一張都不動（ADR-0106）', () => {
    const v = visit('v1', '2026-10-20', [slot('course-retest', 'confirmed')]);
    const done = task('t1', 'v1', 'Examine', { done: true, doneAt: '2026-10-07T00:00:00.000Z', slotIndexes: [0] });
    const out = follow(v, [done], LESS);
    assert.deepEqual([out.create, out.update, out.remove], [[], [], []]);
  });

  test('掛在已經結案的來訪上、還沒勾的那一張也收（她忘了掛就做完了）', () => {
    const v = visit('v1', '2026-10-06', [slot('course-retest', 'done')]);
    const out = follow(v, [task('t1', 'v1', 'Examine', { slotIndexes: [0] })], LESS);
    assert.deepEqual(out.remove.map((r) => r.id), ['t1']);
  });

  test('一張蓋兩段、只有一段是這門課 → 縮成只剩還要掛的那一段，不收', () => {
    const v = visit('v1', '2026-10-20', [
      slot('course-retest', 'confirmed'),
      slot('course-fm', 'confirmed', { startsAt: '14:00', endsAt: '14:30' }),
    ]);
    const out = follow(v, [task('t1', 'v1', 'Examine', { slotIndexes: [0, 1] })], LESS);
    assert.deepEqual(out.remove, []);
    assert.deepEqual(out.update, [{ id: 't1', changes: { slotIndexes: [1] } }]);
  });

  test('三個都不勾：掛號那一族全收、一張「取消 X」都不長', () => {
    const none = withCourse('course-retest', { systems: [] });
    const v = visit('v1', '2026-10-20', [slot('course-retest', 'confirmed')]);
    const out = follow(v, [task('t1', 'v1', 'Examine', { slotIndexes: [0] }), task('t2', 'v1', '耀聖', { slotIndexes: [0] })], none);
    assert.deepEqual(out.remove.map((r) => r.id).sort(), ['t1', 't2']);
    assert.deepEqual(out.create, []);
  });
});

describe('取消類一張都不長', () => {
  // 已經取消、收過「取消 Abovee」的段：「壓在哪」改成 Examine 之後，`cancelTasksFor()` 照種類比，
  // 會覺得那一段還欠一張「取消 Examine」—— 那是假的，那一段當初壓的是 Abovee。
  const MOVED = withCourse('course-retest', { systems: ['Examine', '耀聖'] });

  test('一段取消了、收過「取消 Abovee」→ 改了壓在哪，不多長「取消 Examine」', () => {
    const v = visit('v1', '2026-10-20', [
      slot('course-retest', 'cancelled'),
      slot('course-retest', 'confirmed', { startsAt: '14:00', endsAt: '14:30' }),
    ]);
    const existing = [
      task('tc', 'v1', '取消 Abovee', { done: true, slotIndexes: [0] }),
      task('t1', 'v1', 'Examine', { slotIndexes: [1] }),
      task('t2', 'v1', '耀聖', { slotIndexes: [1] }),
    ];
    // 先確定引擎自己真的會想長那一張 —— 不然這一條什麼都沒測到
    const raw = syncTasksForVisit(v, existing, { coursesById: MOVED.coursesById, today: TODAY });
    assert.ok(raw.create.some((t) => isCancelKind(t.kind)), '引擎照種類比，會想長一張取消類');
    const out = follow(v, existing, MOVED);
    assert.deepEqual(out.create.filter((t) => isCancelKind(t.kind)), []);
    assert.deepEqual(out.remove.map((r) => r.id), ['t1'], 'Examine 變成壓表的地方了，確認後不用再掛');
  });

  test('整天取消的來訪：一個字都不動', () => {
    const v = visit('v1', '2026-10-20', [slot('course-retest', 'cancelled')]);
    assert.equal(v.status, 'cancelled');
    const out = follow(v, [task('t1', 'v1', 'Examine', { done: true, slotIndexes: [0] })], MOVED);
    assert.deepEqual([out.create, out.update, out.remove], [[], [], []]);
  });

  test('刪掉的來訪：一個字都不動', () => {
    const v = { ...visit('v1', '2026-10-20', [slot('course-retest', 'confirmed')]), deletedAt: '2026-10-07' };
    const out = follow(v, [task('t1', 'v1', 'Examine', { slotIndexes: [0] })], MOVED);
    assert.deepEqual([out.create, out.update, out.remove], [[], [], []]);
  });
});

describe('寫紀錄', () => {
  const ON = withCourse('course-amnion', { needsRecord: true });
  const OFF = withCourse('course-nutrition-consult', { needsRecord: false });

  test('打開：已經結案的舊來訪不回頭長', () => {
    const v = visit('v1', '2026-09-01', [slot('course-amnion', 'done')]);
    assert.deepEqual(follow(v, [], ON).create, []);
  });

  test('打開：還開著的那一天裡已經做完的那一段，現在就長（那一天下次存檔本來也會長）', () => {
    const v = visit('v1', TODAY, [
      slot('course-amnion', 'done'),
      slot('course-eecp', 'confirmed', { startsAt: '14:00', endsAt: '15:00' }),
    ]);
    assert.deepEqual(follow(v, [], ON).create.map((t) => [t.kind, t.slotIndexes]), [[RECORD_TASK_KIND, [0]]]);
  });

  test('打開：還沒做完的段不長 —— 那一段做完時才長', () => {
    const v = visit('v1', '2026-10-20', [slot('course-amnion', 'confirmed')]);
    assert.deepEqual(follow(v, [], ON).create, []);
    // 之後簽成做了，照平常那條路長
    const closed = closeVisit(v, [true]);
    assert.deepEqual(
      syncTasksForVisit(closed, [], { coursesById: ON.coursesById, today: '2026-10-20' }).create.map((t) => t.kind),
      [RECORD_TASK_KIND],
    );
  });

  test('關掉：掛在已結案來訪上、還沒勾的那一張收掉；勾過的不動', () => {
    const v = visit('v1', '2026-10-01', [slot('course-nutrition-consult', 'done')]);
    const open = task('t1', 'v1', RECORD_TASK_KIND, { slotIndexes: [0] });
    assert.deepEqual(follow(v, [open], OFF).remove.map((r) => r.id), ['t1']);
    const done = { ...open, done: true, doneAt: '2026-10-02T00:00:00.000Z' };
    assert.deepEqual(follow(v, [done], OFF).remove, []);
  });
});

describe('只動這次變了的那幾種', () => {
  test('同一筆上別種還沒對齊的東西（死線、名字）不順手改', () => {
    const v = visit('v1', '2026-10-20', [slot('course-retest', 'confirmed')], { customerName: '王小明改名' });
    const existing = [
      // 死線與名字都跟來訪對不上 —— 那是下一次存這一筆時的事，不是這一次
      task('t1', 'v1', 'Examine', { slotIndexes: [0], dueDate: '2026-10-01' }),
      task('t2', 'v1', '耀聖', { slotIndexes: [0], dueDate: '2026-10-01' }),
    ];
    const out = follow(v, existing, withCourse('course-retest', { needsRecord: true }));
    assert.deepEqual([out.create, out.update, out.remove], [[], [], []]);
  });

  test('什麼都沒變就什麼都不回', () => {
    const v = visit('v1', '2026-10-20', [slot('course-amnion', 'confirmed')]);
    const same = withCourse('course-amnion', { name: '羊膜注射' });
    assert.deepEqual(follow(v, [], same), { create: [], update: [], remove: [] });
  });

  test('算兩次結果一樣：長出來的放回去再算，什麼都不動', () => {
    const v = visit('v1', '2026-10-20', [slot('course-amnion', 'confirmed')]);
    const first = follow(v, [], AMNION_PLUS);
    const again = follow(v, first.create.map((t, i) => ({ ...t, id: `n${i}` })), AMNION_PLUS);
    assert.deepEqual(again, { create: [], update: [], remove: [] });
  });
});

describe('確認框那幾句（ADR-0070：數字是拿同一支試算出來的）', () => {
  const plan = (rows) => ({ rows });
  const row = (visitId, create = [], remove = []) => ({ visitId, create, update: [], remove });

  test('一天都不影響 → 不問（回 null）', () => {
    assert.equal(courseChangeConsequences({ course: BEFORE['course-amnion'], plan: plan([]) }), null);
    assert.equal(courseChangeConsequences({ course: BEFORE['course-amnion'], plan: plan([row('v1')]) }), null);
  });

  test('多長：講幾天、哪一種幾張', () => {
    const out = courseChangeConsequences({
      course: AMNION_PLUS.after,
      plan: plan([row('v1', [{ kind: '耀聖' }]), row('v2', [{ kind: '耀聖' }])]),
    });
    assert.match(out.title, /羊膜/);
    assert.ok(out.consequences.some((l) => l.includes('會影響 2 天')), out.consequences.join('／'));
    assert.ok(out.consequences.some((l) => l.includes('多 2 張') && l.includes('耀聖')), out.consequences.join('／'));
    assert.ok(!out.consequences.some((l) => l.includes('收掉')), '沒有要收的就不講收');
  });

  test('收掉：講幾張、勾過的不動', () => {
    const out = courseChangeConsequences({
      course: BEFORE['course-retest'],
      plan: plan([row('v1', [], [{ id: 't1', kind: 'Examine' }])]),
    });
    assert.ok(out.consequences.some((l) => l.includes('會影響 1 天')));
    assert.ok(out.consequences.some((l) => l.includes('收掉 1 張') && l.includes('Examine')), out.consequences.join('／'));
    assert.ok(out.consequences.some((l) => l.includes('勾過的')), out.consequences.join('／'));
  });

  test('每一項都是一句話；不講「筆」', () => {
    const out = courseChangeConsequences({
      course: AMNION_PLUS.after,
      plan: plan([row('v1', [{ kind: '耀聖' }], [{ id: 't1', kind: 'Examine' }])]),
    });
    for (const line of out.consequences) {
      assert.ok(!/[—-]{2,}$/.test(line) && line.trim().length > 3, line);
      assert.ok(!/\d\s*筆/.test(line), line);
    }
  });
});

describe('只寫任務，不存來訪（掃原始碼）', () => {
  const src = readFileSync(fromRoot('public/js/data/visits.js'), 'utf8');
  const at = src.indexOf('export async function courseTaskPlan(');
  const end = src.indexOf('\nfunction toOps(');
  const body = src.slice(at, end);
  // 註解裡會講到「不走 save()」—— 掃的是程式，不是註解
  const code = body.split('\n').filter((l) => !/^\s*(\/\/|\*|\/\*)/.test(l)).join('\n');

  test('`courseTaskPlan()`／`saveCourseWithTasks()` 在 data/visits.js', () => {
    assert.ok(at > 0, '找不到 courseTaskPlan()');
    assert.ok(body.includes('export async function saveCourseWithTasks('), '找不到 saveCourseWithTasks()');
  });

  test('那一段不叫 `save(`、不寫 visits 這個集合、不跑健檢鏈', () => {
    assert.ok(!/[^a-zA-Z]save\(/.test(code), '走到 save() 就會換 updatedAt、重算次數');
    assert.ok(!/path:\s*PATH[,\s}]/.test(code), '不可以有任何一個寫 visits 的操作');
    assert.ok(!code.includes('followupOps('), '改課程的系統不會讓鏈上的三種變');
  });

  test('長的那一側不用 `listUnclosed()`（它只回今天以前的，正好是不長的那幾天）', () => {
    assert.ok(!code.includes('listUnclosed('));
    assert.ok(code.includes("listByStatus('confirmed')") && code.includes("listByStatus('pending_confirm')"));
  });

  test('任務連清掉的一起讀（ADR-0106）', () => {
    assert.ok(code.includes('listByVisitForSync('));
  });
});
