// 健檢 ↔ 二返。GitHub issue #15。
//
// 這一支測的是那條動線的三段：額度成對、還欠幾次、待辦跟著健檢走。
// 缺任何一段，行事曆上那十筆二返就補不進 app —— 客戶身上沒有二返額度可扣。

import { test, describe } from 'node:test';
import assert from 'node:assert/strict';

import { syncTasksForVisit } from '../public/js/domain/taskRules.js';
import {
  FOLLOWUP_TASK_KIND,
  REPORT_TASK_KIND,
  SEND_REPORT_TASK_KIND,
  DEFAULT_FOLLOWUP_DUE_DAYS,
  DEFAULT_REPORT_DUE_DAYS,
  followupCourseIdOf,
  isFollowupCourse,
  pairsOf,
  missingPairs,
  countMismatches,
  followupDraft,
  owed,
  syncFollowupTasks,
  describePair,
  claimedExams,
  examChoicesFor,
  bookingForExam,
  examStates,
  describeBooking,
  bookingStateForTask,
} from '../public/js/domain/followups.js';

// ---------- 共用的假資料 ----------

const CHECKUP_COURSE = {
  id: 'course-checkup',
  name: '健檢',
  category: 'B',
  durationMin: 120,
  followupCourseId: 'course-followup',
};

const FOLLOWUP_COURSE = {
  id: 'course-followup',
  name: '二返',
  category: 'A',
  durationMin: 30,
};

const RECOVERY_COURSE = { id: 'course-recovery', name: '復能', category: 'C', durationMin: 60 };

const COURSES = {
  'course-checkup': CHECKUP_COURSE,
  'course-followup': FOLLOWUP_COURSE,
  'course-recovery': RECOVERY_COURSE,
};

const checkup = (over = {}) => ({
  id: 'ent-checkup',
  type: 'single',
  label: '0.75萬健檢',
  courseId: 'course-checkup',
  totalQty: 3,
  doneCount: 0,
  bookedCount: 0,
  ...over,
});

const followup = (over = {}) => ({
  id: 'ent-followup',
  type: 'single',
  label: '二返（0.75萬健檢）',
  courseId: 'course-followup',
  totalQty: 3,
  followupForEntitlementId: 'ent-checkup',
  doneCount: 0,
  bookedCount: 0,
  ...over,
});

/** 一筆用掉某份額度的來訪。 */
const visit = (id, date, entitlementId, over = {}) => ({
  id,
  customerId: 'c1',
  customerName: '客戶甲',
  date,
  status: 'done',
  slots: [{ entitlementId, courseId: 'course-checkup' }],
  ...over,
});

const task = (over = {}) => ({
  id: 't1',
  visitId: 'v1',
  customerId: 'c1',
  customerName: '客戶甲',
  kind: FOLLOWUP_TASK_KIND,
  dueDate: '2026-08-08',
  done: false,
  autoGenerated: true,
  ...over,
});

const report = (over = {}) => task({ id: 'tr1', kind: REPORT_TASK_KIND, dueDate: '2026-08-22', ...over });

const CUSTOMER = { id: 'c1', name: '客戶甲' };

const sync = (over = {}) =>
  syncFollowupTasks({
    customer: CUSTOMER,
    entitlements: [checkup(), followup()],
    visits: [],
    tasks: [],
    coursesById: COURSES,
    ...over,
  });

// ---------- 配對 ----------

describe('健檢與二返的配對', () => {
  test('配對記在課程主檔上，不是靠名字比對', () => {
    assert.equal(followupCourseIdOf(CHECKUP_COURSE), 'course-followup');
    assert.equal(followupCourseIdOf(RECOVERY_COURSE), null);
    assert.equal(followupCourseIdOf(undefined), null);
  });

  test('二返自己不會再配一個二返', () => {
    const courses = [CHECKUP_COURSE, FOLLOWUP_COURSE, RECOVERY_COURSE];
    assert.equal(isFollowupCourse('course-followup', courses), true);
    assert.equal(isFollowupCourse('course-checkup', courses), false);
  });

  test('配到的二返額度是用 followupForEntitlementId 指回去的', () => {
    const pairs = pairsOf([checkup(), followup()], COURSES);
    assert.equal(pairs.length, 1);
    assert.equal(pairs[0].source.id, 'ent-checkup');
    assert.equal(pairs[0].followup.id, 'ent-followup');
  });

  test('兩筆健檢各自配各自的，不會配錯', () => {
    const a = checkup({ id: 'ent-a', label: '0.75萬健檢', totalQty: 1 });
    const b = checkup({ id: 'ent-b', label: '5萬健檢(心臟)', totalQty: 2 });
    const fa = followup({ id: 'f-a', followupForEntitlementId: 'ent-a', totalQty: 1 });
    const fb = followup({ id: 'f-b', followupForEntitlementId: 'ent-b', totalQty: 2 });

    const pairs = pairsOf([a, b, fa, fb], COURSES);
    assert.equal(pairs.length, 2);
    assert.equal(pairs.find((p) => p.source.id === 'ent-a').followup.id, 'f-a');
    assert.equal(pairs.find((p) => p.source.id === 'ent-b').followup.id, 'f-b');
  });

  test('沒有配對的課程不會被拉進來', () => {
    const recovery = { id: 'ent-r', type: 'single', courseId: 'course-recovery', totalQty: 12 };
    assert.deepEqual(pairsOf([recovery], COURSES), []);
  });

  test('已刪除的額度不算', () => {
    assert.deepEqual(pairsOf([checkup({ deletedAt: '2026-08-01' })], COURSES), []);

    // 二返被刪掉了 → 這筆健檢重新變成「還沒配對」
    const pairs = pairsOf([checkup(), followup({ deletedAt: '2026-08-01' })], COURSES);
    assert.equal(pairs[0].followup, null);
  });
});

describe('還沒配對的健檢額度', () => {
  test('列得出來，而且附上要建的那一筆長什麼樣', () => {
    const missing = missingPairs([checkup()], COURSES);
    assert.equal(missing.length, 1);
    assert.equal(missing[0].source.id, 'ent-checkup');
    assert.equal(missing[0].draft.totalQty, 3);
    assert.equal(missing[0].draft.followupForEntitlementId, 'ent-checkup');
  });

  test('配過的就不再列', () => {
    assert.deepEqual(missingPairs([checkup(), followup()], COURSES), []);
  });
});

describe('要配出來的那一筆二返額度', () => {
  test('次數照抄健檢：買 N 次健檢就有 N 次二返', () => {
    const draft = followupDraft(checkup({ totalQty: 5 }), FOLLOWUP_COURSE);
    assert.equal(draft.totalQty, 5);
    assert.equal(draft.courseId, 'course-followup');
    assert.equal(draft.type, 'single');
  });

  test('名稱帶上健檢那一筆的名字，兩筆健檢時分得出來', () => {
    assert.equal(
      followupDraft(checkup({ label: '5萬健檢(心臟)' }), FOLLOWUP_COURSE).label,
      '二返（5萬健檢(心臟)）',
    );
  });

  test('購買日與到期日照抄，因為講的是同一次購買', () => {
    const draft = followupDraft(
      checkup({ purchasedAt: '2026-01-05', expiresAt: '2027-01-05', sourcePlanName: '筋骨強身' }),
      FOLLOWUP_COURSE,
    );
    assert.equal(draft.purchasedAt, '2026-01-05');
    assert.equal(draft.expiresAt, '2027-01-05');
    assert.equal(draft.sourcePlanName, '筋骨強身');
  });

  test('計數欄位從零開始，不繼承健檢的', () => {
    const draft = followupDraft(checkup({ doneCount: 2, bookedCount: 1 }), FOLLOWUP_COURSE);
    assert.equal(draft.doneCount, 0);
    assert.equal(draft.bookedCount, 0);
  });
});

describe('配對的次數對不上', () => {
  test('只回報，不修 —— 她可能是故意給的', () => {
    const rows = countMismatches([checkup({ totalQty: 3 }), followup({ totalQty: 2 })], COURSES);
    assert.equal(rows.length, 1);
    assert.equal(rows[0].expected, 3);
    assert.equal(rows[0].actual, 2);
  });

  test('對得上就不出現', () => {
    assert.deepEqual(countMismatches([checkup(), followup()], COURSES), []);
  });
});

// ---------- 還欠幾次 ----------

describe('還欠幾次二返', () => {
  const pair = { source: checkup(), followup: followup() };

  test('健檢還沒做，就還不欠 —— 沒做的健檢沒有報告可以聽', () => {
    assert.equal(owed(pair, []), 0);
  });

  test('做完一次健檢就欠一次', () => {
    assert.equal(owed(pair, [visit('v1', '2026-08-01', 'ent-checkup')]), 1);
  });

  test('買了 3 次只做了 1 次，欠的是 1 不是 3', () => {
    assert.equal(owed(pair, [visit('v1', '2026-08-01', 'ent-checkup')]), 1);
  });

  test('二返已經排進去（還沒上）就不算欠', () => {
    const visits = [
      visit('v1', '2026-08-01', 'ent-checkup'),
      visit('v2', '2026-08-10', 'ent-followup', { status: 'confirmed' }),
    ];
    assert.equal(owed(pair, visits), 0);
  });

  test('二返做完了也不算欠', () => {
    const visits = [
      visit('v1', '2026-08-01', 'ent-checkup'),
      visit('v2', '2026-08-10', 'ent-followup'),
    ];
    assert.equal(owed(pair, visits), 0);
  });

  test('二返被取消，那一次又欠回來 —— 時段還回去了', () => {
    const visits = [
      visit('v1', '2026-08-01', 'ent-checkup'),
      visit('v2', '2026-08-10', 'ent-followup', { status: 'cancelled' }),
    ];
    assert.equal(owed(pair, visits), 1);
  });

  test('健檢標成未到不算做完', () => {
    const visits = [visit('v1', '2026-08-01', 'ent-checkup', { status: 'no_show' })];
    assert.equal(owed(pair, visits), 0);
  });

  test('健檢做超過買的次數時，二返不會跟著無限長', () => {
    const visits = [
      visit('v1', '2026-08-01', 'ent-checkup'),
      visit('v2', '2026-08-05', 'ent-checkup'),
      visit('v3', '2026-08-09', 'ent-checkup'),
      visit('v4', '2026-08-12', 'ent-checkup'),
    ];
    // 買 3 次，做了 4 次 → 上限仍然是 3。超用由資料健檢另外列。
    assert.equal(owed({ source: checkup(), followup: followup() }, visits), 3);
  });

  test('還沒配對就不算欠 —— 沒有額度可扣，長出待辦也沒有用', () => {
    assert.equal(owed({ source: checkup(), followup: null }, [
      visit('v1', '2026-08-01', 'ent-checkup'),
    ]), 0);
  });

  test('已刪除的來訪不算', () => {
    const visits = [visit('v1', '2026-08-01', 'ent-checkup', { deletedAt: '2026-08-02' })];
    assert.equal(owed(pair, visits), 0);
  });
});

// ---------- 待辦 ----------

describe('待辦鏈：追蹤健檢報告 → 約二返', () => {
  test('健檢還沒完成就不產生', () => {
    const visits = [visit('v1', '2026-09-01', 'ent-checkup', { status: 'confirmed' })];
    assert.deepEqual(sync({ visits }).create, []);
  });

  test('健檢標成已完成之後先長出追蹤報告，不是約二返', () => {
    const { create } = sync({ visits: [visit('v1', '2026-08-01', 'ent-checkup')] });
    assert.equal(create.length, 1);
    assert.equal(create[0].kind, REPORT_TASK_KIND, '報告沒到就不可能約');
    assert.equal(create[0].visitId, 'v1');
    assert.equal(create[0].customerId, 'c1');
    assert.equal(create[0].autoGenerated, true);
  });

  test('追蹤報告的死線是健檢日往後算，不是來訪日的前一天', () => {
    const { create } = sync({ visits: [visit('v1', '2026-08-01', 'ent-checkup')] });
    assert.equal(create[0].dueDate, '2026-08-22'); // 8/1 + 21
    assert.equal(DEFAULT_REPORT_DUE_DAYS, 21);
    assert.equal(DEFAULT_FOLLOWUP_DUE_DAYS, 7);
  });

  test('兩個間隔各自可以調', () => {
    const { create } = sync({
      visits: [visit('v1', '2026-08-01', 'ent-checkup')],
      reportDueDays: 30,
    });
    assert.equal(create[0].dueDate, '2026-08-31');
  });

  test('報告勾掉了才長出約二返，死線從勾掉那天算', () => {
    const { create, remove } = sync({
      visits: [visit('v1', '2026-08-01', 'ent-checkup')],
      tasks: [report({ done: true, doneAt: '2026-09-05T02:00:00.000Z' })],
    });

    const booking = create.find((t) => t.kind === FOLLOWUP_TASK_KIND);
    assert.ok(booking);
    assert.equal(booking.dueDate, '2026-09-12', '9/5 + 7，不是健檢日 8/1 + 7');
    assert.deepEqual(remove, [], '勾掉的追蹤報告不刪，那件事真的做過');
  });

  test('doneAt 讀不出來就退回健檢日 + 報告天數 + 約的天數，不用今天', () => {
    const { create } = sync({
      visits: [visit('v1', '2026-08-01', 'ent-checkup')],
      tasks: [report({ done: true, doneAt: null })],
    });
    // 兩張都退回同一個算法（ADR-0065：同一站的兩張，死線一樣）
    for (const t of create) assert.equal(t.dueDate, '2026-08-29', '8/1 + 21 + 7');
  });

  test('報告還沒勾之前，約二返一張都不會出現', () => {
    const { create } = sync({
      visits: [visit('v1', '2026-08-01', 'ent-checkup')],
      tasks: [report()],
    });
    assert.deepEqual(create, []);
  });

  test('報告勾掉之後健檢又被改成未到 —— 未完成的收掉，勾掉的不刪', () => {
    const { create, remove } = sync({
      visits: [visit('v1', '2026-08-01', 'ent-checkup', { status: 'no_show' })],
      tasks: [
        report({ id: 'tr', done: true, doneAt: '2026-09-05T02:00:00.000Z' }),
        task({ id: 'tb' }),
      ],
    });
    assert.deepEqual(create, []);
    assert.deepEqual(remove, [{ id: 'tb', reason: '那一筆健檢不是已完成了' }]);
  });

  // 2026-09-04 **這一條反過來了**。以前是「二返約好了 → 未完成的追蹤報告也跟著
  // 收掉」，理由是「她都去約了，報告顯然拿到了」。那個推論有兩個問題：
  //
  //   1. ADR-0042 自己寫著「**沒有第二個地方記『報告拿到了沒』**，那張任務的
  //      `done` 就是那個狀態」。從別的資料推論出那個狀態，就是第二個地方。
  //   2. ADR-0065 之後，「寄報告給醫師」只在報告那一張被**勾掉**的時候長出來。
  //      她如果先去壓二返、還沒勾報告，收掉那一張等於那一站**永遠到不了** ——
  //      她再也不會被提醒把報告寄給醫師。
  //
  // 所以現在留著。她一勾掉它，寄報告那一張就會補上來。
  test('二返約好了，未完成的追蹤報告還是留著 —— 那一張是「報告拿到了沒」唯一的答案', () => {
    const visits = [
      visit('v1', '2026-08-01', 'ent-checkup'),
      visit('v2', '2026-08-10', 'ent-followup', { status: 'confirmed' }),
    ];
    const { remove } = sync({ visits, tasks: [report({ id: 'tr' })] });
    assert.deepEqual(remove, []);
  });

  // 這一支上線之前，Firestore 裡就有未完成的「約二返」。第一次跑到它們時
  // 找不到對應的追蹤報告 —— 不特別處理的話會被判成「不該存在」而默默收掉，
  // 而那是她真的還沒做的事。
  test('既有的約二返不補追蹤報告，也不動它', () => {
    const { create, update, remove } = sync({
      visits: [visit('v1', '2026-08-01', 'ent-checkup')],
      tasks: [task({ visitId: 'v1', dueDate: '2026-08-08' })],
    });
    assert.deepEqual([create, update, remove], [[], [], []]);
  });

  test('已經有一張了就不再產生', () => {
    const { create, remove } = sync({
      visits: [visit('v1', '2026-08-01', 'ent-checkup')],
      tasks: [task({ visitId: 'v1' })],
    });
    assert.deepEqual(create, []);
    assert.deepEqual(remove, []);
  });

  test('客戶改名時死線與姓名跟著更新，不重建一張', () => {
    const { create, update } = syncFollowupTasks({
      customer: { id: 'c1', name: '客戶甲改名了' },
      entitlements: [checkup(), followup()],
      visits: [visit('v1', '2026-08-01', 'ent-checkup')],
      tasks: [task({ visitId: 'v1', customerName: '客戶甲' })],
      coursesById: COURSES,
    });
    assert.deepEqual(create, []);
    assert.deepEqual(update, [{ id: 't1', changes: { customerName: '客戶甲改名了' } }]);
  });

  test('沒有配對二返額度時不產生 —— 那張待辦點下去無事可做', () => {
    const { create } = sync({
      entitlements: [checkup()],
      visits: [visit('v1', '2026-08-01', 'ent-checkup')],
    });
    assert.deepEqual(create, []);
  });

  test('二返約好之後，還沒做的待辦收掉', () => {
    const visits = [
      visit('v1', '2026-08-01', 'ent-checkup'),
      visit('v2', '2026-08-10', 'ent-followup', { status: 'confirmed' }),
    ];
    const { remove } = sync({ visits, tasks: [task({ visitId: 'v1' })] });
    assert.deepEqual(remove, [{ id: 't1', reason: '二返已經約好了' }]);
  });

  test('健檢被取消時，還沒做的待辦跟著收掉', () => {
    const visits = [visit('v1', '2026-08-01', 'ent-checkup', { status: 'cancelled' })];
    const { remove } = sync({ visits, tasks: [task({ visitId: 'v1' })] });
    assert.deepEqual(remove, [{ id: 't1', reason: '那一筆健檢不是已完成了' }]);
  });

  test('健檢改成未到時，還沒做的待辦跟著收掉', () => {
    const visits = [visit('v1', '2026-08-01', 'ent-checkup', { status: 'no_show' })];
    const { remove } = sync({ visits, tasks: [task({ visitId: 'v1' })] });
    assert.equal(remove.length, 1);
  });

  test('健檢被刪掉時，還沒做的待辦跟著收掉', () => {
    const visits = [visit('v1', '2026-08-01', 'ent-checkup', { deletedAt: '2026-08-02' })];
    const { remove } = sync({ visits, tasks: [task({ visitId: 'v1' })] });
    assert.equal(remove.length, 1);
  });

  test('已經勾完成的待辦一律不刪 —— 那件事真的做過了', () => {
    const visits = [visit('v1', '2026-08-01', 'ent-checkup', { status: 'cancelled' })];
    const { remove } = sync({ visits, tasks: [task({ visitId: 'v1', done: true })] });
    assert.deepEqual(remove, []);
  });

  test('手動加的同名待辦不歸它管', () => {
    const visits = [visit('v1', '2026-08-01', 'ent-checkup', { status: 'cancelled' })];
    const { remove } = sync({
      visits,
      tasks: [task({ visitId: 'v1', autoGenerated: false })],
    });
    assert.deepEqual(remove, []);
  });

  test('做了兩次健檢就有兩張，一次約掉一張只收一張', () => {
    const twice = [
      visit('v1', '2026-08-01', 'ent-checkup'),
      visit('v2', '2026-08-15', 'ent-checkup'),
    ];
    assert.equal(sync({ visits: twice }).create.length, 2);

    // 約掉一次二返 → 只該剩一張，而且留下的是比較早那一筆
    // （二返照順序約，先做的先約）
    const withOne = [...twice, visit('v3', '2026-08-20', 'ent-followup', { status: 'confirmed' })];
    const { create, remove } = sync({
      visits: withOne,
      tasks: [task({ id: 'ta', visitId: 'v1' }), task({ id: 'tb', visitId: 'v2' })],
    });
    assert.deepEqual(create, []);
    assert.equal(remove.length, 1);
  });

  test('全部約完之後兩張都收掉', () => {
    const visits = [
      visit('v1', '2026-08-01', 'ent-checkup'),
      visit('v2', '2026-08-15', 'ent-checkup'),
      visit('v3', '2026-08-20', 'ent-followup', { status: 'confirmed' }),
      visit('v4', '2026-08-25', 'ent-followup', { status: 'confirmed' }),
    ];
    const { remove } = sync({
      visits,
      tasks: [task({ id: 'ta', visitId: 'v1' }), task({ id: 'tb', visitId: 'v2' })],
    });
    assert.equal(remove.length, 2);
  });

  test('兩筆健檢額度各自算各自的', () => {
    const a = checkup({ id: 'ent-a', label: '0.75萬健檢', totalQty: 1 });
    const b = checkup({ id: 'ent-b', label: '5萬健檢(心臟)', totalQty: 1 });
    const fa = followup({ id: 'f-a', followupForEntitlementId: 'ent-a', totalQty: 1 });
    const fb = followup({ id: 'f-b', followupForEntitlementId: 'ent-b', totalQty: 1 });

    const visits = [
      visit('v1', '2026-08-01', 'ent-a'),
      visit('v2', '2026-08-15', 'ent-b'),
      // 只約掉 a 那一份的二返
      visit('v3', '2026-08-20', 'f-a', { status: 'confirmed' }),
    ];

    // 2026-10-08（ADR-0139）：a 那一份的二返只是**約了**，報告照樣要追 —— 兩次健檢各一張。
    // 以前這裡只長 v2 那一張（a 的二返一約掉，a 那一次整條都不長）。
    const { create } = sync({ entitlements: [a, b, fa, fb], visits });
    assert.deepEqual(create.map((t) => `${t.kind}@${t.visitId}`).sort(), [
      `${REPORT_TASK_KIND}@v1`, `${REPORT_TASK_KIND}@v2`,
    ]);

    // a 那一份的二返**做完了**才不長，而它不會抵掉 b 那一份的
    const doneA = visits.map((v) => (v.id === 'v3' ? { ...v, status: 'done' } : v));
    const after = sync({ entitlements: [a, b, fa, fb], visits: doneA });
    assert.deepEqual(after.create.map((t) => t.visitId), ['v2']);

    // 「約二返」那一邊照舊各算各的：兩次的報告都勾過 → a 約掉了不長，b 還欠一次要長
    const ticked = ['v1', 'v2'].map((visitId) =>
      report({ id: `r-${visitId}`, visitId, done: true, doneAt: '2026-09-05T02:00:00.000Z' }));
    const bookings = sync({ entitlements: [a, b, fa, fb], visits, tasks: ticked })
      .create.filter((t) => t.kind === FOLLOWUP_TASK_KIND);
    assert.deepEqual(bookings.map((t) => t.visitId), ['v2']);
  });
});

// ---------- 給畫面的那一句話 ----------

// 2026-08-25：勾掉「追蹤健檢報告」以前不會長出「約二返」（沒有人在勾掉的那一刻
// 叫這一支），而把報告那一張**拿回來**會反過來把它刪掉 —— 判斷「這一筆健檢有沒有
// 追蹤報告的紀錄」時只看了勾掉的那一種。
// 見 .scratch/asks-2026-08-25/issues/09。
describe('報告那一張被拿回來', () => {
  const visits = [visit('v1', '2026-08-01', 'ent-checkup')];

  test('報告變回未完成時，約二返收起來、報告那一張留著', () => {
    const { create, remove } = sync({
      visits,
      tasks: [
        report({ id: 'tr', done: false, doneAt: null }),
        task({ id: 'tb', visitId: 'v1' }),
      ],
    });

    assert.deepEqual(create, [], '報告那一張已經在了，不用再長一張');
    assert.deepEqual(remove, [{ id: 'tb', reason: '報告那一張被拿回來了' }]);
  });

  test('這一筆健檢從來沒有過報告那一張，既有的約二返照樣不動', () => {
    const { create, update, remove } = sync({
      visits,
      tasks: [task({ id: 'tb', visitId: 'v1' })],
    });
    assert.deepEqual([create, update, remove], [[], [], []], '那是這一支上線前就有的資料');
  });

  test('再勾一次報告，約二返又長回來', () => {
    const { create } = sync({
      visits,
      tasks: [report({ id: 'tr', done: true, doneAt: '2026-09-05T02:00:00.000Z' })],
    });
    assert.deepEqual(
      create.map((t) => t.kind).sort(),
      [SEND_REPORT_TASK_KIND, FOLLOWUP_TASK_KIND].sort(),
      '第二站是兩張（ADR-0065）',
    );
  });

  // 2026-09-04 她實測回報：勾掉報告 → 長出兩張 → 再把報告勾回去，
  // 那一張報告**自己被軟刪除了**（不在未完成、不在已完成）。
  // 原因是收掉的判斷只問「在不在 wanted 裡」，而 wanted 的第一道閘門是
  // owed()：二返一壓好或一勾掉，那一次健檢就整個退出候選。
  // 見 .scratch/asks-2026-09-04/issues/01。
  describe('二返那邊已經有進度了，報告還是要留著', () => {
    // 那一場二返（`followupForVisitId` 指回 v1，所以 v1 算是被認領掉了）
    const booked = (status) => ({
      id: 'v2',
      customerId: 'c1',
      date: '2026-09-10',
      status,
      slots: [{
        entitlementId: 'ent-followup',
        courseId: 'course-followup',
        followupForVisitId: 'v1',
      }],
    });

    const taken = [
      report({ id: 'tr', done: false, doneAt: null }),
      task({ id: 'tb' }),
      task({ id: 'ts', kind: SEND_REPORT_TASK_KIND }),
    ];

    for (const status of ['pending', 'confirmed', 'done']) {
      test(`二返已經壓好（${status}）→ 報告留著，另外兩張收掉`, () => {
        const { remove } = sync({ visits: [...visits, booked(status)], tasks: taken });
        assert.deepEqual(
          remove.map((r) => r.id).sort(),
          ['tb', 'ts'],
          '被收掉的只有那兩張衍生的，報告不可以在裡面',
        );
      });
    }

    test('「約二返」已經勾掉了 → 報告還是留著', () => {
      const { remove } = sync({
        visits,
        tasks: [
          report({ id: 'tr', done: false, doneAt: null }),
          task({ id: 'tb', done: true, doneAt: '2026-09-05T02:00:00.000Z' }),
          task({ id: 'ts', kind: SEND_REPORT_TASK_KIND }),
        ],
      });
      assert.deepEqual(remove.map((r) => r.id), ['ts']);
    });

    test('健檢被取消 → 三張一起收，理由講得出來', () => {
      const cancelled = [visit('v1', '2026-08-01', 'ent-checkup', { status: 'cancelled' })];
      const { remove } = sync({ visits: cancelled, tasks: taken });
      assert.deepEqual(
        remove.map((r) => r.reason),
        ['那一筆健檢不是已完成了', '那一筆健檢不是已完成了', '那一筆健檢不是已完成了'],
      );
    });

    test('同一筆健檢底下兩張未完成的報告，只留一張', () => {
      const { remove } = sync({
        visits,
        tasks: [
          report({ id: 'tr-a', done: false, doneAt: null }),
          report({ id: 'tr-b', done: false, doneAt: null }),
        ],
      });
      assert.equal(remove.length, 1);
      assert.equal(remove[0].reason, '這一筆健檢已經有另一張追蹤報告了');
    });
  });
});

describe('客戶詳情頁那一句', () => {
  test('欠的時候講欠幾次', () => {
    const pair = { source: checkup(), followup: followup() };
    const line = describePair(pair, [visit('v1', '2026-08-01', 'ent-checkup')]);
    assert.equal(line.owed, 1);
    assert.match(line.text, /還欠 1 次/);
  });

  test('不欠的時候講已經約掉幾次', () => {
    const pair = { source: checkup(), followup: followup() };
    const line = describePair(pair, [
      visit('v1', '2026-08-01', 'ent-checkup'),
      visit('v2', '2026-08-10', 'ent-followup'),
    ]);
    assert.equal(line.owed, 0);
    assert.match(line.text, /約掉 1 次/);
  });

  test('沒配對就沒有這一句', () => {
    assert.equal(describePair({ source: checkup(), followup: null }, []), null);
  });
});

// ---------- 跟掛號類任務的分工 ----------

describe('這兩張待辦不歸 syncTasksForVisit 管', () => {
  test('健檢那一筆存檔時不會把「約二返」當成多餘的任務刪掉', () => {
    // 這是最容易漏掉的一種：syncTasksForVisit() 看到一張它認不得的自動任務，
    // 會判定「來訪裡已經沒有需要這個任務的課程」而收掉它 —— 而收掉的時機
    // 正好是健檢那一筆存檔的當下，也就是它剛長出來的那一刻。
    const checkupVisit = {
      id: 'v1',
      customerId: 'c1',
      customerName: '客戶甲',
      date: '2026-08-01',
      status: 'done',
      slots: [{ courseId: 'course-checkup', entitlementId: 'ent-checkup' }],
    };

    const { remove } = syncTasksForVisit(
      checkupVisit,
      [task({ visitId: 'v1' })],
      { coursesById: COURSES, today: '2026-08-02' },
    );

    assert.deepEqual(remove, []);
  });

  test('「追蹤健檢報告」也一樣 —— 它剛長出來的那一刻正是健檢存檔的當下', () => {
    const checkupVisit = {
      id: 'v1',
      customerId: 'c1',
      customerName: '客戶甲',
      date: '2026-08-01',
      status: 'done',
      slots: [{ courseId: 'course-checkup', entitlementId: 'ent-checkup' }],
    };

    const { remove } = syncTasksForVisit(
      checkupVisit,
      [report({ visitId: 'v1' })],
      { coursesById: COURSES, today: '2026-08-02' },
    );

    assert.deepEqual(remove, []);
  });

  test('「寄報告給醫師」也一樣（ADR-0065）', () => {
    const checkupVisit = {
      id: 'v1',
      customerId: 'c1',
      customerName: '客戶甲',
      date: '2026-08-01',
      status: 'done',
      slots: [{ courseId: 'course-checkup', entitlementId: 'ent-checkup' }],
    };

    const { remove } = syncTasksForVisit(
      checkupVisit,
      [task({ id: 'ts', visitId: 'v1', kind: SEND_REPORT_TASK_KIND })],
      { coursesById: COURSES, today: '2026-08-02' },
    );

    assert.deepEqual(remove, []);
  });

  test('健檢確認後一件登記都不長 —— 她壓的時候就在 Examine 上登記了', () => {
    const { create } = syncTasksForVisit(
      {
        id: 'v1', customerId: 'c1', customerName: '客戶甲', date: '2026-08-01',
        status: 'confirmed', slots: [{ courseId: 'course-checkup' }],
      },
      [],
      { coursesById: COURSES, today: '2026-07-01' },
    );
    assert.deepEqual(create, []);
  });

  test('約好的二返走一般動線：門診的兩個登記照樣產生', () => {
    const { create } = syncTasksForVisit(
      {
        id: 'v9', customerId: 'c1', customerName: '客戶甲', date: '2026-08-20',
        status: 'confirmed',
        slots: [{ courseId: 'course-followup', entitlementId: 'ent-followup' }],
      },
      [],
      { coursesById: COURSES, today: '2026-08-10' },
    );
    assert.deepEqual(create.map((t) => t.kind).sort(), ['Examine', '耀聖']);
    assert.equal(create[0].dueDate, '2026-08-19', '一般任務的死線仍然是來訪日前一天');
  });
});

// ---------- 一場二返接在哪一次健檢後面 ----------
//
// 連結以前只做到額度那一層，所以「這一次二返是哪一次健檢的」沒有人答得出來。
// 試算表的二返註記照位置猜，而「約二返」那張待辦勾得掉但沒有人檢查真的約了沒。
// 見 `.scratch/followup-and-products/issues/02`。

describe('一場二返接在哪一次健檢後面', () => {
  const pair = { source: checkup(), followup: followup(), followupCourseId: 'course-followup' };

  /** 一場二返：扣二返額度，指著某一次健檢。 */
  const booking = (id, date, examId, over = {}) => ({
    id,
    customerId: 'c1',
    date,
    status: 'confirmed',
    slots: [{
      entitlementId: 'ent-followup',
      courseId: 'course-followup',
      followupForVisitId: examId,
      doctorId: null,
      ...(over.slot ?? {}),
    }],
    ...(over.visit ?? {}),
  });

  const exams = [
    visit('exam-1', '2026-07-06', 'ent-checkup'),
    visit('exam-2', '2026-08-10', 'ent-checkup'),
  ];

  describe('已經被認領掉的健檢', () => {
    test('指得到就收進來', () => {
      const claimed = claimedExams('ent-followup', [...exams, booking('b1', '2026-07-20', 'exam-1')]);
      assert.deepEqual([...claimed.keys()], ['exam-1']);
      assert.equal(claimed.get('exam-1').date, '2026-07-20');
    });

    test('取消掉的那一場不算 —— 那次健檢要放回去讓人重新約', () => {
      const cancelled = booking('b1', '2026-07-20', 'exam-1', { visit: { status: 'cancelled' } });
      assert.equal(claimedExams('ent-followup', [...exams, cancelled]).size, 0);
    });

    test('刪掉的也不算', () => {
      const gone = booking('b1', '2026-07-20', 'exam-1', { visit: { deletedAt: 'x' } });
      assert.equal(claimedExams('ent-followup', [...exams, gone]).size, 0);
    });

    test('沒指到健檢的二返不算認領 —— 舊資料就是這一種', () => {
      assert.equal(claimedExams('ent-followup', [...exams, booking('b1', '2026-07-20', null)]).size, 0);
    });
  });

  describe('壓表時「這是哪一次健檢的」那一排', () => {
    test('做完的健檢都列出來，日期舊的在前 —— 二返是照順序約掉的', () => {
      const out = examChoicesFor(pair, exams);
      assert.deepEqual(out.map((c) => c.date), ['2026-07-06', '2026-08-10']);
    });

    // 2026-09-24（asks-2026-09-24/issues/11）以前是「不列」；她要看得到它現在的狀態
    test('還沒做完的健檢照樣列、標著狀態，但按不下去 —— 沒有報告可以聽', () => {
      const booked = visit('exam-3', '2026-09-01', 'ent-checkup', { status: 'confirmed' });
      const out = examChoicesFor(pair, [...exams, booked]).find((c) => c.visitId === 'exam-3');
      assert.equal(out.status, 'confirmed');
      assert.equal(out.pickable, false);
    });

    test('已經被認領的照樣列出來，但標記起來', () => {
      const out = examChoicesFor(pair, [...exams, booking('b1', '2026-07-20', 'exam-1')]);
      // 藏掉的話她看不出「另外那一次已經約過了」，而那正是她要對照的東西
      assert.equal(out.length, 2);
      assert.deepEqual(out.map((c) => c.taken), [true, false]);
      assert.equal(out[0].bookedOn, '2026-07-20');
    });

    test('正在編輯的那一段自己認領的那一次要給選', () => {
      const mine = booking('b1', '2026-07-20', 'exam-1');
      // 不然一打開編輯器，原本選好的那一顆就按不下去了
      const out = examChoicesFor(pair, [...exams, mine], { excludeVisitId: 'b1' });
      assert.equal(out.find((c) => c.visitId === 'exam-1').taken, false);
    });

    test('沒配到二返額度就沒有候選', () => {
      assert.deepEqual(examChoicesFor({ source: checkup(), followup: null }, exams), []);
    });
  });

  describe('這一次健檢的二返約了沒', () => {
    test('約了就找得到，連那一段一起回', () => {
      const hit = bookingForExam('exam-1', 'ent-followup', [...exams, booking('b1', '2026-07-20', 'exam-1')]);
      assert.equal(hit.visit.date, '2026-07-20');
      assert.equal(hit.slot.followupForVisitId, 'exam-1');
    });

    test('沒約就是 null —— 不要退回照位置猜一個', () => {
      // 猜出來的日期會讓她以為已經約好了，而那正是這一輪要修的東西
      assert.equal(bookingForExam('exam-2', 'ent-followup', [...exams, booking('b1', '2026-07-20', 'exam-1')]), null);
    });

    test('取消掉的那一場不算已約', () => {
      const cancelled = booking('b1', '2026-07-20', 'exam-1', { visit: { status: 'cancelled' } });
      assert.equal(bookingForExam('exam-1', 'ent-followup', [...exams, cancelled]), null);
    });
  });

  describe('每一次健檢現在是什麼狀態', () => {
    test('一次健檢一列，日期舊的在前，各自帶自己的二返', () => {
      const all = [...exams, booking('b1', '2026-07-20', 'exam-1')];
      const out = examStates([checkup(), followup()], COURSES, all);

      assert.deepEqual(out.map((x) => x.examDate), ['2026-07-06', '2026-08-10']);
      assert.equal(out[0].booking.visit.date, '2026-07-20');
      assert.equal(out[1].booking, null);
    });

    test('沒配到二返的健檢不列 —— 它沒有二返要約', () => {
      assert.deepEqual(examStates([checkup()], COURSES, exams), []);
    });
  });
});

describe('約好的那一次健檢就不再要待辦（連結那一層帶來的精準度）', () => {
  const twoExams = [
    visit('exam-1', '2026-07-06', 'ent-checkup'),
    visit('exam-2', '2026-08-10', 'ent-checkup'),
  ];
  const bookedFor = (examId) => ({
    id: `b-${examId}`,
    customerId: 'c1',
    date: '2026-08-20',
    status: 'confirmed',
    slots: [{
      entitlementId: 'ent-followup', courseId: 'course-followup', followupForVisitId: examId,
    }],
  });
  const done = (visitId) => report({ id: `r-${visitId}`, visitId, done: true, doneAt: '2026-08-01T00:00:00Z' });

  test('收掉的是真的約好的那一次，不是隨便一次', () => {
    // `owed()` 算的是「幾張」不是「哪幾張」。沒有這一道的話，被收掉的可能是
    // 另一次健檢的待辦，而真的約掉的那一次反而還掛在那裡 ——
    // 她看到的症狀是「我明明約好了，它還在叫我去約」。
    const { create, remove } = sync({
      visits: [...twoExams, bookedFor('exam-1')],
      tasks: [
        done('exam-1'), done('exam-2'),
        task({ id: 't-1', visitId: 'exam-1' }),
        task({ id: 't-2', visitId: 'exam-2' }),
      ],
    });

    assert.deepEqual(remove.map((r) => r.id), ['t-1'], '收掉的要是 exam-1 那一張');
    assert.deepEqual(
      create.filter((t) => t.kind === FOLLOWUP_TASK_KIND), [], 'exam-2 那一張還在，不用重建',
    );
    // ADR-0065：兩次健檢的報告都勾掉了，所以兩張寄報告都該有 ——
    // **包含 exam-1，雖然它的二返已經約好了。** 那正是第二圈存在的理由。
    assert.deepEqual(
      create.filter((t) => t.kind === SEND_REPORT_TASK_KIND).map((t) => t.visitId).sort(),
      ['exam-1', 'exam-2'],
    );
  });

  test('取消掉的那一場不算約好 —— 待辦要留著', () => {
    const cancelled = { ...bookedFor('exam-1'), status: 'cancelled' };
    const { remove } = sync({
      visits: [...twoExams, cancelled],
      tasks: [done('exam-1'), task({ id: 't-1', visitId: 'exam-1' })],
    });
    assert.deepEqual(remove, []);
  });

  test('舊資料（二返沒指到健檢）行為不變', () => {
    const unlinked = { ...bookedFor('exam-1'), slots: [{ entitlementId: 'ent-followup', courseId: 'course-followup' }] };
    const { remove } = sync({
      visits: [...twoExams, unlinked],
      tasks: [
        done('exam-1'), done('exam-2'),
        task({ id: 't-1', visitId: 'exam-1' }),
        task({ id: 't-2', visitId: 'exam-2' }),
      ],
    });
    // 一場二返、兩次健檢做完 → 還欠 1 次 → 兩張裡收掉一張。哪一張由排序決定，
    // 這裡只斷言「還是收掉一張」，不斷言是哪一張 —— 那正是連結要解決的問題。
    assert.equal(remove.length, 1);
  });
});

describe('「約二返」那一列右邊那一句', () => {
  test('約了就寫出哪天幾點', () => {
    const out = describeBooking({ visit: { date: '2026-09-03' }, slot: { startsAt: '14:00' } });
    assert.equal(out.booked, true);
    assert.ok(out.text.includes('14:00'));
  });

  test('沒約就寫「還沒約」', () => {
    assert.deepEqual(describeBooking(null), { booked: false, text: '還沒約' });
  });

  test('配不到就回 null —— 不要斷言「還沒約」', () => {
    // 斷言一件不知道的事，她會照著它去多約一場。
    const t = task({ visitId: 'exam-1' });
    assert.equal(bookingStateForTask(t, { entitlements: [checkup(), followup()], coursesById: COURSES, visits: [] }), null);
  });

  test('種類不對就回 null', () => {
    const t = report({ visitId: 'exam-1' });
    const visits = [visit('exam-1', '2026-07-06', 'ent-checkup')];
    assert.equal(bookingStateForTask(t, { entitlements: [checkup(), followup()], coursesById: COURSES, visits }), null);
  });

  test('約了就從那一張待辦問得出來', () => {
    const exams = [visit('exam-1', '2026-07-06', 'ent-checkup')];
    const booking = {
      id: 'b1', customerId: 'c1', date: '2026-07-20', status: 'confirmed',
      slots: [{ entitlementId: 'ent-followup', courseId: 'course-followup', followupForVisitId: 'exam-1', startsAt: '10:30' }],
    };
    const out = bookingStateForTask(task({ visitId: 'exam-1' }), {
      entitlements: [checkup(), followup()], coursesById: COURSES, visits: [...exams, booking],
    });
    assert.equal(out.booked, true);
    assert.ok(out.text.includes('10:30'));
  });
});

// ---------------------------------------------------------------------------
// ADR-0065：報告到手的那一刻有兩件事要做
// ---------------------------------------------------------------------------

describe('寄報告給醫師（第二站的第二張）', () => {
  const exam = visit('v1', '2026-08-01', 'ent-checkup');
  const ticked = (over = {}) =>
    report({ id: 'tr', done: true, doneAt: '2026-09-05T02:00:00.000Z', ...over });
  const sent = (over = {}) => task({ id: 'ts', kind: SEND_REPORT_TASK_KIND, ...over });

  test('報告勾掉了 → 兩張一起長出來，死線一樣', () => {
    const { create } = sync({ visits: [exam], tasks: [ticked()] });

    assert.deepEqual(
      create.map((t) => t.kind).sort(),
      [SEND_REPORT_TASK_KIND, FOLLOWUP_TASK_KIND].sort(),
    );
    // 同一個動作的兩半，給兩個可調的天數只會讓她某天發現紅字時間不一樣
    // 而想不起來為什麼。
    assert.equal(new Set(create.map((t) => t.dueDate)).size, 1);
    assert.equal(create[0].dueDate, '2026-09-12', '9/5 + 7');
    for (const t of create) assert.equal(t.visitId, 'v1', '兩張都掛在那一次健檢上');
  });

  // 這一支是整條改動的重點。第一圈受 `owed()` 管，而她一約好二返
  // `owed` 就掉到 0 —— 寄報告擠在同一圈裡的話，還沒寄出去的那一張
  // 會在那一刻被靜默收掉，而畫面上什麼都不說。
  test('**二返約好了、報告還沒寄 → 寄報告那一張還在**', () => {
    const booked = {
      id: 'b1',
      customerId: 'c1',
      date: '2026-09-20',
      status: 'confirmed',
      slots: [{
        entitlementId: 'ent-followup', courseId: 'course-followup', followupForVisitId: 'v1',
      }],
    };
    const { create, remove } = sync({
      visits: [exam, booked],
      tasks: [ticked(), sent()],
    });

    assert.deepEqual(remove, [], '寄報告不因為二返約好了而消失 —— 那是兩件事');
    assert.deepEqual(create, [], '已經有一張了，不要再長一張');
  });

  test('已經寄了（勾掉了）就不再長第二張 —— 存幾次檔都一樣', () => {
    const { create, remove } = sync({
      visits: [exam],
      tasks: [ticked(), sent({ done: true, doneAt: '2026-09-06T00:00:00.000Z' })],
    });
    assert.deepEqual(create.map((t) => t.kind), [FOLLOWUP_TASK_KIND]);
    assert.deepEqual(remove, [], '勾掉的一律不刪');
  });

  test('報告那一張被拿回來 → 寄報告也收起來，理由講得出來', () => {
    const { remove } = sync({
      visits: [exam],
      tasks: [report({ id: 'tr', done: false, doneAt: null }), sent()],
    });
    assert.deepEqual(remove, [{ id: 'ts', reason: '報告那一張被拿回來了' }]);
  });

  test('健檢被改成未到 → 寄報告收起來，理由是那一筆不是已完成了', () => {
    const notDone = { ...exam, status: 'no_show' };
    const { remove } = sync({ visits: [notDone], tasks: [ticked(), sent()] });
    assert.deepEqual(remove.filter((r) => r.id === 'ts'), [
      { id: 'ts', reason: '那一筆健檢不是已完成了' },
    ]);
  });

  // ADR-0042 的舊資料判斷，方向相反但理由一樣：不要無中生有一批
  // 她其實早就做完的事。補一批紅字出來，她第一件事是全部勾掉，
  // 而那讓稽核紀錄多了一批假的「做完了」。
  test('這一支上線前就停在「約二返」的舊資料，不補寄報告', () => {
    const { create, update, remove } = sync({
      visits: [exam],
      tasks: [task({ id: 'tb', visitId: 'v1' })],
    });
    assert.deepEqual([create, update, remove], [[], [], []]);
  });

  test('doneAt 讀不出來時退回健檢日 + 報告天數 + 約的天數，兩張仍然一樣', () => {
    const { create } = sync({ visits: [exam], tasks: [ticked({ doneAt: null })] });
    assert.equal(create.length, 2);
    for (const t of create) assert.equal(t.dueDate, '2026-08-29', '8/1 + 21 + 7');
  });

  test('客戶改名時兩張都跟著改', () => {
    const { update } = sync({
      customer: { id: 'c1', name: '新名字' },
      visits: [exam],
      tasks: [ticked(), sent(), task({ id: 'tb', visitId: 'v1', dueDate: '2026-09-12' })],
    });
    assert.deepEqual(
      update.map((u) => u.id).sort(),
      ['tb', 'ts'],
    );
    for (const u of update) assert.equal(u.changes.customerName, '新名字');
  });
});

// ---------------------------------------------------------------------------
// ADR-0139：報告那一張不等二返約了沒（prelaunch-fixes-2026-10-08/issues/15）
// ---------------------------------------------------------------------------
//
// 她常在同一次就把健檢和二返一起排好。以前「追蹤健檢報告」長出來也要過 `owed()`（還欠幾次二返），
// 先約好二返 → 報告那一張不長 → 「寄報告給醫師」等不到它被勾掉，整條都不長。
// 她 2026-10-08：「照樣長（報告那一張也不受「約好二返」影響）」。
//
// **只改「長出來」**：要不要追報告＝健檢那一段做完了、這一次健檢的二返還沒做完。
// 「約二返」那一圈一個字都沒動，「留著」那一側（ADR-0068）也沒動。

describe('報告那一張不等二返約了沒（ADR-0139）', () => {
  const A = visit('vA', '2026-08-01', 'ent-checkup');
  const B = visit('vB', '2026-09-01', 'ent-checkup');

  /** 一場二返。`examId` 給了就是有連結的那一種；沒給是健檢還沒做完時就先約好的、或匯進來的舊資料。 */
  const second = (id, date, status, examId = null, over = {}) => ({
    id,
    customerId: 'c1',
    customerName: '客戶甲',
    date,
    status,
    slots: [{ entitlementId: 'ent-followup', courseId: 'course-followup', followupForVisitId: examId }],
    ...over,
  });

  const ticked = (visitId, over = {}) =>
    report({ id: `r-${visitId}`, visitId, done: true, doneAt: '2026-09-05T02:00:00.000Z', ...over });

  /** 這一輪會長出哪幾張：`種類@掛在哪一次健檢`。 */
  const grows = (o) => sync(o).create.map((t) => `${t.kind}@${t.visitId}`).sort();

  describe('表的每一格', () => {
    test('二返還沒約、報告還沒勾 → 追蹤健檢報告（照舊）', () => {
      assert.deepEqual(grows({ visits: [A] }), [`${REPORT_TASK_KIND}@vA`]);
    });

    test('二返還沒約、報告勾了 → 約二返＋寄報告（照舊）', () => {
      assert.deepEqual(
        grows({ visits: [A], tasks: [ticked('vA')] }),
        [`${SEND_REPORT_TASK_KIND}@vA`, `${FOLLOWUP_TASK_KIND}@vA`].sort(),
      );
    });

    for (const status of ['pending_confirm', 'confirmed']) {
      test(`健檢和二返同一次排好（二返還接不到健檢，${status}）→ 健檢做完照樣長追蹤健檢報告`, () => {
        const plan = sync({ visits: [A, second('s1', '2026-08-29', status)] });
        assert.deepEqual(plan.create.map((t) => `${t.kind}@${t.visitId}`), [`${REPORT_TASK_KIND}@vA`]);
        assert.equal(plan.create[0].dueDate, '2026-08-22', '死線照舊：健檢日 + 21');
        assert.deepEqual(plan.remove, []);
      });

      test(`二返約了還沒做（有連結，${status}）、報告還沒勾 → 追蹤健檢報告`, () => {
        assert.deepEqual(
          grows({ visits: [A, second('s1', '2026-08-29', status, 'vA')] }),
          [`${REPORT_TASK_KIND}@vA`],
        );
      });
    }

    for (const examId of [null, 'vA']) {
      test(`二返約了還沒做（${examId ? '有' : '沒'}連結）、報告勾了 → 只有寄報告，不可以長約二返`, () => {
        assert.deepEqual(
          grows({ visits: [A, second('s1', '2026-09-20', 'confirmed', examId)], tasks: [ticked('vA')] }),
          [`${SEND_REPORT_TASK_KIND}@vA`],
        );
      });

      test(`二返做完了（${examId ? '有' : '沒'}連結）→ 報告那一張不長`, () => {
        assert.deepEqual(grows({ visits: [A, second('s1', '2026-08-20', 'done', examId)] }), []);
      });

      test(`二返做完了（${examId ? '有' : '沒'}連結）、報告勾過 → 追蹤健檢報告與約二返都不長`, () => {
        const out = grows({ visits: [A, second('s1', '2026-09-20', 'done', examId)], tasks: [ticked('vA')] });
        assert.deepEqual(out.filter((x) => !x.startsWith(SEND_REPORT_TASK_KIND)), []);
      });
    }

    test('勾過「約二返」的那一次（整條鏈結束了）→ 不長報告', () => {
      const settled = task({ id: 'tb', visitId: 'vA', done: true, doneAt: '2026-08-20T00:00:00.000Z' });
      assert.deepEqual(grows({ visits: [A], tasks: [settled] }), []);
      assert.deepEqual(grows({ visits: [A, second('s1', '2026-09-20', 'confirmed')], tasks: [settled] }), []);
    });

    test('有一張開著的「約二返」、從來沒有報告的舊資料 → 不補報告，那一張照舊', () => {
      const { create, update, remove } = sync({ visits: [A], tasks: [task({ id: 'tb', visitId: 'vA' })] });
      assert.deepEqual([create, update, remove], [[], [], []]);
    });

    test('同一張舊的「約二返」在二返約好的那一輪被收掉 —— 同一輪不補報告', () => {
      const { create, remove } = sync({
        visits: [A, second('s1', '2026-09-20', 'confirmed')],
        tasks: [task({ id: 'tb', visitId: 'vA' })],
      });
      assert.deepEqual(create, []);
      assert.deepEqual(remove, [{ id: 'tb', reason: '二返已經約好了' }]);
    });
  });

  describe('二返沒連到哪一次健檢的：有連結的先定案，剩下的才照位置', () => {
    test('A 的二返有連結、約了還沒做；B 的二返做完、沒連結 → 長的是 A，不是比較新的 B', () => {
      assert.deepEqual(
        grows({
          visits: [A, B, second('s1', '2026-10-20', 'confirmed', 'vA'), second('s2', '2026-09-20', 'done')],
        }),
        [`${REPORT_TASK_KIND}@vA`],
      );
    });

    test('一場沒連結的二返做完、A 的報告勾過 → B 要長，不可以被 A 佔掉名額', () => {
      const out = grows({
        visits: [A, B, second('s1', '2026-08-25', 'done')],
        tasks: [ticked('vA'), task({ id: 'ts', visitId: 'vA', kind: SEND_REPORT_TASK_KIND, done: true })],
      });
      assert.ok(out.includes(`${REPORT_TASK_KIND}@vB`), `B 沒有長出報告：${out.join('、')}`);
      assert.ok(!out.includes(`${REPORT_TASK_KIND}@vA`), 'A 的報告勾過了');
    });

    // 同一個情境以前會替 A 長一張「約二返」（A 有待辦所以排前面，而 A 的二返其實做完了）。
    // 現在 B 這一輪要長的報告也算「已經有待辦」—— 不算的話這一輪替 A 長、下一次存檔又收掉。
    test('同一個情境一輪就到定點：不替 A 長一張下一次存檔又要收掉的「約二返」', () => {
      const visits = [A, B, second('s1', '2026-08-25', 'done')];
      const tasks = [ticked('vA'), task({ id: 'ts', visitId: 'vA', kind: SEND_REPORT_TASK_KIND, done: true })];
      const first = sync({ visits, tasks });
      assert.deepEqual(first.create.map((t) => `${t.kind}@${t.visitId}`), [`${REPORT_TASK_KIND}@vB`]);
      const again = sync({ visits, tasks: [...tasks, ...first.create.map((t, i) => ({ ...t, id: `n${i}` }))] });
      assert.deepEqual([again.create, again.update, again.remove], [[], [], []]);
    });

    // ADR-0139「還沒有答案的」那一格，她 2026-10-09 回了（ADR-0142）：
    // > A 照建議的 名額先給報告已勾過的那一次，A 留著「約二返」。多一張提醒可以勾掉，少一張沒人提醒。
    // A 的報告勾過、還沒約二返；B 是健檢和二返同一次排好的，現在做完了。那一場二返沒有連結：
    // 數得出「還欠一次」，認不出是誰的。以前照「已經有待辦的排前面、新的在前」算給 B，A 的「約二返」這一輪不長。
    test('兩次健檢同時在路上、新的那一次的二返是先約好的 → B 長報告；「約二返」名額先給報告勾過的 A', () => {
      const visits = [A, B, second('s1', '2026-09-20', 'confirmed')];
      const tasks = [ticked('vA'), task({ id: 'ts', visitId: 'vA', kind: SEND_REPORT_TASK_KIND, done: true })];
      const first = sync({ visits, tasks });
      assert.deepEqual(
        first.create.map((t) => `${t.kind}@${t.visitId}`).sort(),
        [`${FOLLOWUP_TASK_KIND}@vA`, `${REPORT_TASK_KIND}@vB`].sort(),
      );
      const again = sync({ visits, tasks: [...tasks, ...first.create.map((t, i) => ({ ...t, id: `n${i}` }))] });
      assert.deepEqual([again.create, again.update, again.remove], [[], [], []], '一輪就到定點');
    });

    // 同一個資料狀態，那一場其實是 A 的（她替 A 約了、沒選「這是哪一次健檢的」）也長這樣 —— 認不出來。
    // 這是她接受的代價：A 那一張不會自己收，要她自己勾（ADR-0142）。反過來收掉的話，那一場是 B 的時候 A 就沒人提醒。
    test('A 的「約二返」已經開著、一場沒連結的二返約了、B 做完了 → A 那一張留著', () => {
      const visits = [A, B, second('s1', '2026-09-20', 'confirmed')];
      const tasks = [
        ticked('vA'),
        task({ id: 'ts', visitId: 'vA', kind: SEND_REPORT_TASK_KIND, done: true }),
        task({ id: 'tb', visitId: 'vA', dueDate: '2026-09-12' }),
      ];
      const { create, update, remove } = sync({ visits, tasks });
      assert.deepEqual(remove, []);
      assert.deepEqual(update, []);
      assert.deepEqual(create.map((t) => `${t.kind}@${t.visitId}`), [`${REPORT_TASK_KIND}@vB`]);
    });

    // 兩次的報告都勾了、名額只有一個：已經開著「約二返」的那一次先留（「A 留著」）。照舊「新的在前」的話，
    // 她一勾 B 的報告，A 那一張就被收掉、改長在 B 身上 —— 而那一場二返是跟 B 一起約的時候，A 就沒人提醒了
    // 照位置會把那一場算成最舊的 A 的；但它也可能是跟 B 一起約的（她：「客人常當場一起約」）。
    // 收掉的話那一場是 B 的時候 A 就沒人提醒 —— 開著的那一張留著，要不要勾她決定
    test('A 的「約二返」開著、B 做完、一場沒連結的二返簽成做了（日期在 B 之後）→ A 那一張留著', () => {
      const visits = [A, B, second('s1', '2026-09-20', 'done')];
      const tasks = [
        ticked('vA'),
        task({ id: 'ts', visitId: 'vA', kind: SEND_REPORT_TASK_KIND, done: true }),
        task({ id: 'tb', visitId: 'vA', dueDate: '2026-09-12' }),
        report({ id: 'tr-vB', visitId: 'vB', dueDate: '2026-09-22' }),
      ];
      const { create, update, remove } = sync({ visits, tasks });
      assert.deepEqual([create, update, remove], [[], [], []]);
    });

    test('B 的報告也勾了、A 的「約二返」開著 → A 那一張留著，B 不長', () => {
      const visits = [A, B, second('s1', '2026-09-20', 'confirmed')];
      const tasks = [ticked('vA'), ticked('vB', { id: 'r-vB' }), task({ id: 'tb', visitId: 'vA', dueDate: '2026-09-12' })];
      const { create, remove } = sync({ visits, tasks });
      assert.deepEqual(remove, []);
      assert.ok(!create.some((t) => t.kind === FOLLOWUP_TASK_KIND), create.map((t) => `${t.kind}@${t.visitId}`).join('、'));
    });

    test('兩次的報告都勾了、哪一次都還沒有「約二返」→ 照舊新的在前', () => {
      const visits = [A, B, second('s1', '2026-09-20', 'confirmed')];
      const tasks = [ticked('vA'), ticked('vB', { id: 'r-vB' })];
      const out = grows({ visits, tasks });
      assert.ok(out.includes(`${FOLLOWUP_TASK_KIND}@vB`), out.join('、'));
      assert.ok(!out.includes(`${FOLLOWUP_TASK_KIND}@vA`), out.join('、'));
    });

    test('名額先給報告勾過的，但照位置已經做完二返的那一次不算（二返日期在 B 之前，只可能是 A 的）', () => {
      // 跟上面「一輪就到定點」同一份：那一場二返做完了，照位置配給最舊的 A —— A 不是「報告勾過、還在等二返」
      const visits = [A, B, second('s1', '2026-08-25', 'done')];
      const tasks = [ticked('vA'), task({ id: 'ts', visitId: 'vA', kind: SEND_REPORT_TASK_KIND, done: true })];
      assert.deepEqual(grows({ visits, tasks }), [`${REPORT_TASK_KIND}@vB`]);
    });

    // 切換那天匯進來的幾乎都是這一種：舊的健檢與它的二返都做完了、二返沒有連結。
    // 之後她做第二次健檢、勾掉它的報告 —— 舊的那一次不可以因此冒出一張逾期的報告
    test('舊的那一次健檢二返做完了（沒連結）、新的那一次報告勾過 → 舊的那一次不長', () => {
      const out = grows({ visits: [A, B, second('s1', '2026-08-25', 'done')], tasks: [ticked('vB')] });
      assert.ok(!out.some((x) => x.startsWith(REPORT_TASK_KIND)), out.join('、'));
    });

    // 2026-10-09 審查查到的兩格。兩格的前提都是「約二返」是她自己勾掉的、那一場二返沒有連結 ——
    // 正是 ADR-0142 她接受的代價（「A 那一張要她自己勾」）之後會留下來的樣子。

    // A 的二返做完了（沒連結）；B 是健檢和二返同一次排好的。以前照位置時先把勾過「約二返」的 A 拿掉，
    // 那一場做完的二返就配給「剩下最舊的」B —— B 被當成二返做完了，報告不長、寄報告也等不到
    test('A 的「約二返」勾過、A 的二返做完（沒連結）；B 健檢＋二返同一次排好、B 做完 → B 要長報告', () => {
      const visits = [A, B, second('s1', '2026-08-25', 'done'), second('s2', '2026-10-20', 'confirmed')];
      const tasks = [
        ticked('vA'),
        task({ id: 'ts', visitId: 'vA', kind: SEND_REPORT_TASK_KIND, done: true }),
        task({ id: 'tb', visitId: 'vA', done: true, doneAt: '2026-08-10T02:00:00.000Z' }),
      ];
      const first = sync({ visits, tasks });
      assert.deepEqual(first.create.map((t) => `${t.kind}@${t.visitId}`), [`${REPORT_TASK_KIND}@vB`]);
      const again = sync({ visits, tasks: [...tasks, ...first.create.map((t, i) => ({ ...t, id: `n${i}` }))] });
      assert.deepEqual([again.create, again.update, again.remove], [[], [], []], '一輪就到定點');
    });

    // 決定 2：「二返已經做完」的舊健檢不可以長出報告 —— 切換那天匯進來的全是這種（沒有連結、沒有任何待辦）。
    // B 的「約二返」她先自己勾掉了、那一場還沒記進 app：數得出還欠一次，而沒勾過的只剩照位置算二返做完了的 A。
    // 以前名額就落到 A 身上：A 從來沒有過報告，於是長一張死線是健檢日＋21 天、一出生就逾期的「追蹤健檢報告」
    test('舊的那一次二返做完了（沒連結、從來沒有待辦）、新的那一次的「約二返」她自己勾掉了 → 舊的那一次不長', () => {
      const visits = [A, B, second('s1', '2026-08-25', 'done')];
      const tasks = [
        ticked('vB'),
        task({ id: 'ts', visitId: 'vB', kind: SEND_REPORT_TASK_KIND, done: true }),
        task({ id: 'tb', visitId: 'vB', done: true, doneAt: '2026-09-10T02:00:00.000Z' }),
      ];
      assert.deepEqual(grows({ visits, tasks }), []);
    });

    // 同一格的另一半：照位置算做完的那一次**身上本來就有待辦**的照舊留在名單最後（ADR-0142 第 5 層，寧可多一張）
    test('照位置算二返做完了的那一次，開著的「追蹤健檢報告」不會因此被收掉', () => {
      const visits = [A, B, second('s1', '2026-08-25', 'done')];
      const tasks = [
        report({ id: 'tr-vA', visitId: 'vA', dueDate: '2026-08-22' }),
        ticked('vB'),
        task({ id: 'ts', visitId: 'vB', kind: SEND_REPORT_TASK_KIND, done: true }),
        task({ id: 'tb', visitId: 'vB', done: true, doneAt: '2026-09-10T02:00:00.000Z' }),
      ];
      const { create, update, remove } = sync({ visits, tasks });
      assert.deepEqual([create, update, remove], [[], [], []]);
    });

    test('兩次健檢、一場沒連結的二返約了還沒做 → 兩次的報告都要追', () => {
      assert.deepEqual(
        grows({ visits: [A, B, second('s1', '2026-10-20', 'confirmed')] }),
        [`${REPORT_TASK_KIND}@vA`, `${REPORT_TASK_KIND}@vB`],
      );
    });

    test('兩次健檢、一場沒連結的二返做完 → 只追比較新的那一次（二返是照順序做的）', () => {
      assert.deepEqual(
        grows({ visits: [A, B, second('s1', '2026-08-25', 'done')] }),
        [`${REPORT_TASK_KIND}@vB`],
      );
    });

    test('二返的總次數是上限：只買 1 次二返、健檢做了兩次、二返做完一次 → 一張都不長', () => {
      assert.deepEqual(
        grows({
          entitlements: [checkup(), followup({ totalQty: 1 })],
          visits: [A, B, second('s1', '2026-08-25', 'done')],
        }),
        [],
      );
    });
  });

  describe('每一條判準', () => {
    test('報告勾掉之後：長寄報告，不多一張約二返（健檢和二返同一次排好的那條路走完）', () => {
      const visits = [A, second('s1', '2026-08-29', 'confirmed')];
      const first = sync({ visits });
      assert.deepEqual(first.create.map((t) => t.kind), [REPORT_TASK_KIND]);
      const next = sync({
        visits,
        tasks: [{ ...first.create[0], id: 'tr', done: true, doneAt: '2026-08-20T02:00:00.000Z' }],
      });
      assert.deepEqual(next.create.map((t) => t.kind), [SEND_REPORT_TASK_KIND]);
      assert.deepEqual(next.remove, []);
    });

    for (const status of ['cancelled', 'no_show']) {
      test(`那一場二返${status === 'cancelled' ? '取消了' : '未到'} → 這一次健檢回到「二返還沒約」那一列`, () => {
        const visits = [A, second('s1', '2026-08-29', status, 'vA')];
        assert.deepEqual(grows({ visits }), [`${REPORT_TASK_KIND}@vA`]);
        assert.deepEqual(
          grows({ visits, tasks: [ticked('vA')] }),
          [`${SEND_REPORT_TASK_KIND}@vA`, `${FOLLOWUP_TASK_KIND}@vA`].sort(),
          '報告勾過 → 約二返要回來',
        );
      });
    }

    test('健檢那一段被取消、同一天別段做完了 → 不長（問的是健檢那一段，ADR-0112）', () => {
      const mixed = {
        ...A,
        status: 'done',
        slots: [
          { entitlementId: 'ent-checkup', courseId: 'course-checkup', status: 'cancelled' },
          { entitlementId: 'ent-other', courseId: 'course-recovery', status: 'done' },
        ],
      };
      assert.deepEqual(grows({ visits: [mixed, second('s1', '2026-08-29', 'confirmed')] }), []);
    });

    test('勾過的「追蹤健檢報告」被清掉 → 不再長一張（ADR-0106）', () => {
      const cleared = ticked('vA', { deletedAt: '2026-09-10' });
      const out = grows({ visits: [A, second('s1', '2026-09-20', 'confirmed')], tasks: [cleared] });
      assert.ok(!out.includes(`${REPORT_TASK_KIND}@vA`), out.join('、'));
    });

    test('沒勾過就被收掉的那一張（復原、系統收掉）→ 當成不存在，照樣長', () => {
      const gone = report({ id: 'tr', visitId: 'vA', deletedAt: '2026-08-10' });
      assert.deepEqual(
        grows({ visits: [A, second('s1', '2026-09-20', 'confirmed')], tasks: [gone] }),
        [`${REPORT_TASK_KIND}@vA`],
      );
    });

    test('n返 兩邊都不算：做完的三返不代表二返做完，也不讓報告少長', () => {
      const third = {
        id: 'n1',
        customerId: 'c1',
        date: '2026-08-20',
        status: 'done',
        slots: [{ entitlementId: null, courseId: 'course-followup', followupNth: 3, followupForVisitId: 'vA' }],
      };
      assert.deepEqual(grows({ visits: [A, third] }), [`${REPORT_TASK_KIND}@vA`]);
      assert.deepEqual(
        grows({ visits: [A, third, second('s1', '2026-09-20', 'confirmed')] }),
        [`${REPORT_TASK_KIND}@vA`],
      );
    });

    test('沒有二返額度 → 照舊不長（那張待辦點下去無事可做）', () => {
      assert.deepEqual(grows({ entitlements: [checkup()], visits: [A] }), []);
    });

    test('已經有一張開著的報告 → 不再長第二張；二返後來做完了它照樣留著（ADR-0068）', () => {
      const open = report({ id: 'tr', visitId: 'vA' });
      for (const status of ['confirmed', 'done']) {
        const { create, remove } = sync({ visits: [A, second('s1', '2026-08-29', status)], tasks: [open] });
        assert.deepEqual([create, remove], [[], []], status);
      }
    });

    test('存幾次都一樣：長出來的那一張放回去再算一次，什麼都不動', () => {
      const visits = [A, B, second('s1', '2026-10-20', 'confirmed', 'vA'), second('s2', '2026-10-21', 'confirmed')];
      const first = sync({ visits });
      const tasks = first.create.map((t, i) => ({ ...t, id: `t${i}` }));
      const again = sync({ visits, tasks });
      assert.deepEqual([again.create, again.update, again.remove], [[], [], []]);
    });
  });
});

// ---------- 清掉之後的鏈上任務（prelaunch-audit-2026-09-23/issues/07） ----------
//
// 同 ADR-0106：勾過又被清掉（軟刪除）的照樣算做過；沒勾過就被刪掉的（復原、系統收掉）不算。
// 以前 `mine` 自己濾 `!t.deletedAt`、而 `data/visits.js` 讀的也是不含軟刪除的那一份 ——
// 清掉已完成的「約二返」之後，任何一筆來訪再存一次，它就長回來而且逾期。

describe('清掉的鏈上任務照樣算做過', () => {
  const exam = visit('v1', '2026-08-01', 'ent-checkup');
  const cleared = (t) => ({ ...t, done: true, doneAt: '2026-08-19T02:00:00.000Z', deletedAt: '2026-08-29' });
  const rep = cleared(report({ id: 'tr' }));
  const send = cleared(task({ id: 'ts', kind: SEND_REPORT_TASK_KIND }));
  const book = cleared(task({ id: 'tb', kind: FOLLOWUP_TASK_KIND }));

  test('約二返清掉了（報告、寄報告還在已完成）→ 不長回來', () => {
    const { create } = sync({ visits: [exam], tasks: [{ ...rep, deletedAt: null }, { ...send, deletedAt: null }, book] });
    assert.deepEqual(create, []);
  });

  test('三張都清掉 → 一張都不長', () => {
    const { create, update, remove } = sync({ visits: [exam], tasks: [rep, send, book] });
    assert.deepEqual(create, []);
    assert.deepEqual(update, [], '軟刪除的一個字都不改');
    assert.deepEqual(remove, []);
  });

  test('復原掉的（沒勾過）照樣當成不存在 —— 該長的照長', () => {
    const undone = { ...report({ id: 'tr' }), deletedAt: '2026-08-29' };
    const { create } = sync({ visits: [exam], tasks: [undone] });
    assert.deepEqual(create.map((t) => t.kind), [REPORT_TASK_KIND]);
  });
});

describe('健檢鏈比對讀連軟刪除的那一份', () => {
  test('followupOps()、chainPlans() 與確認框試算用的 chainInputs() 都走 listByCustomerForSync()', async () => {
    const { readFileSync } = await import('node:fs');
    const src = readFileSync(new URL('../public/js/data/visits.js', import.meta.url), 'utf8');
    assert.ok(!src.includes('tasksData.listByCustomer('), '不含軟刪除的那一支看不到清掉的約二返');
    assert.equal(src.split('tasksData.listByCustomerForSync(').length - 1, 3);
    const tasks = readFileSync(new URL('../public/js/data/tasks.js', import.meta.url), 'utf8');
    const at = tasks.indexOf('export function listByCustomerForSync(');
    assert.match(tasks.slice(at, at + 200), /repo\.listWithDeleted\(/);
  });
});

// ---------------------------------------------------------------------------
// 隨機情境：存幾次都一樣（ADR-0142）
// ---------------------------------------------------------------------------
//
// 第一圈的排法改了（報告勾過的先拿名額、開著「約二返」的先留、照位置做完二返的排最後）。
// 排法一有「這一輪的結果改變下一輪的排序」就會一存一變 —— 這一輪長、下一輪收。
// 把這一輪的長、改、收都套回去再算一次，什麼都不該再動。
//
// 不造「開著一張約二返、從來沒有報告」的舊形狀（`stationFor()` 第 2 條）：那一種本來就要兩次存檔才停 ——
// 約二返被收掉之後下一次才補報告（ADR-0139「後果」），上線前的資料才有，切換那天重新匯。

describe('隨機情境：長出來、改、收掉的套回去再算一次，什麼都不再動', () => {
  test('2000 組（一筆配對、0–3 次健檢、0–3 場二返、任意的鏈上待辦）', () => {
    // `Math.imul` 不是 `seed * 1103515245`：後者超過 2^53 掉精度，一萬多個數就繞回同一圈（幾百組在重複）
    let seed = 20261009;
    const rnd = () => { seed = (Math.imul(seed, 1103515245) + 12345) >>> 0; return seed / 2 ** 32; };
    const pick = (list) => list[Math.floor(rnd() * list.length)];
    const STATUSES = ['pending_confirm', 'confirmed', 'done', 'done', 'done', 'no_show', 'cancelled'];
    const day = (i) => `2026-0${1 + Math.floor(i / 28)}-${String(1 + (i % 28)).padStart(2, '0')}`;
    const KINDS = [REPORT_TASK_KIND, FOLLOWUP_TASK_KIND, SEND_REPORT_TASK_KIND];

    for (let n = 0; n < 2000; n += 1) {
      const exams = Math.floor(rnd() * 4);
      const seconds = Math.floor(rnd() * 4);
      const entitlements = [
        checkup({ totalQty: 1 + Math.floor(rnd() * 3) }),
        followup({ totalQty: 1 + Math.floor(rnd() * 3) }),
      ];
      const visits = [];
      for (let i = 0; i < exams; i += 1) {
        visits.push(visit(`x${i}`, day(i * 20 + Math.floor(rnd() * 10)), 'ent-checkup', { status: pick(STATUSES) }));
      }
      for (let i = 0; i < seconds; i += 1) {
        const link = rnd() < 0.5 && exams ? `x${Math.floor(rnd() * exams)}` : null;
        visits.push({
          id: `s${i}`, customerId: 'c1', date: day(100 + i * 9), status: pick(STATUSES),
          slots: [{ entitlementId: 'ent-followup', courseId: 'course-followup', followupForVisitId: link }],
        });
      }
      const drawn = [];
      for (let i = 0; i < exams; i += 1) {
        for (const kind of KINDS) {
          const r = rnd();
          if (r < 0.55) continue;
          drawn.push(task({
            id: `t-${kind}-${i}`, visitId: `x${i}`, kind, dueDate: '2026-06-10',
            done: r > 0.8, doneAt: r > 0.8 ? '2026-06-01T00:00:00.000Z' : null,
            deletedAt: rnd() < 0.1 ? '2026-06-02' : null,
          }));
        }
      }
      const reportTicked = (id) => drawn.some((t) => t.kind === REPORT_TASK_KIND && t.visitId === id && t.done);
      const tasks = drawn.filter((t) => t.kind !== FOLLOWUP_TASK_KIND || reportTicked(t.visitId));

      const first = sync({ entitlements, visits, tasks });
      const removed = new Set(first.remove.map((r) => r.id));
      const changed = new Map(first.update.map((u) => [u.id, u.changes]));
      const after = [
        ...tasks.map((t) => (removed.has(t.id) ? { ...t, deletedAt: '2026-10-09' } : { ...t, ...changed.get(t.id) })),
        ...first.create.map((t, i) => ({ ...t, id: `new${i}` })),
      ];
      const again = sync({ entitlements, visits, tasks: after });
      assert.deepEqual([again.create, again.update, again.remove], [[], [], []], `第 ${n} 組又動了`);
    }
  });
});
