// 二返可以先接上還沒做完的那一次健檢（.scratch/followup-link-before-exam，ADR-0145）。
//
// 她 2026-10-09：
//
// > B 照建議的根本解法：允許先約，約的時候就綁在那次健檢上（讓「這是哪一次健檢的」那一排也列得出還沒做的健檢）。
// > 不要禁止先約，因為客人常當場一起約。
//
// 推翻 9/24 那一句「只有已完成按得下去」（asks-2026-09-24/issues/11）。取消、未到照舊按不下去 —— 那一次不會有報告。

import { test, describe } from 'node:test';
import assert from 'node:assert/strict';

import {
  examChoicesFor, owed, syncFollowupTasks, claimedExams, cannotClose, closeBlocks,
  FOLLOWUP_TASK_KIND, REPORT_TASK_KIND, SEND_REPORT_TASK_KIND,
} from '../public/js/domain/followups.js';
import { validateVisit, visitStatusFrom, closeVisit, rebookSlot } from '../public/js/domain/visits.js';
import {
  closeConsequences, cancelConsequences, cancelChainLines, rebookConsequences,
} from '../public/js/domain/consequences.js';
import { examChoicesForNth, nthSlotFields } from '../public/js/domain/nthFollowup.js';
import { slotOptionsFor } from '../public/js/domain/slotOptions.js';

const COURSES = [
  { id: 'c-exam', name: '健檢', assigns: 'none', doctorPick: 'none', followupCourseId: 'c-fu' },
  { id: 'c-fu', name: '二返', assigns: 'none', doctorPick: 'none' },
];
const coursesById = Object.fromEntries(COURSES.map((c) => [c.id, c]));
const ENTS = [
  { id: 'e-exam', type: 'single', label: '健檢', courseId: 'c-exam', totalQty: 3 },
  { id: 'e-fu', type: 'single', label: '二返', courseId: 'c-fu', totalQty: 3, followupForEntitlementId: 'e-exam' },
];
const pair = { source: ENTS[0], followup: ENTS[1] };

const visitOf = (id, date, slots) => {
  const v = { id, customerId: 'c1', customerName: '客戶A', date, slots };
  return { ...v, status: visitStatusFrom(v) };
};
const exam = (id, date, status) => visitOf(id, date, [
  { entitlementId: 'e-exam', courseId: 'c-exam', courseName: '健檢', startsAt: '09:00', endsAt: '10:00', status },
]);
const second = (id, date, status, to) => visitOf(id, date, [
  { entitlementId: 'e-fu', courseId: 'c-fu', courseName: '二返', startsAt: '11:00', endsAt: '11:30', status, followupForVisitId: to },
]);
const task = (id, kind, visitId, done, o = {}) => ({
  id, kind, visitId, customerId: 'c1', done, doneAt: done ? '2026-09-25T02:00:00.000Z' : null, autoGenerated: true, ...o,
});
const chain = (visits, tasks = []) => syncFollowupTasks({
  customer: { id: 'c1', name: '客戶A' }, entitlements: ENTS, visits, tasks, coursesById,
});
const ask = (visit, customerVisits) => validateVisit(visit, {
  customer: { id: 'c1', flags: [] }, entitlements: ENTS, courses: COURSES, equipment: [],
  rooms: [], staff: [], ivProducts: [], customerVisits, sameDayVisits: [],
});
const aboutExam = (list) => list.filter((e) => e.includes('健檢'));

describe('「這是哪一次健檢的」那一排：排著的也按得下去', () => {
  const world = [
    exam('e1', '2026-09-01', 'done'),
    exam('e2', '2026-10-01', 'confirmed'),
    exam('e3', '2026-10-05', 'pending_confirm'),
    exam('e4', '2026-10-06', 'no_show'),
    exam('e5', '2026-10-07', 'cancelled'),
  ];

  test('待確認、已確認、已完成按得下去；取消、未到照舊按不下去', () => {
    const out = examChoicesFor(pair, world);
    assert.deepEqual(out.map((c) => c.status), ['done', 'confirmed', 'pending_confirm', 'no_show', 'cancelled']);
    assert.deepEqual(out.map((c) => c.pickable), [true, true, true, false, false]);
  });

  test('被別場活著的二返佔走的，排著的那一次也按不下去', () => {
    const out = examChoicesFor(pair, [...world, second('f', '2026-10-20', 'confirmed', 'e2')]);
    const e2 = out.find((c) => c.visitId === 'e2');
    assert.equal(e2.taken, true);
    assert.equal(e2.pickable, false);
  });

  test('佔著那一次的二返取消了：放回去', () => {
    const out = examChoicesFor(pair, [...world, second('f', '2026-10-20', 'cancelled', 'e2')]);
    assert.equal(out.find((c) => c.visitId === 'e2').pickable, true);
    assert.equal(claimedExams('e-fu', [...world, second('f', '2026-10-20', 'cancelled', 'e2')]).size, 0);
  });
});

describe('存檔驗證：接到排著的健檢存得下去，接到取消、未到的擋', () => {
  const world = [
    exam('e2', '2026-10-01', 'confirmed'),
    exam('e3', '2026-10-05', 'pending_confirm'),
    exam('e4', '2026-10-06', 'no_show'),
    exam('e5', '2026-10-07', 'cancelled'),
  ];
  const draft = (to) => ({ ...second(null, '2026-10-24', 'pending_confirm', to), id: undefined });

  test('已確認、待確認：沒有 error', () => {
    assert.deepEqual(aboutExam(ask(draft('e2'), world).errors), []);
    assert.deepEqual(aboutExam(ask(draft('e3'), world).errors), []);
  });

  test('未到、取消：擋下來，講出它是什麼狀態', () => {
    for (const to of ['e4', 'e5']) {
      const errors = aboutExam(ask(draft(to), world).errors);
      assert.equal(errors.length, 1, to);
      assert.match(errors[0], /不會有報告/);
    }
  });

  test('存著的那一份本來就指著它（健檢後來取消了）：改別的照樣存得下去（ADR-0011）', () => {
    const stored = second('f', '2026-10-24', 'confirmed', 'e5');
    const edited = { ...stored, slots: [{ ...stored.slots[0], note: '改了一句' }] };
    assert.deepEqual(aboutExam(ask(edited, [...world, stored]).errors), []);
  });

  test('二返自己改時間（舊的那一段取消、新的接在尾巴帶同一個連結）：不當成新接上的', () => {
    const stored = second('f', '2026-10-24', 'confirmed', 'e5');
    const rebooked = {
      ...stored,
      slots: [
        { ...stored.slots[0], status: 'cancelled' },
        { ...stored.slots[0], startsAt: '15:00', endsAt: '15:30', status: 'pending_confirm' },
      ],
    };
    assert.deepEqual(aboutExam(ask(rebooked, [...world, stored]).errors), []);
  });
});

describe('owed()：接在一次還沒做完的健檢上的二返，不算「約掉了一次」', () => {
  // A 做完、報告勾過、「約二返」開著；B 是健檢和二返當場一起約的（B 還沒做）
  const A = exam('A', '2026-09-01', 'done');
  const B = exam('B', '2026-10-01', 'confirmed');
  const fuB = second('F', '2026-10-24', 'pending_confirm', 'B');
  const tasks = [
    task('t-rep-A', REPORT_TASK_KIND, 'A', true),
    task('t-book-A', FOLLOWUP_TASK_KIND, 'A', false, { dueDate: '2026-10-02' }),
    task('t-send-A', SEND_REPORT_TASK_KIND, 'A', true),
  ];

  test('還欠的那一次照舊是 A 的', () => {
    assert.equal(owed(pair, [A, B, fuB]), 1);
  });

  test('約好 B 的二返那一刻，A 開著的「約二返」沒有被收掉', () => {
    const plan = chain([A, B, fuB], tasks);
    assert.deepEqual(plan.remove, []);
    assert.deepEqual(plan.create, []);
  });

  test('B 簽成做了：長 B 的追蹤健檢報告、不長 B 的約二返；A 的照舊留著', () => {
    const Bdone = exam('B', '2026-10-01', 'done');
    const plan = chain([A, Bdone, fuB], tasks);
    assert.deepEqual(plan.create.map((t) => `${t.kind}@${t.visitId}`), [`${REPORT_TASK_KIND}@B`]);
    assert.deepEqual(plan.remove, []);
  });

  test('B 的報告勾掉：只多「寄報告給醫師」，不長 B 的約二返', () => {
    const Bdone = exam('B', '2026-10-01', 'done');
    const plan = chain([A, Bdone, fuB], [...tasks, task('t-rep-B', REPORT_TASK_KIND, 'B', true)]);
    assert.deepEqual(plan.create.map((t) => `${t.kind}@${t.visitId}`), [`${SEND_REPORT_TASK_KIND}@B`]);
    assert.deepEqual(plan.remove, []);
  });

  test('B 取消了：那一場二返照樣不算約掉（A 的照舊）', () => {
    assert.equal(owed(pair, [A, exam('B', '2026-10-01', 'cancelled'), fuB]), 1);
  });

  test('連結指到的那一次不在手上這一份裡（刪掉的、或只給了部分來訪）：照舊算約掉 —— 不憑空多長一張', () => {
    assert.equal(owed(pair, [A, fuB]), 0);
  });

  test('沒連結的照舊算約掉（舊資料一個字都不動）', () => {
    assert.equal(owed(pair, [A, B, second('F', '2026-10-24', 'pending_confirm', null)]), 0);
  });
});

// ---------- 03 n返 一起放寬（她 10/9：「放寬」）----------

describe('n返：跟二返同一條 —— 排著的與做完的接得上，取消、未到接不上', () => {
  const nth = (id, date, to, status = 'pending_confirm') => visitOf(id, date, [{
    ...nthSlotFields({ nth: 3, examVisitId: to, courseId: 'c-fu' }),
    startsAt: '14:00', endsAt: '14:30', status,
  }]);
  const world = [
    exam('e1', '2026-09-01', 'done'),
    exam('e2', '2026-10-01', 'confirmed'),
    exam('e3', '2026-10-05', 'pending_confirm'),
    exam('e4', '2026-10-06', 'no_show'),
    exam('e5', '2026-10-07', 'cancelled'),
  ];

  test('那一排：待確認、已確認、已完成按得下去', () => {
    const out = examChoicesForNth({ entitlements: ENTS, coursesById, visits: world });
    assert.deepEqual(out.map((c) => c.pickable), [true, true, true, false, false]);
  });

  test('「＋ n返」那一顆：只有一次排著的健檢也畫', () => {
    const opts = slotOptionsFor({ entitlements: ENTS, visits: [exam('e2', '2026-10-01', 'confirmed')], courses: COURSES, pools: [] });
    assert.ok(opts.some((o) => o.isNth), '排著的那一次接得上，那一顆就要在');
    assert.ok(!slotOptionsFor({ entitlements: ENTS, visits: [exam('e5', '2026-10-07', 'cancelled')], courses: COURSES, pools: [] })
      .some((o) => o.isNth), '只有取消的就不畫');
  });

  test('存檔：接已確認的存得下去；接取消、未到的擋下來', () => {
    assert.deepEqual(aboutExam(ask(nth(undefined, '2026-10-24', 'e2'), world).errors), []);
    for (const to of ['e4', 'e5']) {
      const errors = aboutExam(ask(nth(undefined, '2026-10-24', to), world).errors);
      assert.equal(errors.length, 1, to);
      assert.match(errors[0], /不會有報告/);
    }
  });

  test('健檢後來取消了：接在它上面的 n返 那一天改別的照樣存得下去（以前 n返 每一次都驗）', () => {
    const stored = nth('n', '2026-10-24', 'e5', 'confirmed');
    const edited = { ...stored, slots: [{ ...stored.slots[0], note: '改了一句' }] };
    assert.deepEqual(aboutExam(ask(edited, [...world, stored]).errors), []);
  });

  test('指到的那一天根本不是健檢：每一次都擋', () => {
    const rehab = visitOf('r', '2026-09-01', [{ entitlementId: null, courseId: 'c-fu', startsAt: '09:00', endsAt: '10:00', status: 'done' }]);
    const stored = nth('n', '2026-10-24', 'r', 'confirmed');
    assert.equal(aboutExam(ask(stored, [rehab, stored]).errors).length, 1);
  });
});

// ---------- 04 一次健檢只接一場二返（ADR-0022：額度成對、次數一樣；要多約走 n返）----------

describe('存檔驗證：同一次健檢已經接了一場活著的二返 → 擋', () => {
  const B = exam('B', '2026-10-01', 'confirmed');
  const draft = () => ({ ...second(null, '2026-11-05', 'pending_confirm', 'B'), id: undefined });

  test('另一場活著的二返已經接在 B 上：擋下來、講出是哪一天那一場', () => {
    const other = second('F1', '2026-10-24', 'confirmed', 'B');
    const errors = aboutExam(ask(draft(), [B, other]).errors);
    assert.equal(errors.length, 1, errors.join('｜'));
    assert.match(errors[0], /已經接了 10\/24\(六\) 那一場二返/);
    assert.match(errors[0], /n返/);
  });

  test('佔著它的那一場取消了、或沒來：放回去了，存得下去', () => {
    for (const st of ['cancelled', 'no_show']) {
      assert.deepEqual(aboutExam(ask(draft(), [B, second('F1', '2026-10-24', st, 'B')]).errors), [], st);
    }
  });

  test('兩場本來就都接在 B 上（舊資料）：改其中一場的別的照樣存得下去 —— 資料健檢會列出來', () => {
    const f1 = second('F1', '2026-10-24', 'confirmed', 'B');
    const f2 = second('F2', '2026-11-05', 'confirmed', 'B');
    const edited = { ...f2, slots: [{ ...f2.slots[0], note: '改了一句' }] };
    assert.deepEqual(aboutExam(ask(edited, [B, f1, f2]).errors), []);
  });

  test('畫面上那一排沒看到佔走它的那一場也擋得住 —— 驗證拿的是全部來訪', () => {
    // 壓表那一排只讀到目標月份月底；存檔前重讀的是全部（`customerVisits`）
    const later = second('F1', '2027-01-10', 'pending_confirm', 'B');
    assert.equal(aboutExam(ask(draft(), [B, later]).errors).length, 1);
  });

  test('同一筆裡二返改時間（舊的那一段取消、新的帶同一個連結）不被自己擋', () => {
    const stored = second('F1', '2026-10-24', 'confirmed', 'B');
    const rebooked = { ...stored, slots: [
      { ...stored.slots[0], status: 'cancelled' },
      { ...stored.slots[0], startsAt: '15:00', endsAt: '15:30', status: 'pending_confirm' },
    ] };
    assert.deepEqual(aboutExam(ask(rebooked, [B, stored]).errors), []);
  });
});

// ---------- 05 簽療程單：接的那一次健檢還沒做完，二返那一段簽不成「做了」----------

describe('簽療程單擋：二返比它接的健檢先簽成做了', () => {
  const B = exam('B', '2026-10-01', 'confirmed');
  const fu = second('F', '2026-10-24', 'confirmed', 'B');
  const ctx = (visits) => ({ entitlements: ENTS, visits });

  test('接的那一次還沒做完：那一段 ✓ 簽不下去、講得出是哪一天的健檢', () => {
    assert.deepEqual([...cannotClose(fu, 0, [true], ctx([B, fu]))?.examDate ?? ''].join(''), '2026-10-01');
    assert.deepEqual([...closeBlocks(fu, [true], ctx([B, fu])).keys()], [0]);
  });

  test('closeVisit() 帶著 guard 自己也擋：那一段當成先不結', () => {
    const after = closeVisit(fu, [true], '2026-10-24T05:00:00.000Z', ctx([B, fu]));
    assert.equal(after.slots[0].status, 'confirmed');
    assert.equal(closeVisit(fu, [false], '2026-10-24T05:00:00.000Z', ctx([B, fu])).slots[0].status, 'no_show', '✗ 照樣按得下去');
  });

  test('接的那一次做完了：照常', () => {
    assert.equal(cannotClose(fu, 0, [true], ctx([exam('B', '2026-10-01', 'done'), fu])), null);
  });

  test('同一天健檢＋二返，同一張抽屜兩段都 ✓：可以；只 ✓ 二返不行', () => {
    const day = visitOf('D', '2026-10-24', [
      { entitlementId: 'e-exam', courseId: 'c-exam', startsAt: '09:00', endsAt: '10:00', status: 'confirmed' },
      { entitlementId: 'e-fu', courseId: 'c-fu', startsAt: '11:00', endsAt: '11:30', status: 'confirmed', followupForVisitId: 'D' },
    ]);
    assert.equal(cannotClose(day, 1, [true, true], ctx([day])), null);
    assert.ok(cannotClose(day, 1, [null, true], ctx([day])));
  });

  test('沒連結的二返照舊簽得下去；接的那一次不在手上這一份裡也不擋（不知道就不擋）', () => {
    const loose = second('F', '2026-10-24', 'confirmed', null);
    assert.equal(cannotClose(loose, 0, [true], ctx([B, loose])), null);
    assert.equal(cannotClose(fu, 0, [true], ctx([fu])), null);
  });

  test('n返 同一條', () => {
    const n = visitOf('N', '2026-10-24', [{
      ...nthSlotFields({ nth: 3, examVisitId: 'B', courseId: 'c-fu' }), startsAt: '14:00', endsAt: '14:30', status: 'confirmed',
    }]);
    assert.ok(cannotClose(n, 0, [true], ctx([B, n])));
  });

  test('抽屜那一句講出這一段先不結、會扣的不算它', () => {
    const lines = closeConsequences({ visit: fu, picks: [true], entitlements: ENTS, coursesById, visits: [B, fu], tasks: [] });
    assert.ok(lines.some((l) => /健檢（10\/1\(四\)）還沒做完/.test(l)), lines.join('｜'));
    assert.ok(!lines.some((l) => l.includes('扣掉次數')), lines.join('｜'));
  });
});


// ---------- 06 健檢取消或未到：確認框講「後面接著一場二返，不會跟著改」（她：只提醒、不連動）----------

describe('健檢取消／未到：講出後面接著的二返', () => {
  const B = exam('B', '2026-10-01', 'confirmed');
  const fuB = second('F', '2026-10-24', 'confirmed', 'B');
  const chain = { entitlements: ENTS, tasks: [] };
  const said = /10\/24\(六\) 那一場二返接在 10\/1\(四\) 那一次健檢後面 —— 不會跟著取消/;

  test('取消健檢那一段（日曆長按、編輯器 ×）：講那一句、叫她回去換', () => {
    const lines = cancelConsequences({ visit: B, coursesById, slotIndex: 0, customerVisits: [B, fuB], chain });
    assert.ok(lines.some((l) => said.test(l)), lines.join('｜'));
    assert.ok(lines.some((l) => l.includes('換「這是哪一次健檢的」')), lines.join('｜'));
  });

  test('取消整天也講', () => {
    const lines = cancelConsequences({ visit: B, coursesById, customerVisits: [B, fuB], chain });
    assert.ok(lines.some((l) => said.test(l)), lines.join('｜'));
  });

  test('一次取消好幾段（批次取消、確認抽屜）：全部套上去之後講一次', () => {
    const lines = cancelChainLines({
      customer: { id: 'c1', name: '客戶A' }, visits: [B, fuB], cancels: [{ visit: B, at: [0] }], chain, coursesById,
    });
    assert.ok(lines.some((l) => said.test(l)), lines.join('｜'));
  });

  test('二返那一場自己也一起取消了、或後面沒有接二返：不講', () => {
    const both = cancelChainLines({
      customer: { id: 'c1' }, visits: [B, fuB], cancels: [{ visit: B, at: [0] }, { visit: fuB, at: [0] }], chain, coursesById,
    });
    assert.ok(!both.some((l) => l.includes('不會跟著')), both.join('｜'));
    const alone = cancelConsequences({ visit: B, coursesById, slotIndex: 0, customerVisits: [B], chain });
    assert.ok(!alone.some((l) => l.includes('不會跟著')), alone.join('｜'));
  });

  test('簽療程單抽屜：健檢那一段按 ✗ → 「不會跟著改成未到」', () => {
    const lines = closeConsequences({ visit: B, picks: [false], entitlements: ENTS, coursesById, visits: [B, fuB], tasks: [] });
    assert.ok(lines.some((l) => /那一場二返接在 10\/1\(四\) 那一次健檢後面 —— 不會跟著改成未到/.test(l)), lines.join('｜'));
  });

  test('健檢那一段改成別的課程（`rebookSlot()`）＝那一筆沒有活著的健檢了：講；只改時間：不講', () => {
    const other = rebookSlot(B, 0, { ...B.slots[0], entitlementId: 'e-fu', courseId: 'c-fu', courseName: '二返' });
    const lines = rebookConsequences({ before: B, after: other, index: 0, coursesById, customerVisits: [B, fuB], entitlements: ENTS }).lines;
    assert.ok(lines.some((l) => said.test(l)), lines.join('｜'));
    const moved = rebookSlot(B, 0, { ...B.slots[0], startsAt: '13:00', endsAt: '15:00' });
    assert.ok(!rebookConsequences({ before: B, after: moved, index: 0, coursesById, customerVisits: [B, fuB], entitlements: ENTS })
      .lines.some((l) => l.includes('不會跟著')));
  });
});

