// 二返可以先接上還沒做完的那一次健檢（.scratch/followup-link-before-exam，ADR-0145）。
//
// 她 2026-10-09：
//
// > B 照建議的根本解法：允許先約，約的時候就綁在那次健檢上（讓「這是哪一次健檢的」那一排也列得出還沒做的健檢）。
// > 不要禁止先約，因為客人常當場一起約。
//
// 推翻 9/24 那一句「只有已完成按得下去」（asks-2026-09-24/issues/11）。取消、未到照舊按不下去 —— 那一次不會有報告。

import { test, describe } from 'node:test';
import assert from 'node:assert/strict';

import {
  examChoicesFor, owed, syncFollowupTasks, claimedExams,
  FOLLOWUP_TASK_KIND, REPORT_TASK_KIND, SEND_REPORT_TASK_KIND,
} from '../public/js/domain/followups.js';
import { validateVisit, visitStatusFrom } from '../public/js/domain/visits.js';

const COURSES = [
  { id: 'c-exam', name: '健檢', assigns: 'none', doctorPick: 'none', followupCourseId: 'c-fu' },
  { id: 'c-fu', name: '二返', assigns: 'none', doctorPick: 'none' },
];
const coursesById = Object.fromEntries(COURSES.map((c) => [c.id, c]));
const ENTS = [
  { id: 'e-exam', type: 'single', label: '健檢', courseId: 'c-exam', totalQty: 3 },
  { id: 'e-fu', type: 'single', label: '二返', courseId: 'c-fu', totalQty: 3, followupForEntitlementId: 'e-exam' },
];
const pair = { source: ENTS[0], followup: ENTS[1] };

const visitOf = (id, date, slots) => {
  const v = { id, customerId: 'c1', customerName: '客戶A', date, slots };
  return { ...v, status: visitStatusFrom(v) };
};
const exam = (id, date, status) => visitOf(id, date, [
  { entitlementId: 'e-exam', courseId: 'c-exam', courseName: '健檢', startsAt: '09:00', endsAt: '10:00', status },
]);
const second = (id, date, status, to) => visitOf(id, date, [
  { entitlementId: 'e-fu', courseId: 'c-fu', courseName: '二返', startsAt: '11:00', endsAt: '11:30', status, followupForVisitId: to },
]);
const task = (id, kind, visitId, done, o = {}) => ({
  id, kind, visitId, customerId: 'c1', done, doneAt: done ? '2026-09-25T02:00:00.000Z' : null, autoGenerated: true, ...o,
});
const chain = (visits, tasks = []) => syncFollowupTasks({
  customer: { id: 'c1', name: '客戶A' }, entitlements: ENTS, visits, tasks, coursesById,
});
const ask = (visit, customerVisits) => validateVisit(visit, {
  customer: { id: 'c1', flags: [] }, entitlements: ENTS, courses: COURSES, equipment: [],
  rooms: [], staff: [], ivProducts: [], customerVisits, sameDayVisits: [],
});
const aboutExam = (list) => list.filter((e) => e.includes('健檢'));

describe('「這是哪一次健檢的」那一排：排著的也按得下去', () => {
  const world = [
    exam('e1', '2026-09-01', 'done'),
    exam('e2', '2026-10-01', 'confirmed'),
    exam('e3', '2026-10-05', 'pending_confirm'),
    exam('e4', '2026-10-06', 'no_show'),
    exam('e5', '2026-10-07', 'cancelled'),
  ];

  test('待確認、已確認、已完成按得下去；取消、未到照舊按不下去', () => {
    const out = examChoicesFor(pair, world);
    assert.deepEqual(out.map((c) => c.status), ['done', 'confirmed', 'pending_confirm', 'no_show', 'cancelled']);
    assert.deepEqual(out.map((c) => c.pickable), [true, true, true, false, false]);
  });

  test('被別場活著的二返佔走的，排著的那一次也按不下去', () => {
    const out = examChoicesFor(pair, [...world, second('f', '2026-10-20', 'confirmed', 'e2')]);
    const e2 = out.find((c) => c.visitId === 'e2');
    assert.equal(e2.taken, true);
    assert.equal(e2.pickable, false);
  });

  test('佔著那一次的二返取消了：放回去', () => {
    const out = examChoicesFor(pair, [...world, second('f', '2026-10-20', 'cancelled', 'e2')]);
    assert.equal(out.find((c) => c.visitId === 'e2').pickable, true);
    assert.equal(claimedExams('e-fu', [...world, second('f', '2026-10-20', 'cancelled', 'e2')]).size, 0);
  });
});

describe('存檔驗證：接到排著的健檢存得下去，接到取消、未到的擋', () => {
  const world = [
    exam('e2', '2026-10-01', 'confirmed'),
    exam('e3', '2026-10-05', 'pending_confirm'),
    exam('e4', '2026-10-06', 'no_show'),
    exam('e5', '2026-10-07', 'cancelled'),
  ];
  const draft = (to) => ({ ...second(null, '2026-10-24', 'pending_confirm', to), id: undefined });

  test('已確認、待確認：沒有 error', () => {
    assert.deepEqual(aboutExam(ask(draft('e2'), world).errors), []);
    assert.deepEqual(aboutExam(ask(draft('e3'), world).errors), []);
  });

  test('未到、取消：擋下來，講出它是什麼狀態', () => {
    for (const to of ['e4', 'e5']) {
      const errors = aboutExam(ask(draft(to), world).errors);
      assert.equal(errors.length, 1, to);
      assert.match(errors[0], /不會有報告/);
    }
  });

  test('存著的那一份本來就指著它（健檢後來取消了）：改別的照樣存得下去（ADR-0011）', () => {
    const stored = second('f', '2026-10-24', 'confirmed', 'e5');
    const edited = { ...stored, slots: [{ ...stored.slots[0], note: '改了一句' }] };
    assert.deepEqual(aboutExam(ask(edited, [...world, stored]).errors), []);
  });

  test('二返自己改時間（舊的那一段取消、新的接在尾巴帶同一個連結）：不當成新接上的', () => {
    const stored = second('f', '2026-10-24', 'confirmed', 'e5');
    const rebooked = {
      ...stored,
      slots: [
        { ...stored.slots[0], status: 'cancelled' },
        { ...stored.slots[0], startsAt: '15:00', endsAt: '15:30', status: 'pending_confirm' },
      ],
    };
    assert.deepEqual(aboutExam(ask(rebooked, [...world, stored]).errors), []);
  });
});

describe('owed()：接在一次還沒做完的健檢上的二返，不算「約掉了一次」', () => {
  // A 做完、報告勾過、「約二返」開著；B 是健檢和二返當場一起約的（B 還沒做）
  const A = exam('A', '2026-09-01', 'done');
  const B = exam('B', '2026-10-01', 'confirmed');
  const fuB = second('F', '2026-10-24', 'pending_confirm', 'B');
  const tasks = [
    task('t-rep-A', REPORT_TASK_KIND, 'A', true),
    task('t-book-A', FOLLOWUP_TASK_KIND, 'A', false, { dueDate: '2026-10-02' }),
    task('t-send-A', SEND_REPORT_TASK_KIND, 'A', true),
  ];

  test('還欠的那一次照舊是 A 的', () => {
    assert.equal(owed(pair, [A, B, fuB]), 1);
  });

  test('約好 B 的二返那一刻，A 開著的「約二返」沒有被收掉', () => {
    const plan = chain([A, B, fuB], tasks);
    assert.deepEqual(plan.remove, []);
    assert.deepEqual(plan.create, []);
  });

  test('B 簽成做了：長 B 的追蹤健檢報告、不長 B 的約二返；A 的照舊留著', () => {
    const Bdone = exam('B', '2026-10-01', 'done');
    const plan = chain([A, Bdone, fuB], tasks);
    assert.deepEqual(plan.create.map((t) => `${t.kind}@${t.visitId}`), [`${REPORT_TASK_KIND}@B`]);
    assert.deepEqual(plan.remove, []);
  });

  test('B 的報告勾掉：只多「寄報告給醫師」，不長 B 的約二返', () => {
    const Bdone = exam('B', '2026-10-01', 'done');
    const plan = chain([A, Bdone, fuB], [...tasks, task('t-rep-B', REPORT_TASK_KIND, 'B', true)]);
    assert.deepEqual(plan.create.map((t) => `${t.kind}@${t.visitId}`), [`${SEND_REPORT_TASK_KIND}@B`]);
    assert.deepEqual(plan.remove, []);
  });

  test('B 取消了：那一場二返照樣不算約掉（A 的照舊）', () => {
    assert.equal(owed(pair, [A, exam('B', '2026-10-01', 'cancelled'), fuB]), 1);
  });

  test('連結指到的那一次不在手上這一份裡（刪掉的、或只給了部分來訪）：照舊算約掉 —— 不憑空多長一張', () => {
    assert.equal(owed(pair, [A, fuB]), 0);
  });

  test('沒連結的照舊算約掉（舊資料一個字都不動）', () => {
    assert.equal(owed(pair, [A, B, second('F', '2026-10-24', 'pending_confirm', null)]), 0);
  });
});
