// 健檢 ↔ 二返。GitHub issue #15。
//
// 這一支測的是那條動線的三段：額度成對、還欠幾次、待辦跟著健檢走。
// 缺任何一段，行事曆上那十筆二返就補不進 app —— 客戶身上沒有二返額度可扣。

import { test, describe } from 'node:test';
import assert from 'node:assert/strict';

import { syncTasksForVisit } from '../public/js/domain/taskRules.js';
import {
  FOLLOWUP_TASK_KIND,
  DEFAULT_FOLLOWUP_DUE_DAYS,
  followupCourseIdOf,
  isFollowupCourse,
  pairsOf,
  missingPairs,
  countMismatches,
  followupDraft,
  owed,
  syncFollowupTasks,
  describePair,
} from '../public/js/domain/followups.js';

// ---------- 共用的假資料 ----------

const CHECKUP_COURSE = {
  id: 'course-checkup',
  name: '健檢',
  category: 'B',
  durationMin: 120,
  followupCourseId: 'course-followup',
};

const FOLLOWUP_COURSE = {
  id: 'course-followup',
  name: '二返',
  category: 'A',
  durationMin: 30,
};

const RECOVERY_COURSE = { id: 'course-recovery', name: '復能', category: 'C', durationMin: 60 };

const COURSES = {
  'course-checkup': CHECKUP_COURSE,
  'course-followup': FOLLOWUP_COURSE,
  'course-recovery': RECOVERY_COURSE,
};

const checkup = (over = {}) => ({
  id: 'ent-checkup',
  type: 'single',
  label: '0.75萬健檢',
  courseId: 'course-checkup',
  totalQty: 3,
  doneCount: 0,
  bookedCount: 0,
  ...over,
});

const followup = (over = {}) => ({
  id: 'ent-followup',
  type: 'single',
  label: '二返（0.75萬健檢）',
  courseId: 'course-followup',
  totalQty: 3,
  followupForEntitlementId: 'ent-checkup',
  doneCount: 0,
  bookedCount: 0,
  ...over,
});

/** 一筆用掉某份額度的來訪。 */
const visit = (id, date, entitlementId, over = {}) => ({
  id,
  customerId: 'c1',
  customerName: '客戶甲',
  date,
  status: 'done',
  slots: [{ entitlementId, courseId: 'course-checkup' }],
  ...over,
});

const task = (over = {}) => ({
  id: 't1',
  visitId: 'v1',
  customerId: 'c1',
  customerName: '客戶甲',
  kind: FOLLOWUP_TASK_KIND,
  dueDate: '2026-08-08',
  done: false,
  autoGenerated: true,
  ...over,
});

const CUSTOMER = { id: 'c1', name: '客戶甲' };

const sync = (over = {}) =>
  syncFollowupTasks({
    customer: CUSTOMER,
    entitlements: [checkup(), followup()],
    visits: [],
    tasks: [],
    coursesById: COURSES,
    ...over,
  });

// ---------- 配對 ----------

describe('健檢與二返的配對', () => {
  test('配對記在課程主檔上，不是靠名字比對', () => {
    assert.equal(followupCourseIdOf(CHECKUP_COURSE), 'course-followup');
    assert.equal(followupCourseIdOf(RECOVERY_COURSE), null);
    assert.equal(followupCourseIdOf(undefined), null);
  });

  test('二返自己不會再配一個二返', () => {
    const courses = [CHECKUP_COURSE, FOLLOWUP_COURSE, RECOVERY_COURSE];
    assert.equal(isFollowupCourse('course-followup', courses), true);
    assert.equal(isFollowupCourse('course-checkup', courses), false);
  });

  test('配到的二返額度是用 followupForEntitlementId 指回去的', () => {
    const pairs = pairsOf([checkup(), followup()], COURSES);
    assert.equal(pairs.length, 1);
    assert.equal(pairs[0].source.id, 'ent-checkup');
    assert.equal(pairs[0].followup.id, 'ent-followup');
  });

  test('兩筆健檢各自配各自的，不會配錯', () => {
    const a = checkup({ id: 'ent-a', label: '0.75萬健檢', totalQty: 1 });
    const b = checkup({ id: 'ent-b', label: '5萬健檢(心臟)', totalQty: 2 });
    const fa = followup({ id: 'f-a', followupForEntitlementId: 'ent-a', totalQty: 1 });
    const fb = followup({ id: 'f-b', followupForEntitlementId: 'ent-b', totalQty: 2 });

    const pairs = pairsOf([a, b, fa, fb], COURSES);
    assert.equal(pairs.length, 2);
    assert.equal(pairs.find((p) => p.source.id === 'ent-a').followup.id, 'f-a');
    assert.equal(pairs.find((p) => p.source.id === 'ent-b').followup.id, 'f-b');
  });

  test('沒有配對的課程不會被拉進來', () => {
    const recovery = { id: 'ent-r', type: 'single', courseId: 'course-recovery', totalQty: 12 };
    assert.deepEqual(pairsOf([recovery], COURSES), []);
  });

  test('已刪除的額度不算', () => {
    assert.deepEqual(pairsOf([checkup({ deletedAt: '2026-08-01' })], COURSES), []);

    // 二返被刪掉了 → 這筆健檢重新變成「還沒配對」
    const pairs = pairsOf([checkup(), followup({ deletedAt: '2026-08-01' })], COURSES);
    assert.equal(pairs[0].followup, null);
  });
});

describe('還沒配對的健檢額度', () => {
  test('列得出來，而且附上要建的那一筆長什麼樣', () => {
    const missing = missingPairs([checkup()], COURSES);
    assert.equal(missing.length, 1);
    assert.equal(missing[0].source.id, 'ent-checkup');
    assert.equal(missing[0].draft.totalQty, 3);
    assert.equal(missing[0].draft.followupForEntitlementId, 'ent-checkup');
  });

  test('配過的就不再列', () => {
    assert.deepEqual(missingPairs([checkup(), followup()], COURSES), []);
  });
});

describe('要配出來的那一筆二返額度', () => {
  test('次數照抄健檢：買 N 次健檢就有 N 次二返', () => {
    const draft = followupDraft(checkup({ totalQty: 5 }), FOLLOWUP_COURSE);
    assert.equal(draft.totalQty, 5);
    assert.equal(draft.courseId, 'course-followup');
    assert.equal(draft.type, 'single');
  });

  test('名稱帶上健檢那一筆的名字，兩筆健檢時分得出來', () => {
    assert.equal(
      followupDraft(checkup({ label: '5萬健檢(心臟)' }), FOLLOWUP_COURSE).label,
      '二返（5萬健檢(心臟)）',
    );
  });

  test('購買日與到期日照抄，因為講的是同一次購買', () => {
    const draft = followupDraft(
      checkup({ purchasedAt: '2026-01-05', expiresAt: '2027-01-05', sourcePlanName: '筋骨強身' }),
      FOLLOWUP_COURSE,
    );
    assert.equal(draft.purchasedAt, '2026-01-05');
    assert.equal(draft.expiresAt, '2027-01-05');
    assert.equal(draft.sourcePlanName, '筋骨強身');
  });

  test('計數欄位從零開始，不繼承健檢的', () => {
    const draft = followupDraft(checkup({ doneCount: 2, bookedCount: 1 }), FOLLOWUP_COURSE);
    assert.equal(draft.doneCount, 0);
    assert.equal(draft.bookedCount, 0);
  });
});

describe('配對的次數對不上', () => {
  test('只回報，不修 —— 她可能是故意給的', () => {
    const rows = countMismatches([checkup({ totalQty: 3 }), followup({ totalQty: 2 })], COURSES);
    assert.equal(rows.length, 1);
    assert.equal(rows[0].expected, 3);
    assert.equal(rows[0].actual, 2);
  });

  test('對得上就不出現', () => {
    assert.deepEqual(countMismatches([checkup(), followup()], COURSES), []);
  });
});

// ---------- 還欠幾次 ----------

describe('還欠幾次二返', () => {
  const pair = { source: checkup(), followup: followup() };

  test('健檢還沒做，就還不欠 —— 沒做的健檢沒有報告可以聽', () => {
    assert.equal(owed(pair, []), 0);
  });

  test('做完一次健檢就欠一次', () => {
    assert.equal(owed(pair, [visit('v1', '2026-08-01', 'ent-checkup')]), 1);
  });

  test('買了 3 次只做了 1 次，欠的是 1 不是 3', () => {
    assert.equal(owed(pair, [visit('v1', '2026-08-01', 'ent-checkup')]), 1);
  });

  test('二返已經排進去（還沒上）就不算欠', () => {
    const visits = [
      visit('v1', '2026-08-01', 'ent-checkup'),
      visit('v2', '2026-08-10', 'ent-followup', { status: 'confirmed' }),
    ];
    assert.equal(owed(pair, visits), 0);
  });

  test('二返做完了也不算欠', () => {
    const visits = [
      visit('v1', '2026-08-01', 'ent-checkup'),
      visit('v2', '2026-08-10', 'ent-followup'),
    ];
    assert.equal(owed(pair, visits), 0);
  });

  test('二返被取消，那一次又欠回來 —— 時段還回去了', () => {
    const visits = [
      visit('v1', '2026-08-01', 'ent-checkup'),
      visit('v2', '2026-08-10', 'ent-followup', { status: 'cancelled' }),
    ];
    assert.equal(owed(pair, visits), 1);
  });

  test('健檢標成未到不算做完', () => {
    const visits = [visit('v1', '2026-08-01', 'ent-checkup', { status: 'no_show' })];
    assert.equal(owed(pair, visits), 0);
  });

  test('健檢做超過買的次數時，二返不會跟著無限長', () => {
    const visits = [
      visit('v1', '2026-08-01', 'ent-checkup'),
      visit('v2', '2026-08-05', 'ent-checkup'),
      visit('v3', '2026-08-09', 'ent-checkup'),
      visit('v4', '2026-08-12', 'ent-checkup'),
    ];
    // 買 3 次，做了 4 次 → 上限仍然是 3。超用由資料健檢另外列。
    assert.equal(owed({ source: checkup(), followup: followup() }, visits), 3);
  });

  test('還沒配對就不算欠 —— 沒有額度可扣，長出待辦也沒有用', () => {
    assert.equal(owed({ source: checkup(), followup: null }, [
      visit('v1', '2026-08-01', 'ent-checkup'),
    ]), 0);
  });

  test('已刪除的來訪不算', () => {
    const visits = [visit('v1', '2026-08-01', 'ent-checkup', { deletedAt: '2026-08-02' })];
    assert.equal(owed(pair, visits), 0);
  });
});

// ---------- 待辦 ----------

describe('「約二返」的待辦', () => {
  test('健檢還沒完成就不產生', () => {
    const visits = [visit('v1', '2026-09-01', 'ent-checkup', { status: 'confirmed' })];
    assert.deepEqual(sync({ visits }).create, []);
  });

  test('健檢標成已完成之後長出一張，掛在那一筆健檢上', () => {
    const { create } = sync({ visits: [visit('v1', '2026-08-01', 'ent-checkup')] });
    assert.equal(create.length, 1);
    assert.equal(create[0].kind, FOLLOWUP_TASK_KIND);
    assert.equal(create[0].visitId, 'v1');
    assert.equal(create[0].customerId, 'c1');
    assert.equal(create[0].autoGenerated, true);
  });

  test('死線是健檢日往後算，不是來訪日的前一天', () => {
    const { create } = sync({ visits: [visit('v1', '2026-08-01', 'ent-checkup')] });
    assert.equal(create[0].dueDate, '2026-08-08'); // 8/1 + 7
    assert.equal(DEFAULT_FOLLOWUP_DUE_DAYS, 7);
  });

  test('間隔可以調', () => {
    const { create } = sync({
      visits: [visit('v1', '2026-08-01', 'ent-checkup')],
      dueDays: 30,
    });
    assert.equal(create[0].dueDate, '2026-08-31');
  });

  test('已經有一張了就不再產生', () => {
    const { create, remove } = sync({
      visits: [visit('v1', '2026-08-01', 'ent-checkup')],
      tasks: [task({ visitId: 'v1' })],
    });
    assert.deepEqual(create, []);
    assert.deepEqual(remove, []);
  });

  test('客戶改名時死線與姓名跟著更新，不重建一張', () => {
    const { create, update } = syncFollowupTasks({
      customer: { id: 'c1', name: '客戶甲改名了' },
      entitlements: [checkup(), followup()],
      visits: [visit('v1', '2026-08-01', 'ent-checkup')],
      tasks: [task({ visitId: 'v1', customerName: '客戶甲' })],
      coursesById: COURSES,
    });
    assert.deepEqual(create, []);
    assert.deepEqual(update, [{ id: 't1', changes: { customerName: '客戶甲改名了' } }]);
  });

  test('沒有配對二返額度時不產生 —— 那張待辦點下去無事可做', () => {
    const { create } = sync({
      entitlements: [checkup()],
      visits: [visit('v1', '2026-08-01', 'ent-checkup')],
    });
    assert.deepEqual(create, []);
  });

  test('二返約好之後，還沒做的待辦收掉', () => {
    const visits = [
      visit('v1', '2026-08-01', 'ent-checkup'),
      visit('v2', '2026-08-10', 'ent-followup', { status: 'confirmed' }),
    ];
    const { remove } = sync({ visits, tasks: [task({ visitId: 'v1' })] });
    assert.deepEqual(remove, [{ id: 't1', reason: '二返已經約好了' }]);
  });

  test('健檢被取消時，還沒做的待辦跟著收掉', () => {
    const visits = [visit('v1', '2026-08-01', 'ent-checkup', { status: 'cancelled' })];
    const { remove } = sync({ visits, tasks: [task({ visitId: 'v1' })] });
    assert.deepEqual(remove, [{ id: 't1', reason: '那一筆健檢不是已完成了' }]);
  });

  test('健檢改成未到時，還沒做的待辦跟著收掉', () => {
    const visits = [visit('v1', '2026-08-01', 'ent-checkup', { status: 'no_show' })];
    const { remove } = sync({ visits, tasks: [task({ visitId: 'v1' })] });
    assert.equal(remove.length, 1);
  });

  test('健檢被刪掉時，還沒做的待辦跟著收掉', () => {
    const visits = [visit('v1', '2026-08-01', 'ent-checkup', { deletedAt: '2026-08-02' })];
    const { remove } = sync({ visits, tasks: [task({ visitId: 'v1' })] });
    assert.equal(remove.length, 1);
  });

  test('已經勾完成的待辦一律不刪 —— 那件事真的做過了', () => {
    const visits = [visit('v1', '2026-08-01', 'ent-checkup', { status: 'cancelled' })];
    const { remove } = sync({ visits, tasks: [task({ visitId: 'v1', done: true })] });
    assert.deepEqual(remove, []);
  });

  test('手動加的同名待辦不歸它管', () => {
    const visits = [visit('v1', '2026-08-01', 'ent-checkup', { status: 'cancelled' })];
    const { remove } = sync({
      visits,
      tasks: [task({ visitId: 'v1', autoGenerated: false })],
    });
    assert.deepEqual(remove, []);
  });

  test('做了兩次健檢就有兩張，一次約掉一張只收一張', () => {
    const twice = [
      visit('v1', '2026-08-01', 'ent-checkup'),
      visit('v2', '2026-08-15', 'ent-checkup'),
    ];
    assert.equal(sync({ visits: twice }).create.length, 2);

    // 約掉一次二返 → 只該剩一張，而且留下的是比較早那一筆
    // （二返照順序約，先做的先約）
    const withOne = [...twice, visit('v3', '2026-08-20', 'ent-followup', { status: 'confirmed' })];
    const { create, remove } = sync({
      visits: withOne,
      tasks: [task({ id: 'ta', visitId: 'v1' }), task({ id: 'tb', visitId: 'v2' })],
    });
    assert.deepEqual(create, []);
    assert.equal(remove.length, 1);
  });

  test('全部約完之後兩張都收掉', () => {
    const visits = [
      visit('v1', '2026-08-01', 'ent-checkup'),
      visit('v2', '2026-08-15', 'ent-checkup'),
      visit('v3', '2026-08-20', 'ent-followup', { status: 'confirmed' }),
      visit('v4', '2026-08-25', 'ent-followup', { status: 'confirmed' }),
    ];
    const { remove } = sync({
      visits,
      tasks: [task({ id: 'ta', visitId: 'v1' }), task({ id: 'tb', visitId: 'v2' })],
    });
    assert.equal(remove.length, 2);
  });

  test('兩筆健檢額度各自算各自的', () => {
    const a = checkup({ id: 'ent-a', label: '0.75萬健檢', totalQty: 1 });
    const b = checkup({ id: 'ent-b', label: '5萬健檢(心臟)', totalQty: 1 });
    const fa = followup({ id: 'f-a', followupForEntitlementId: 'ent-a', totalQty: 1 });
    const fb = followup({ id: 'f-b', followupForEntitlementId: 'ent-b', totalQty: 1 });

    const visits = [
      visit('v1', '2026-08-01', 'ent-a'),
      visit('v2', '2026-08-15', 'ent-b'),
      // 只約掉 a 那一份的二返
      visit('v3', '2026-08-20', 'f-a', { status: 'confirmed' }),
    ];

    const { create } = sync({ entitlements: [a, b, fa, fb], visits });
    assert.equal(create.length, 1);
    assert.equal(create[0].visitId, 'v2');
  });
});

// ---------- 給畫面的那一句話 ----------

describe('客戶詳情頁那一句', () => {
  test('欠的時候講欠幾次', () => {
    const pair = { source: checkup(), followup: followup() };
    const line = describePair(pair, [visit('v1', '2026-08-01', 'ent-checkup')]);
    assert.equal(line.owed, 1);
    assert.match(line.text, /還欠 1 次/);
  });

  test('不欠的時候講已經約掉幾次', () => {
    const pair = { source: checkup(), followup: followup() };
    const line = describePair(pair, [
      visit('v1', '2026-08-01', 'ent-checkup'),
      visit('v2', '2026-08-10', 'ent-followup'),
    ]);
    assert.equal(line.owed, 0);
    assert.match(line.text, /約掉 1 次/);
  });

  test('沒配對就沒有這一句', () => {
    assert.equal(describePair({ source: checkup(), followup: null }, []), null);
  });
});

// ---------- 跟掛號類任務的分工 ----------

describe('「約二返」不歸 syncTasksForVisit 管', () => {
  test('健檢那一筆存檔時不會把「約二返」當成多餘的任務刪掉', () => {
    // 這是最容易漏掉的一種：syncTasksForVisit() 看到一張它認不得的自動任務，
    // 會判定「來訪裡已經沒有需要這個任務的課程」而收掉它 —— 而收掉的時機
    // 正好是健檢那一筆存檔的當下，也就是它剛長出來的那一刻。
    const checkupVisit = {
      id: 'v1',
      customerId: 'c1',
      customerName: '客戶甲',
      date: '2026-08-01',
      status: 'done',
      slots: [{ courseId: 'course-checkup', entitlementId: 'ent-checkup' }],
    };

    const { remove } = syncTasksForVisit(
      checkupVisit,
      [task({ visitId: 'v1' })],
      { coursesById: COURSES, today: '2026-08-02' },
    );

    assert.deepEqual(remove, []);
  });

  test('健檢照樣產生它自己的 B 類任務', () => {
    // 狀態是 confirmed 而不是 pending_confirm：登記任務要等客人確認才長出來
    // （ADR-0027）。這一條測的是「健檢走 B 類」，不是「什麼時候長」。
    const { create } = syncTasksForVisit(
      {
        id: 'v1', customerId: 'c1', customerName: '客戶甲', date: '2026-08-01',
        status: 'confirmed', slots: [{ courseId: 'course-checkup' }],
      },
      [],
      { coursesById: COURSES, today: '2026-07-01' },
    );
    assert.deepEqual(create.map((t) => t.kind).sort(), ['Examine', '打電話']);
  });

  test('約好的二返走一般動線：A 類的四個任務照樣產生', () => {
    const { create } = syncTasksForVisit(
      {
        id: 'v9', customerId: 'c1', customerName: '客戶甲', date: '2026-08-20',
        status: 'confirmed',
        slots: [{ courseId: 'course-followup', entitlementId: 'ent-followup' }],
      },
      [],
      { coursesById: COURSES, today: '2026-08-10' },
    );
    assert.deepEqual(
      create.map((t) => t.kind).sort(),
      ['Abovee', 'Examine', '打電話', '耀聖'].sort(),
    );
    assert.equal(create[0].dueDate, '2026-08-19', '一般任務的死線仍然是來訪日前一天');
  });
});
