// 跟標題講同一件事的 `?` 不畫（ADR-0114，`.scratch/asks-2026-09-24-evening/issues/01`）。
//
// 她 2026-09-24 晚：
//
// > 有一些tooltip是完全不必要的，不要卡在標簽之間很奇怪，而且有些根本其實不用那些說明
// > a追蹤健檢報告那邊的待辦，不需要提醒"健檢做完了，去問報告出來沒" 這是多餘的話
// > b簽療程單那邊寫的"有幾段到現在還是.....沒來就打叉"看不懂且沒必要，是多餘的
// > c改時間/取消"2026-09-08的來訪取消了....放掉"不需要，是多餘的
// > 1清單 B 全部拿掉可以，但是C先不用
//
// 那幾支 view 進不了 node（一路 import 到 firebase 的 CDN），所以這裡掃原始碼；
// 瀏覽器那一側由 E2E `29-slot-first` 的 S2c／S2d 問同樣的問題。

import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const read = (rel) => readFileSync(new URL(`../public/js/${rel}`, import.meta.url), 'utf8');

/** 某一支函式的身體：從宣告到下一個頂層宣告。 */
function body(src, start) {
  const at = src.indexOf(start);
  assert.ok(at >= 0, `找不到 ${start}`);
  const next = src.slice(at + start.length).search(/\n(export )?(async )?function |\nconst [A-Z_]+ = /);
  return next < 0 ? src.slice(at) : src.slice(at, at + start.length + next);
}

describe('A 她點名的', () => {
  test('系統自己寫在任務上的那一句兩個畫面都不畫，她自己寫的照舊印', () => {
    for (const [f, t] of [['ui/views/home.js', 't'], ['ui/components/tasklist.js', 'task']]) {
      const src = read(f);
      assert.ok(!src.includes(`tip(${t}.note`), `${f}：系統那一句不再收進 ?，整句不畫`);
      assert.ok(src.includes(`${t}.note && !${t}.autoGenerated`), `${f}：她手寫的那一句要照舊印`);
    }
  });

  test('簽療程單那張卡不再有「有幾段到現在還是…」', () => {
    const row = body(read('ui/views/home.js'), 'function closeRow(');
    assert.ok(!row.includes('tip('), 'closeRow() 裡一顆 ? 都不要');
    assert.ok(!row.includes('沒來就打叉'));
  });
});

describe('B 跟標題講同一件事的', () => {
  const home = read('ui/views/home.js');

  test('逾期／今天／明天／改時間取消／確認／簽療程單的頁標題沒有說明', () => {
    const groups = body(home, 'const GROUPS = {');
    for (const s of ['死線已經過去了', '死線是今天', '可以提早做', '要回去把已經做掉的登記收回來',
      '問完回來按打勾', '次數是這時候才扣的']) {
      assert.ok(!groups.includes(s), `GROUPS 還留著「${s}」`);
    }
    assert.ok(!home.includes("tip('問完回來按打勾。')"), '跟客人確認時間那一頁的標題');
    assert.ok(!home.includes('沒來就打叉 —— 次數是這時候才扣的'), '簽療程單那一頁的標題');
  });

  test('任務種類那一頁：只有 Examine 與耀聖留著（那是另一個系統上的步驟）', () => {
    const notes = body(home, 'const KIND_NOTES = {');
    assert.ok(notes.includes('預約作業 → 查核 → 已報到'), 'Examine 那一句要留著');
    assert.ok(notes.includes('右下角 → 未報到 → V'), '耀聖那一句要留著');
    for (const s of ['健檢做完了', '報告拿到了', '客人走了', '來訪前一天提醒', '壓表登記']) {
      assert.ok(!notes.includes(s), `KIND_NOTES 還留著「${s}」`);
    }
  });

  test('依客戶抽屜那兩列、確認抽屜、客戶詳情、壓表那幾顆', () => {
    assert.ok(!home.includes('客人可能只答應其中幾天'), '依客戶抽屜：跟客人確認時間那一列');
    assert.ok(!home.includes('次數是收尾時才扣的'), '依客戶抽屜：簽療程單那一列');
    assert.ok(!home.includes('確認之後會自動排進日曆'), '確認抽屜（而且那一句是錯的）');
    assert.ok(!read('ui/views/customerDetail.js').includes('勾掉待辦上那一張「跟客人確認時間」之後'),
      '客戶詳情「還沒有任務。」旁邊那一顆');
    assert.ok(!read('ui/views/schedule.js').includes('會出現在待辦的「跟客人確認時間」。`)'),
      '壓表那張卡上那一顆');
  });
});
