// 任務跟著來訪走。SPEC 第 4.1、5.5 節。
//
// 這一支測的是「來訪變了，任務要怎麼跟著變」——這正是現在白紙做不到的事：
// 東西改了，該做的事沒人記得。

import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

import {
  syncTasksForVisit,
  acceptsNewTasks,
  isCancelKind,
  cancelKindFor,
} from '../public/js/domain/taskRules.js';
import { confirmMessage } from '../public/js/domain/messages.js';
import { shortDate, weekdayLabel } from '../public/js/domain/dates.js';

const COURSES = {
  rehab: { category: 'A' },   // 復健科：Abovee 壓表，確認後 Examine、耀聖
  checkup: { category: 'B' }, // 健檢：Examine 壓表，確認後沒有後續登記
  recovery: { category: 'C' },// 復能：Abovee 壓表，確認後沒有後續登記
};

const visit = (over = {}) => ({
  id: 'v1',
  customerId: 'c1',
  customerName: '客戶甲',
  date: '2026-09-10',
  status: 'pending_confirm',
  slots: [{ courseId: 'recovery' }],
  ...over,
});

const ctx = { coursesById: COURSES, today: '2026-09-01' };

const task = (over = {}) => ({
  id: 't1',
  visitId: 'v1',
  customerId: 'c1',
  customerName: '客戶甲',
  kind: 'Examine',
  dueDate: '2026-09-09',
  done: false,
  autoGenerated: true,
  ...over,
});

describe('來訪存檔時的任務同步', () => {
  test('客人確認之後產生它該有的任務', () => {
    const { create, update, remove } = syncTasksForVisit(
      visit({ status: 'confirmed', slots: [{ courseId: 'rehab' }] }), [], ctx,
    );

    assert.deepEqual(create.map((t) => t.kind).sort(), ['Examine', '耀聖']);
    assert.ok(create.every((t) => t.dueDate === '2026-09-09'));
    assert.ok(create.every((t) => t.autoGenerated));
    assert.equal(update.length, 0);
    assert.equal(remove.length, 0);
  });

  test('已經有的任務不會再產生一次', () => {
    const confirmed = visit({ status: 'confirmed', slots: [{ courseId: 'rehab' }] });
    const { create } = syncTasksForVisit(confirmed, [task(), task({ id: 't2', kind: '耀聖' })], ctx);
    assert.equal(create.length, 0);
  });

  test('改了來訪日期，死線跟著移，已完成的仍然是已完成', () => {
    const done = task({ done: true, doneAt: '2026-09-02T00:00:00Z' });
    const moved = visit({ date: '2026-09-20', slots: [{ courseId: 'rehab' }] });
    const { update, remove } = syncTasksForVisit(moved, [done], ctx);

    assert.deepEqual(update, [{ id: 't1', changes: { dueDate: '2026-09-19' } }]);
    assert.equal(remove.length, 0);
  });

  test('課程被移出來訪：沒做的移除，做過的留著', () => {
    const undone = task({ id: 'a', kind: 'Examine' });
    const finished = task({ id: 'b', kind: '耀聖', done: true });

    // 來訪只剩復能（C 類），確認後沒有任何登記 —— 兩張都不再需要
    const { remove, create } = syncTasksForVisit(visit(), [undone, finished], ctx);

    assert.deepEqual(remove.map((r) => r.id), ['a']);
    assert.equal(create.length, 0);
  });
});

// 她的順序是「壓表 → 問客人 → 客人說可以 → 才去登記」。壓完表就長出來的話，
// 一晚上二十幾位等於立刻多出幾十件還不確定要不要做的待辦。ADR-0027。
describe('登記任務等客人確認之後才長出來（ADR-0027）', () => {
  test('壓完表記下去，一件登記都不產生', () => {
    const { create, update, remove } = syncTasksForVisit(
      visit({ slots: [{ courseId: 'rehab' }] }), [], ctx,
    );

    assert.deepEqual([create, update, remove], [[], [], []]);
  });

  test('確認之後才長出來，死線仍然是來訪日的前一天', () => {
    const asked = visit({ slots: [{ courseId: 'rehab' }] });
    assert.equal(syncTasksForVisit(asked, [], ctx).create.length, 0);

    const { create } = syncTasksForVisit({ ...asked, status: 'confirmed' }, [], ctx);
    assert.deepEqual(create.map((t) => t.kind).sort(), ['Examine', '耀聖']);
    assert.ok(create.every((t) => t.dueDate === '2026-09-09'));
  });

  test('補記一筆已經上完的課，不會長出一串死線早就過的登記', () => {
    // pending_confirm → done，中間沒有經過 confirmed。那天已經過完了，
    // 掛號沒有東西要補 —— 產生出來只會是四筆一出生就逾期的紅字。
    const { create, remove } = syncTasksForVisit(
      visit({ status: 'done', slots: [{ courseId: 'rehab' }] }),
      [],
      { ...ctx, today: '2026-09-30' },
    );

    assert.deepEqual([create, remove], [[], []]);
  });

  test('來訪結案不會把她還沒做完的登記洗掉', () => {
    // 反過來的方向：confirmed 時長出來的任務，走到 done 一個都不能少。
    // 「還沒做完」本身就是要看得見的事。
    const undone = task({ kind: 'Examine' });
    const { create, remove } = syncTasksForVisit(
      visit({ status: 'done', slots: [{ courseId: 'rehab' }] }), [undone], ctx,
    );

    assert.deepEqual([create, remove], [[], []]);
  });

  test('未到也一樣不產生新的登記', () => {
    const { create } = syncTasksForVisit(
      visit({ status: 'no_show', slots: [{ courseId: 'rehab' }] }), [], ctx,
    );
    assert.equal(create.length, 0);
  });

  test('擋掉的只有「無中生有」—— 還沒確認的來訪照樣收得掉多餘的任務', () => {
    // 來訪只剩復能（C 類 → Abovee），Examine 不再需要。
    // 這一條顧的是「不產生」不可以順手變成「什麼都不做」。
    const stale = task({ id: 'a', kind: 'Examine' });
    const { remove } = syncTasksForVisit(visit(), [stale], ctx);

    assert.deepEqual(remove.map((r) => r.id), ['a']);
  });

  test('acceptsNewTasks() 只認得 confirmed', () => {
    assert.equal(acceptsNewTasks('confirmed'), true);
    for (const s of ['pending_confirm', 'done', 'no_show', 'cancelled', undefined]) {
      assert.equal(acceptsNewTasks(s), false, `${s} 不該產生新任務`);
    }
  });

  // `data/legacyImport.js` 的 importPlan() 就是拿這一支去問的（一筆來訪、
  // 沒有現有任務）。那一層在 node 裡跑不起來（firebase SDK 是 CDN import），
  // 所以在這個接縫上把行為釘住：匯入不是特例，它走的是同一條規則。
  // 見 .scratch/first-real-import/issues/04。
  test('匯進來的未來預約會長出登記待辦，已經發生的一筆都不長', () => {
    const imported = (over) => visit({
      slots: [{ courseId: 'rehab' }],
      importedFrom: { source: 'merge-file' },
      ...over,
    });

    const past = syncTasksForVisit(imported({ status: 'done' }), [], ctx);
    assert.deepEqual([past.create, past.update, past.remove], [[], [], []],
      '那些掛號在舊系統早就做完了');

    const ahead = syncTasksForVisit(imported({ status: 'confirmed' }), [], ctx);
    assert.deepEqual(ahead.create.map((t) => t.kind).sort(), ['Examine', '耀聖']);
    assert.ok(ahead.create.every((t) => t.autoGenerated));
  });
});

describe('取消來訪時的任務', () => {
  const cancelled = visit({ status: 'cancelled' });

  // 來訪存在就代表她已經在 Abovee（健檢是 Examine）上把時段佔住了 ——
  // app 裡的來訪從「已壓表」開始，所以不需要任何任務來證明她壓過。
  test('壓表登記本身一律要收回來', () => {
    const { create, remove } = syncTasksForVisit(cancelled, [], ctx);

    assert.deepEqual(create.map((t) => t.kind), ['取消 Abovee']);
    assert.ok(create[0].note.includes('放掉'));
    assert.ok(create[0].note.includes('2026-09-10'));
    assert.deepEqual(remove, []);
  });

  test('健檢是壓在 Examine 上的，所以要收回來的是那一個', () => {
    const { create } = syncTasksForVisit(
      visit({ status: 'cancelled', slots: [{ courseId: 'checkup' }] }), [], ctx,
    );
    assert.deepEqual(create.map((t) => t.kind), ['取消 Examine']);
  });

  test('同一天兩種課程 —— 兩個系統上真的各有一筆', () => {
    const { create } = syncTasksForVisit(
      visit({ status: 'cancelled', slots: [{ courseId: 'recovery' }, { courseId: 'checkup' }] }),
      [], ctx,
    );
    assert.deepEqual(create.map((t) => t.kind).sort(), ['取消 Abovee', '取消 Examine']);
  });

  test('還沒做的任務直接收掉 —— 那件事不用做了', () => {
    const { remove } = syncTasksForVisit(cancelled, [task()], ctx);
    assert.deepEqual(remove, [{ id: 't1', reason: '來訪已取消' }]);
  });

  test('已經登記過的要產生「回去取消」的任務（SPEC 4.1）', () => {
    const registered = [
      task({ id: 'a', kind: 'Abovee', done: true }),
      task({ id: 'b', kind: 'Examine', done: true }),
      task({ id: 'c', kind: '耀聖', done: true }),
    ];
    const { create, remove } = syncTasksForVisit(cancelled, registered, ctx);

    assert.deepEqual(create.map((t) => t.kind), ['取消 Abovee', '取消 Examine', '取消 耀聖']);
    assert.ok(create.every((t) => isCancelKind(t.kind)));
    assert.ok(create.every((t) => t.note.includes('2026-09-10')));
    assert.equal(remove.length, 0, '已完成的不刪，那件事真的做過');
  });

  test('壓表登記與已勾掉的同名任務不會各長一張', () => {
    // 復能壓在 Abovee，而歷史資料裡也有一張勾掉的 Abovee 任務 —— 那是同一件事
    const { create } = syncTasksForVisit(
      cancelled, [task({ id: 'a', kind: 'Abovee', done: true })], ctx,
    );
    assert.deepEqual(create.map((t) => t.kind), ['取消 Abovee']);
  });

  test('打電話做過了就是做過了，沒有東西要收回來', () => {
    const { create } = syncTasksForVisit(cancelled, [task({ kind: '打電話', done: true })], ctx);
    assert.ok(!create.some((t) => t.kind === '取消 打電話'));
  });

  test('取消登記沒有寬限期：今天比死線早就用今天', () => {
    const { create } = syncTasksForVisit(cancelled, [], ctx);
    assert.equal(create[0].dueDate, '2026-09-01');

    const late = syncTasksForVisit(cancelled, [], { ...ctx, today: '2026-09-30' });
    assert.equal(late.create[0].dueDate, '2026-09-09', '死線已經過了就照死線，逾期看得出來');
  });

  test('取消類的任務不會被之後的同步再動到，也不會長出第二張', () => {
    const existing = [task({ id: 'x', kind: cancelKindFor('Abovee') })];
    const { create, update, remove } = syncTasksForVisit(cancelled, existing, ctx);
    assert.deepEqual([create, update, remove], [[], [], []]);
  });

  test('已經勾掉的取消任務也不會再長一張', () => {
    const existing = [task({ id: 'x', kind: cancelKindFor('Abovee'), done: true })];
    assert.deepEqual(syncTasksForVisit(cancelled, existing, ctx).create, []);
  });

  test('軟刪除的來訪與取消一樣處理', () => {
    const { remove } = syncTasksForVisit(visit({ deletedAt: 'x' }), [task()], ctx);
    assert.equal(remove.length, 1);
  });
});

describe('LINE 確認訊息', () => {
  test('把壓好的時間列成一句可以直接貼的話', () => {
    const msg = confirmMessage({ name: '王小姐' }, [
      { date: '2026-09-17', slots: [{ startsAt: '14:00' }] },
      { date: '2026-09-03', slots: [{ startsAt: '14:00' }, { startsAt: '15:15' }] },
    ]);

    assert.equal(msg, '王小姐您好，9 月為您安排了 9/3(四) 14:00、9/17(四) 14:00，請問可以嗎？');
  });

  test('一次來訪只講第一個時段的時間，不把整份時刻表念完', () => {
    const msg = confirmMessage({ name: '王小姐' }, [
      { date: '2026-09-03', slots: [{ startsAt: '15:15' }, { startsAt: '09:15' }] },
    ]);
    assert.ok(msg.includes('09:15'));
    assert.ok(!msg.includes('15:15'));
  });

  test('沒有東西可問就回空字串，不要產生半句話', () => {
    assert.equal(confirmMessage({ name: '王小姐' }, []), '');
  });
});

describe('日期的人話格式', () => {
  test('星期算得對', () => {
    assert.equal(weekdayLabel('2026-09-03'), '四');
    assert.equal(weekdayLabel('2026-09-06'), '日');
  });

  test('M/D(週)', () => {
    assert.equal(shortDate('2026-09-03'), '9/3(四)');
    assert.equal(shortDate('2026-12-25'), '12/25(五)');
  });
});

// ---------- 勾掉一張待辦要把健檢鏈一起帶著走 ----------
//
// 這一支不執行程式碼，只讀原始碼 —— 跟 `module-names.test.js` 同一個路數。
// `data/*.js` 從 gstatic 載入 Firebase SDK，node 載不進來，而這裡要守的是
// 一個「不執行就看不出來、執行了要有真的 Firestore 才看得出來」的接線：
//
//   勾掉「追蹤健檢報告」→ 同一個 commit 裡把「約二返」長出來
//
// 2026-08-25 以前這條線根本不存在（`syncFollowupTasks()` 三個呼叫端全在
// `save()` / `remove()` / `restore()` 底下），而且**947 個測試全綠** ——
// 規則本身測得很完整，只是沒有人在勾掉的那一刻叫它。
// 見 `.scratch/asks-2026-08-25/issues/09`。
describe('勾完成那一支的接線', () => {
  const src = readFileSync(
    new URL('../public/js/data/tasks.js', import.meta.url), 'utf8',
  );
  const setDone = src.slice(src.indexOf('export async function setDone'));

  test('setDone 把健檢鏈的操作放進同一個 commit', () => {
    assert.match(setDone, /followupOpsAfterTaskChange/,
      '勾掉「追蹤健檢報告」要連著把「約二返」長出來');
    assert.match(setDone, /repo\.commit\(\[[\s\S]*followupOpsAfterTaskChange/,
      '兩件事要在同一個 commit 裡，不然復原只退得回其中一半');
  });

  test('setDone 收的是任務本身，不是 id', () => {
    // 收 id 的話這一層得先把那幾筆讀回來才知道是不是鏈上的那兩種，
    // 而呼叫端手上本來就有 —— 那是白白多一輪往返。
    assert.match(setDone, /setDone\(tasks, done\)/);
  });
});
