// 任務跟著來訪走。SPEC 第 4.1、5.5 節。
//
// 這一支測的是「來訪變了，任務要怎麼跟著變」——這正是現在白紙做不到的事：
// 東西改了，該做的事沒人記得。

import { test, describe } from 'node:test';
import assert from 'node:assert/strict';

import {
  syncTasksForVisit,
  isCancelKind,
  cancelKindFor,
} from '../public/js/domain/taskRules.js';
import { confirmMessage } from '../public/js/domain/messages.js';
import { shortDate, weekdayLabel } from '../public/js/domain/dates.js';

const COURSES = {
  rehab: { category: 'A' },   // 復健科：打電話、Abovee、Examine、耀聖
  checkup: { category: 'B' }, // 健檢：打電話、Examine
  recovery: { category: 'C' },// 復能：Abovee
};

const visit = (over = {}) => ({
  id: 'v1',
  customerId: 'c1',
  customerName: '客戶甲',
  date: '2026-09-10',
  status: 'pending_confirm',
  slots: [{ courseId: 'recovery' }],
  ...over,
});

const ctx = { coursesById: COURSES, today: '2026-09-01' };

const task = (over = {}) => ({
  id: 't1',
  visitId: 'v1',
  customerId: 'c1',
  customerName: '客戶甲',
  kind: 'Abovee',
  dueDate: '2026-09-09',
  done: false,
  autoGenerated: true,
  ...over,
});

describe('來訪存檔時的任務同步', () => {
  test('新的來訪產生它該有的任務', () => {
    const { create, update, remove } = syncTasksForVisit(visit({ slots: [{ courseId: 'rehab' }] }), [], ctx);

    assert.deepEqual(create.map((t) => t.kind).sort(), ['Abovee', 'Examine', '打電話', '耀聖'].sort());
    assert.ok(create.every((t) => t.dueDate === '2026-09-09'));
    assert.ok(create.every((t) => t.autoGenerated));
    assert.equal(update.length, 0);
    assert.equal(remove.length, 0);
  });

  test('已經有的任務不會再產生一次', () => {
    const { create } = syncTasksForVisit(visit(), [task()], ctx);
    assert.equal(create.length, 0);
  });

  test('改了來訪日期，死線跟著移，已完成的仍然是已完成', () => {
    const done = task({ done: true, doneAt: '2026-09-02T00:00:00Z' });
    const { update, remove } = syncTasksForVisit(visit({ date: '2026-09-20' }), [done], ctx);

    assert.deepEqual(update, [{ id: 't1', changes: { dueDate: '2026-09-19' } }]);
    assert.equal(remove.length, 0);
  });

  test('課程被移出來訪：沒做的移除，做過的留著', () => {
    const undone = task({ id: 'a', kind: 'Examine' });
    const finished = task({ id: 'b', kind: '打電話', done: true });

    // 來訪只剩復能（C 類），Examine 與打電話都不再需要
    const { remove, create } = syncTasksForVisit(visit(), [undone, finished, task()], ctx);

    assert.deepEqual(remove.map((r) => r.id), ['a']);
    assert.equal(create.length, 0);
  });
});

describe('取消來訪時的任務', () => {
  const cancelled = visit({ status: 'cancelled' });

  test('還沒做的任務直接收掉 —— 那件事不用做了', () => {
    const { remove, create } = syncTasksForVisit(cancelled, [task()], ctx);
    assert.deepEqual(remove, [{ id: 't1', reason: '來訪已取消' }]);
    assert.equal(create.length, 0);
  });

  test('已經登記過的要產生「回去取消」的任務（SPEC 4.1）', () => {
    const registered = [
      task({ id: 'a', kind: 'Abovee', done: true }),
      task({ id: 'b', kind: 'Examine', done: true }),
      task({ id: 'c', kind: '耀聖', done: true }),
    ];
    const { create, remove } = syncTasksForVisit(cancelled, registered, ctx);

    assert.deepEqual(create.map((t) => t.kind), ['取消 Abovee', '取消 Examine', '取消 耀聖']);
    assert.ok(create.every((t) => isCancelKind(t.kind)));
    assert.ok(create.every((t) => t.note.includes('2026-09-10')));
    assert.equal(remove.length, 0, '已完成的不刪，那件事真的做過');
  });

  test('打電話做過了就是做過了，沒有東西要收回來', () => {
    const { create } = syncTasksForVisit(cancelled, [task({ kind: '打電話', done: true })], ctx);
    assert.equal(create.length, 0);
  });

  test('取消登記沒有寬限期：今天比死線早就用今天', () => {
    const { create } = syncTasksForVisit(cancelled, [task({ done: true })], ctx);
    assert.equal(create[0].dueDate, '2026-09-01');

    const late = syncTasksForVisit(cancelled, [task({ done: true })], {
      ...ctx,
      today: '2026-09-30',
    });
    assert.equal(late.create[0].dueDate, '2026-09-09', '死線已經過了就照死線，逾期看得出來');
  });

  test('取消類的任務不會被之後的同步再動到', () => {
    const existing = [task({ id: 'x', kind: cancelKindFor('Abovee') })];
    const { create, update, remove } = syncTasksForVisit(cancelled, existing, ctx);
    assert.deepEqual([create, update, remove], [[], [], []]);
  });

  test('軟刪除的來訪與取消一樣處理', () => {
    const { remove } = syncTasksForVisit(visit({ deletedAt: 'x' }), [task()], ctx);
    assert.equal(remove.length, 1);
  });
});

describe('LINE 確認訊息', () => {
  test('把壓好的時間列成一句可以直接貼的話', () => {
    const msg = confirmMessage({ name: '王小姐' }, [
      { date: '2026-09-17', slots: [{ startsAt: '14:00' }] },
      { date: '2026-09-03', slots: [{ startsAt: '14:00' }, { startsAt: '15:15' }] },
    ]);

    assert.equal(msg, '王小姐您好，9 月為您安排了 9/3(四) 14:00、9/17(四) 14:00，請問可以嗎？');
  });

  test('一次來訪只講第一個時段的時間，不把整份時刻表念完', () => {
    const msg = confirmMessage({ name: '王小姐' }, [
      { date: '2026-09-03', slots: [{ startsAt: '15:15' }, { startsAt: '09:15' }] },
    ]);
    assert.ok(msg.includes('09:15'));
    assert.ok(!msg.includes('15:15'));
  });

  test('沒有東西可問就回空字串，不要產生半句話', () => {
    assert.equal(confirmMessage({ name: '王小姐' }, []), '');
  });
});

describe('日期的人話格式', () => {
  test('星期算得對', () => {
    assert.equal(weekdayLabel('2026-09-03'), '四');
    assert.equal(weekdayLabel('2026-09-06'), '日');
  });

  test('M/D(週)', () => {
    assert.equal(shortDate('2026-09-03'), '9/3(四)');
    assert.equal(shortDate('2026-12-25'), '12/25(五)');
  });
});
