// 任務跟著來訪走。SPEC 第 4.1、5.5 節。
//
// 這一支測的是「來訪變了，任務要怎麼跟著變」——這正是現在白紙做不到的事：
// 東西改了，該做的事沒人記得。

import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

import {
  syncTasksForVisit,
  acceptsNewTasks,
  acceptsRecordTasks,
  recordTasksForVisit,
  tasksForVisit,
  isCancelKind,
  cancelKindFor,
  taskLine,
  RECORD_TASK_KIND,
  seenTasks,
} from '../public/js/domain/taskRules.js';
import { confirmMessage } from '../public/js/domain/messages.js';
import { shortDate, weekdayLabel } from '../public/js/domain/dates.js';
import { visitStatusFrom } from '../public/js/domain/visits.js';

const COURSES = {
  rehab: { category: 'A' },   // 復健科：Abovee 壓表，確認後 Examine、耀聖
  checkup: { category: 'B' }, // 健檢：Examine 壓表，確認後沒有後續登記
  recovery: { category: 'C' },// 復能：Abovee 壓表，確認後沒有後續登記
  // 二返：A 類（所以有掛號那一族），而且做完要補一份紀錄（ADR-0066）
  followup: { category: 'A', needsRecord: true },
  // 營養師諮詢：不用掛號，但一樣要補紀錄 —— 這一條逐課程不逐類別
  consult: { category: null, needsRecord: true },
};

const visit = (over = {}) => ({
  id: 'v1',
  customerId: 'c1',
  customerName: '客戶甲',
  date: '2026-09-10',
  status: 'pending_confirm',
  slots: [{ courseId: 'recovery' }],
  ...over,
});

const ctx = { coursesById: COURSES, today: '2026-09-01' };

const task = (over = {}) => ({
  id: 't1',
  visitId: 'v1',
  customerId: 'c1',
  customerName: '客戶甲',
  kind: 'Examine',
  dueDate: '2026-09-09',
  done: false,
  autoGenerated: true,
  ...over,
});

describe('來訪存檔時的任務同步', () => {
  test('客人確認之後產生它該有的任務', () => {
    const { create, update, remove } = syncTasksForVisit(
      visit({ status: 'confirmed', slots: [{ courseId: 'rehab' }] }), [], ctx,
    );

    assert.deepEqual(create.map((t) => t.kind).sort(), ['Examine', '耀聖']);
    assert.ok(create.every((t) => t.dueDate === '2026-09-09'));
    assert.ok(create.every((t) => t.autoGenerated));
    assert.equal(update.length, 0);
    assert.equal(remove.length, 0);
  });

  test('已經有的任務不會再產生一次', () => {
    const confirmed = visit({ status: 'confirmed', slots: [{ courseId: 'rehab' }] });
    const { create } = syncTasksForVisit(confirmed, [task(), task({ id: 't2', kind: '耀聖' })], ctx);
    assert.equal(create.length, 0);
  });

  test('改了來訪日期，死線跟著移，已完成的仍然是已完成', () => {
    const done = task({ done: true, doneAt: '2026-09-02T00:00:00Z' });
    const moved = visit({ date: '2026-09-20', slots: [{ courseId: 'rehab' }] });
    const { update, remove } = syncTasksForVisit(moved, [done], ctx);

    assert.deepEqual(update, [{ id: 't1', changes: { dueDate: '2026-09-19' } }]);
    assert.equal(remove.length, 0);
  });

  test('課程被移出來訪：沒做的移除，做過的留著', () => {
    const undone = task({ id: 'a', kind: 'Examine' });
    const finished = task({ id: 'b', kind: '耀聖', done: true });

    // 來訪只剩復能（C 類），確認後沒有任何登記 —— 兩張都不再需要
    const { remove, create } = syncTasksForVisit(visit(), [undone, finished], ctx);

    assert.deepEqual(remove.map((r) => r.id), ['a']);
    assert.equal(create.length, 0);
  });
});

// 她的順序是「壓表 → 問客人 → 客人說可以 → 才去登記」。壓完表就長出來的話，
// 一晚上二十幾位等於立刻多出幾十件還不確定要不要做的待辦。ADR-0027。
describe('登記任務等客人確認之後才長出來（ADR-0027）', () => {
  test('壓完表記下去，一件登記都不產生', () => {
    const { create, update, remove } = syncTasksForVisit(
      visit({ slots: [{ courseId: 'rehab' }] }), [], ctx,
    );

    assert.deepEqual([create, update, remove], [[], [], []]);
  });

  test('確認之後才長出來，死線仍然是來訪日的前一天', () => {
    const asked = visit({ slots: [{ courseId: 'rehab' }] });
    assert.equal(syncTasksForVisit(asked, [], ctx).create.length, 0);

    const { create } = syncTasksForVisit({ ...asked, status: 'confirmed' }, [], ctx);
    assert.deepEqual(create.map((t) => t.kind).sort(), ['Examine', '耀聖']);
    assert.ok(create.every((t) => t.dueDate === '2026-09-09'));
  });

  test('補記一筆已經上完的課，不會長出一串死線早就過的登記', () => {
    // pending_confirm → done，中間沒有經過 confirmed。那天已經過完了，
    // 掛號沒有東西要補 —— 產生出來只會是四筆一出生就逾期的紅字。
    const { create, remove } = syncTasksForVisit(
      visit({ status: 'done', slots: [{ courseId: 'rehab' }] }),
      [],
      { ...ctx, today: '2026-09-30' },
    );

    assert.deepEqual([create, remove], [[], []]);
  });

  test('來訪結案不會把她還沒做完的登記洗掉', () => {
    // 反過來的方向：confirmed 時長出來的任務，走到 done 一個都不能少。
    // 「還沒做完」本身就是要看得見的事。
    const undone = task({ kind: 'Examine' });
    const { create, remove } = syncTasksForVisit(
      visit({ status: 'done', slots: [{ courseId: 'rehab' }] }), [undone], ctx,
    );

    assert.deepEqual([create, remove], [[], []]);
  });

  test('未到也一樣不產生新的登記', () => {
    const { create } = syncTasksForVisit(
      visit({ status: 'no_show', slots: [{ courseId: 'rehab' }] }), [], ctx,
    );
    assert.equal(create.length, 0);
  });

  test('擋掉的只有「無中生有」—— 還沒確認的來訪照樣收得掉多餘的任務', () => {
    // 來訪只剩復能（C 類 → Abovee），Examine 不再需要。
    // 這一條顧的是「不產生」不可以順手變成「什麼都不做」。
    const stale = task({ id: 'a', kind: 'Examine' });
    const { remove } = syncTasksForVisit(visit(), [stale], ctx);

    assert.deepEqual(remove.map((r) => r.id), ['a']);
  });

  test('acceptsNewTasks() 只認得 confirmed', () => {
    assert.equal(acceptsNewTasks('confirmed'), true);
    for (const s of ['pending_confirm', 'done', 'no_show', 'cancelled', undefined]) {
      assert.equal(acceptsNewTasks(s), false, `${s} 不該產生新任務`);
    }
  });

  // `data/legacyImport.js` 的 importPlan() 就是拿這一支去問的（一筆來訪、
  // 沒有現有任務）。那一層在 node 裡跑不起來（firebase SDK 是 CDN import），
  // 所以在這個接縫上把行為釘住：匯入不是特例，它走的是同一條規則。
  // 見 .scratch/first-real-import/issues/04。
  test('匯進來的未來預約會長出登記待辦，已經發生的一筆都不長', () => {
    const imported = (over) => visit({
      slots: [{ courseId: 'rehab' }],
      importedFrom: { source: 'merge-file' },
      ...over,
    });

    const past = syncTasksForVisit(imported({ status: 'done' }), [], ctx);
    assert.deepEqual([past.create, past.update, past.remove], [[], [], []],
      '那些掛號在舊系統早就做完了');

    const ahead = syncTasksForVisit(imported({ status: 'confirmed' }), [], ctx);
    assert.deepEqual(ahead.create.map((t) => t.kind).sort(), ['Examine', '耀聖']);
    assert.ok(ahead.create.every((t) => t.autoGenerated));
  });
});

describe('取消來訪時的任務', () => {
  const cancelled = visit({ status: 'cancelled' });

  // 來訪存在就代表她已經在 Abovee（健檢是 Examine）上把時段佔住了 ——
  // app 裡的來訪從「已壓表」開始，所以不需要任何任務來證明她壓過。
  test('壓表登記本身一律要收回來', () => {
    const { create, remove } = syncTasksForVisit(cancelled, [], ctx);

    assert.deepEqual(create.map((t) => t.kind), ['取消 Abovee']);
    assert.ok(create[0].note.includes('放掉'));
    assert.ok(create[0].note.includes('2026-09-10'));
    assert.deepEqual(remove, []);
  });

  test('健檢是壓在 Examine 上的，所以要收回來的是那一個', () => {
    const { create } = syncTasksForVisit(
      visit({ status: 'cancelled', slots: [{ courseId: 'checkup' }] }), [], ctx,
    );
    assert.deepEqual(create.map((t) => t.kind), ['取消 Examine']);
  });

  test('同一天兩種課程 —— 兩個系統上真的各有一筆', () => {
    const { create } = syncTasksForVisit(
      visit({ status: 'cancelled', slots: [{ courseId: 'recovery' }, { courseId: 'checkup' }] }),
      [], ctx,
    );
    assert.deepEqual(create.map((t) => t.kind).sort(), ['取消 Abovee', '取消 Examine']);
  });

  test('還沒做的任務直接收掉 —— 那件事不用做了', () => {
    const { remove } = syncTasksForVisit(cancelled, [task()], ctx);
    assert.deepEqual(remove, [{ id: 't1', reason: '來訪已取消' }]);
  });

  test('已經登記過的要產生「回去取消」的任務（SPEC 4.1）', () => {
    const registered = [
      task({ id: 'a', kind: 'Abovee', done: true }),
      task({ id: 'b', kind: 'Examine', done: true }),
      task({ id: 'c', kind: '耀聖', done: true }),
    ];
    const { create, remove } = syncTasksForVisit(cancelled, registered, ctx);

    assert.deepEqual(create.map((t) => t.kind), ['取消 Abovee', '取消 Examine', '取消 耀聖']);
    assert.ok(create.every((t) => isCancelKind(t.kind)));
    assert.ok(create.every((t) => t.note.includes('2026-09-10')));
    assert.equal(remove.length, 0, '已完成的不刪，那件事真的做過');
  });

  test('壓表登記與已勾掉的同名任務不會各長一張', () => {
    // 復能壓在 Abovee，而歷史資料裡也有一張勾掉的 Abovee 任務 —— 那是同一件事
    const { create } = syncTasksForVisit(
      cancelled, [task({ id: 'a', kind: 'Abovee', done: true })], ctx,
    );
    assert.deepEqual(create.map((t) => t.kind), ['取消 Abovee']);
  });

  test('打電話做過了就是做過了，沒有東西要收回來', () => {
    const { create } = syncTasksForVisit(cancelled, [task({ kind: '打電話', done: true })], ctx);
    assert.ok(!create.some((t) => t.kind === '取消 打電話'));
  });

  test('取消登記沒有寬限期：今天比死線早就用今天', () => {
    const { create } = syncTasksForVisit(cancelled, [], ctx);
    assert.equal(create[0].dueDate, '2026-09-01');

    const late = syncTasksForVisit(cancelled, [], { ...ctx, today: '2026-09-30' });
    assert.equal(late.create[0].dueDate, '2026-09-09', '死線已經過了就照死線，逾期看得出來');
  });

  test('取消類的任務不會被之後的同步再動到，也不會長出第二張', () => {
    const existing = [task({ id: 'x', kind: cancelKindFor('Abovee') })];
    const { create, update, remove } = syncTasksForVisit(cancelled, existing, ctx);
    assert.deepEqual([create, update, remove], [[], [], []]);
  });

  test('已經勾掉的取消任務也不會再長一張', () => {
    const existing = [task({ id: 'x', kind: cancelKindFor('Abovee'), done: true })];
    assert.deepEqual(syncTasksForVisit(cancelled, existing, ctx).create, []);
  });

  test('軟刪除的來訪與取消一樣處理', () => {
    const { remove } = syncTasksForVisit(visit({ deletedAt: 'x' }), [task()], ctx);
    assert.equal(remove.length, 1);
  });
});

describe('LINE 確認訊息', () => {
  test('每一段各自一行：日期、幾點到幾點、課程', () => {
    const msg = confirmMessage({ name: '王小姐' }, [
      { date: '2026-09-17', slots: [
        { startsAt: '11:00', endsAt: '12:00', courseName: '復能' },
        { startsAt: '10:00', endsAt: '11:00', courseName: '營養點滴' },
      ] },
      { date: '2026-09-03', slots: [{ startsAt: '14:00', endsAt: '15:00', courseName: '復能' }] },
    ]);

    assert.equal(msg, [
      '王小姐您好，9 月為您安排了：',
      '9/3(四) 14:00–15:00 復能',
      '9/17(四) 10:00–11:00 營養點滴',
      '9/17(四) 11:00–12:00 復能',
      '請問可以嗎？',
    ].join('\n'));
  });

  test('**時間寫完整的一段**（2026-09-05 推翻了「只寫幾點開始」）', () => {
    // 她的原話：「不是只寫幾點開始，而是幾點 - 幾點」。
    // 「9/17 11:00 復能」看不出做完是幾點，而那正是客戶排當天其他事情要用的
    // 那個數字。橫槓用 en dash，跟 `timeLabel()` 與「臨時空出一格」那一則一樣。
    const msg = confirmMessage({ name: '王小姐' }, [
      { date: '2026-09-03', slots: [{ startsAt: '09:15', endsAt: '10:15', courseName: '復能' }] },
    ]);
    assert.ok(msg.includes('09:15–10:15 復能'), msg);
    assert.ok(!msg.includes('09:15 復能'), '不可以只印開始時間');
  });

  test('只記得開始時間的那一段就只印開始 —— 不要湊一個半截的橫槓', () => {
    const msg = confirmMessage({ name: '王小姐' }, [
      { date: '2026-09-03', slots: [{ startsAt: '14:00', endsAt: null, courseName: '復能' }] },
    ]);
    assert.ok(msg.includes('9/3(四) 14:00 復能'), msg);
    assert.ok(!msg.includes('–'), '結束時間不知道就不要印橫槓');
  });

  test('**同一天不同時段的都要印**（2026-09-04 推翻了「只講第一段」）', () => {
    // 舊的行為是一筆來訪只印第一個時段，理由是「不要把時刻表念一遍」。
    // 她實際用過之後說：少印的那幾段客戶照樣要來，看不到反而以為只有一段。
    const msg = confirmMessage({ name: '王小姐' }, [
      { date: '2026-09-03', slots: [
        { startsAt: '15:15', endsAt: '16:15', courseName: '靜脈' },
        { startsAt: '09:15', endsAt: '10:15', courseName: '復能' },
      ] },
    ]);
    assert.ok(msg.includes('09:15–10:15 復能'));
    assert.ok(msg.includes('15:15–16:15 靜脈'));
    // 而且早的排前面
    assert.ok(msg.indexOf('09:15') < msg.indexOf('15:15'));
  });

  test('沒有時間的那一段不印時間 —— 「時間不詳」貼給客戶只會被打電話問', () => {
    const msg = confirmMessage({ name: '王小姐' }, [
      { date: '2026-09-03', slots: [{ startsAt: null, endsAt: null, courseName: '復能' }] },
    ]);
    assert.ok(msg.includes('9/3(四) 復能'));
    assert.ok(!msg.includes('時間不詳'));
    // 那一行不可以多一個空格或半截橫槓出來
    assert.ok(!msg.includes('–'));
    assert.ok(!msg.includes('  '));
  });

  test('沒有東西可問就回空字串，不要產生半句話', () => {
    assert.equal(confirmMessage({ name: '王小姐' }, []), '');
    // 有來訪但一段都沒有，照樣是半句話
    assert.equal(confirmMessage({ name: '王小姐' }, [{ date: '2026-09-03', slots: [] }]), '');
  });
});

describe('日期的人話格式', () => {
  test('星期算得對', () => {
    assert.equal(weekdayLabel('2026-09-03'), '四');
    assert.equal(weekdayLabel('2026-09-06'), '日');
  });

  test('M/D(週)', () => {
    assert.equal(shortDate('2026-09-03'), '9/3(四)');
    assert.equal(shortDate('2026-12-25'), '12/25(五)');
  });
});

// ---------- 勾掉一張待辦要把健檢鏈一起帶著走 ----------
//
// 這一支不執行程式碼，只讀原始碼 —— 跟 `module-names.test.js` 同一個路數。
// `data/*.js` 從 gstatic 載入 Firebase SDK，node 載不進來，而這裡要守的是
// 一個「不執行就看不出來、執行了要有真的 Firestore 才看得出來」的接線：
//
//   勾掉「追蹤健檢報告」→ 同一個 commit 裡把「約二返」長出來
//
// 2026-08-25 以前這條線根本不存在（`syncFollowupTasks()` 三個呼叫端全在
// `save()` / `remove()` / `restore()` 底下），而且**947 個測試全綠** ——
// 規則本身測得很完整，只是沒有人在勾掉的那一刻叫它。
// 見 `.scratch/asks-2026-08-25/issues/09`。
describe('勾完成那一支的接線', () => {
  const src = readFileSync(
    new URL('../public/js/data/tasks.js', import.meta.url), 'utf8',
  );
  const setDone = src.slice(src.indexOf('export async function setDone'));

  test('setDone 把健檢鏈的操作放進同一個 commit', () => {
    assert.match(setDone, /followupOpsAfterTaskChange/,
      '勾掉「追蹤健檢報告」要連著把「約二返」長出來');
    assert.match(setDone, /repo\.commit\(\[[\s\S]*followupOpsAfterTaskChange/,
      '兩件事要在同一個 commit 裡，不然復原只退得回其中一半');
  });

  test('setDone 收的是任務本身，不是 id', () => {
    // 收 id 的話這一層得先把那幾筆讀回來才知道是不是鏈上的那兩種，
    // 而呼叫端手上本來就有 —— 那是白白多一輪往返。
    assert.match(setDone, /setDone\(tasks, done\)/);
  });
});

// ---------- 一列任務要講的三件事 ----------
//
// 她的原話：「客戶詳情裡的任務目前只會顯示 Examine 或 耀聖，資訊量太少……
// 例如：Examine・9/1・二返」。
//
// 三個地方共用（試算表的 TODO 區、客戶詳情、待辦中心），所以「日期取哪一個」
// 只能有一份答案 —— 兩份的話會有一份差一天。

describe('一列任務要講的三件事', () => {
  const t = task({ kind: 'Examine', dueDate: '2026-09-09' });

  test('日期是**來訪那一天**，不是死線', () => {
    const line = taskLine(t, visit({ date: '2026-09-10', slots: [{ courseName: '二返' }] }));
    assert.equal(line.date, '2026-09-10');
    assert.equal(line.fromDue, false);
    assert.equal(line.kind, 'Examine');
    assert.equal(line.what, '二返');
  });

  test('來訪找不到才退回死線，而且要講得出來那是退回來的', () => {
    const line = taskLine(t, null);
    assert.equal(line.date, '2026-09-09');
    assert.equal(line.fromDue, true, '畫面要靠它決定講不講「死線」兩個字');
    assert.equal(line.what, '');
  });

  test('同一場兩段同一個課程只印一次（去重在 visitCourseLabel）', () => {
    const line = taskLine(t, visit({
      slots: [{ courseName: '復能' }, { courseName: '復能' }, { courseName: '營養針' }],
    }));
    assert.equal(line.what, '復能、營養針');
  });

  test('課程名全都認不出來就退回「N 段」，不是空白', () => {
    const line = taskLine(t, visit({ slots: [{}, {}] }));
    assert.equal(line.what, '2 段');
  });

  test('沒有時段就沒有東西可講 —— 不要印「0 段」', () => {
    assert.equal(taskLine(t, visit({ slots: [] })).what, '');
  });

  test('死線與來訪日都沒有也不會爆', () => {
    const line = taskLine({ kind: '耀聖' }, null);
    assert.equal(line.date, null);
    assert.equal(line.kind, '耀聖');
  });
});


// ---------------------------------------------------------------------------
// ADR-0066：紀錄是來訪之後才長出來的任務
// ---------------------------------------------------------------------------

describe('客人走了之後要寫的那一張（ADR-0066）', () => {
  const consult = (over = {}) => visit({ slots: [{ courseId: 'consult' }], ...over });
  const record = (over = {}) => task({ id: 'tw', kind: RECORD_TASK_KIND, dueDate: '2026-09-10', ...over });

  test('兩個閘門是兩件事：掛號等客人確認，紀錄等那一場做完', () => {
    assert.equal(acceptsNewTasks('confirmed'), true);
    assert.equal(acceptsNewTasks('done'), false);
    assert.equal(acceptsRecordTasks('done'), true);
    assert.equal(acceptsRecordTasks('confirmed'), false);
    assert.equal(acceptsRecordTasks('no_show'), false, '人沒來，沒有紀錄要寫');
  });

  test('死線是來訪那一天，不是它的前一天', () => {
    const [t] = recordTasksForVisit(consult({ status: 'done' }), COURSES);
    assert.equal(t.dueDate, '2026-09-10');
    assert.equal(t.kind, RECORD_TASK_KIND);
    assert.equal(t.visitId, 'v1');
  });

  test('課程主檔上沒勾就一張都不長 —— 這一條逐課程不逐類別', () => {
    assert.deepEqual(recordTasksForVisit(visit({ status: 'done' }), COURSES), []);
  });

  test('同一天兩個都要寫紀錄的課程只長一張', () => {
    const both = visit({ status: 'done', slots: [{ courseId: 'consult' }, { courseId: 'followup' }] });
    assert.equal(recordTasksForVisit(both, COURSES).length, 1);
  });

  test('確認 → 已完成：長出寫紀錄，而還沒做完的 Examine 一張都不會被收掉', () => {
    const rehabDone = visit({ status: 'done', slots: [{ courseId: 'followup' }] });
    const { create, remove } = syncTasksForVisit(rehabDone, [task()], ctx);

    assert.deepEqual(create.map((t) => t.kind), [RECORD_TASK_KIND]);
    assert.deepEqual(remove, [], '掛號那一族不因為結案而消失（ADR-0027 的 Consequences）');
  });

  test('已完成 → 拿回來改成已確認：沒勾的那一張收掉，理由講得出是哪一種情況', () => {
    const { create, remove } = syncTasksForVisit(consult({ status: 'confirmed' }), [record()], ctx);
    assert.deepEqual(create, []);
    assert.deepEqual(remove, [{ id: 'tw', reason: '那一場沒有做完，沒有紀錄要寫' }]);
  });

  test('改成未到也一樣收掉 —— 人沒來就沒有紀錄要寫', () => {
    const { remove } = syncTasksForVisit(consult({ status: 'no_show' }), [record()], ctx);
    assert.deepEqual(remove, [{ id: 'tw', reason: '那一場沒有做完，沒有紀錄要寫' }]);
  });

  test('課程被移出來訪時，理由是另一句 —— 兩種情況要分得出來', () => {
    const swapped = visit({ status: 'done', slots: [{ courseId: 'recovery' }] });
    const { remove } = syncTasksForVisit(swapped, [record()], ctx);
    assert.deepEqual(remove, [{ id: 'tw', reason: '來訪裡已經沒有需要這個任務的課程' }]);
  });

  test('已經勾掉的紀錄一律不刪，就算來訪被拿回來也一樣', () => {
    const { remove } = syncTasksForVisit(
      consult({ status: 'confirmed' }), [record({ done: true, doneAt: 'x' })], ctx,
    );
    assert.deepEqual(remove, []);
  });

  test('改日期時死線跟著移到新的那一天', () => {
    const moved = consult({ status: 'done', date: '2026-09-12' });
    const { update } = syncTasksForVisit(moved, [record()], ctx);
    assert.deepEqual(update, [{ id: 'tw', changes: { dueDate: '2026-09-12' } }]);
  });

  test('來訪取消時沒勾的收掉 —— 那一場沒發生', () => {
    const { remove } = syncTasksForVisit(consult({ status: 'cancelled' }), [record()], ctx);
    assert.ok(remove.some((r) => r.id === 'tw'));
  });

  test('已經有一張了就不再長第二張', () => {
    const { create } = syncTasksForVisit(consult({ status: 'done' }), [record()], ctx);
    assert.deepEqual(create, []);
  });
});

describe('一段取消掉，回去把那個時段放掉（ADR-0081）', () => {
  const COURSES = {
    'c-recovery': { id: 'c-recovery', name: '復能', category: 'C' },
    'c-checkup': { id: 'c-checkup', name: '健檢', category: 'B' },
  };
  const TODAY = '2026-09-01';
  const v = (slots, over = {}) => ({
    id: 'v1', customerId: 'cust1', customerName: '客戶A',
    date: '2026-09-20', status: 'confirmed', slots, ...over,
  });

  test('整筆還活著，但那一段取消了 → 長出「取消 Abovee」', () => {
    const visit = v([
      { courseId: 'c-recovery', status: 'cancelled' },
      { courseId: 'c-recovery', status: 'confirmed' },
    ]);
    const { create } = syncTasksForVisit(visit, [], { coursesById: COURSES, today: TODAY });
    assert.ok(create.some((t) => t.kind === '取消 Abovee'),
      '她在 Abovee 上壓過那一格，要回去放掉');
  });

  test('只講那一段用得到的系統', () => {
    const visit = v([
      { courseId: 'c-checkup', status: 'cancelled' },
      { courseId: 'c-recovery', status: 'confirmed' },
    ]);
    const { create } = syncTasksForVisit(visit, [], { coursesById: COURSES, today: TODAY });
    const kinds = create.map((t) => t.kind);
    assert.ok(kinds.includes('取消 Examine'), '健檢壓在 Examine');
    assert.ok(!kinds.includes('取消 Abovee'), '復能那一段還在，不要叫她去收 Abovee');
  });

  test('同一個系統取消兩段只長一張 —— 她回去一次收兩格', () => {
    const visit = v([
      { courseId: 'c-recovery', status: 'cancelled' },
      { courseId: 'c-recovery', status: 'cancelled' },
      { courseId: 'c-checkup', status: 'confirmed' },
    ]);
    const { create } = syncTasksForVisit(visit, [], { coursesById: COURSES, today: TODAY });
    assert.equal(create.filter((t) => t.kind === '取消 Abovee').length, 1);
  });

  test('已經有那一張就不要再長一張（存兩次也一樣）', () => {
    const visit = v([
      { courseId: 'c-recovery', status: 'cancelled' },
      { courseId: 'c-recovery', status: 'confirmed' },
    ]);
    const existing = [{ id: 't1', kind: '取消 Abovee', done: false, autoGenerated: true }];
    const { create } = syncTasksForVisit(visit, existing, { coursesById: COURSES, today: TODAY });
    assert.equal(create.filter((t) => t.kind === '取消 Abovee').length, 0);
  });

  test('她已經做掉那一張了也不要再長一張', () => {
    const visit = v([
      { courseId: 'c-recovery', status: 'cancelled' },
      { courseId: 'c-recovery', status: 'confirmed' },
    ]);
    const existing = [{ id: 't1', kind: '取消 Abovee', done: true, autoGenerated: true }];
    const { create } = syncTasksForVisit(visit, existing, { coursesById: COURSES, today: TODAY });
    assert.equal(create.filter((t) => t.kind === '取消 Abovee').length, 0);
  });

  test('一段都沒取消時一張都不長（回歸）', () => {
    const visit = v([
      { courseId: 'c-recovery', status: 'confirmed' },
      { courseId: 'c-checkup', status: 'confirmed' },
    ]);
    const { create } = syncTasksForVisit(visit, [], { coursesById: COURSES, today: TODAY });
    assert.ok(!create.some((t) => t.kind.startsWith('取消 ')));
  });

  test('整筆取消時照舊走 gone 那一段 —— 每一段都是 cancelled 也照樣長得出來', () => {
    // applyStatus(v, 'cancelled') 現在會把每一段都標成 cancelled，
    // 所以 gone 那一段**不可以**改成只看還活著的時段（會變成一張都不長）。
    const visit = v(
      [{ courseId: 'c-recovery', status: 'cancelled' }, { courseId: 'c-checkup', status: 'cancelled' }],
      { status: 'cancelled' },
    );
    const { create } = syncTasksForVisit(visit, [], { coursesById: COURSES, today: TODAY });
    const kinds = create.map((t) => t.kind);
    assert.ok(kinds.includes('取消 Abovee'));
    assert.ok(kinds.includes('取消 Examine'));
  });
});

describe('取消掉的那一段不再要求她做任何事（ADR-0081）', () => {
  const COURSES = {
    'c-recovery': { id: 'c-recovery', name: '復能', category: 'C' },
    'c-followup': { id: 'c-followup', name: '二返', category: 'A', needsTreatmentForm: false, needsRecord: true },
    'c-checkup': { id: 'c-checkup', name: '健檢', category: 'B' },
  };

  test('掛號那一族只看還算數的那幾段', () => {
    // 二返（A 類）取消掉之後就不用去 Examine 與耀聖掛號了
    const v = {
      id: 'v1', customerId: 'c1', date: '2026-09-20', status: 'confirmed',
      slots: [
        { courseId: 'c-followup', status: 'cancelled' },
        { courseId: 'c-recovery', status: 'confirmed' },
      ],
    };
    assert.deepEqual(tasksForVisit(v, COURSES).map((t) => t.kind), []);
  });

  test('還有一段是 A 類的話照樣要掛號', () => {
    const v = {
      id: 'v1', customerId: 'c1', date: '2026-09-20', status: 'confirmed',
      slots: [
        { courseId: 'c-followup', status: 'cancelled' },
        { courseId: 'c-followup', status: 'confirmed' },
      ],
    };
    assert.deepEqual(tasksForVisit(v, COURSES).map((t) => t.kind).sort(), ['Examine', '耀聖']);
  });

  test('那一段取消了就沒有紀錄要寫', () => {
    const v = {
      id: 'v1', customerId: 'c1', date: '2026-09-20', status: 'done',
      slots: [
        { courseId: 'c-followup', status: 'cancelled' },
        { courseId: 'c-recovery', status: 'done' },
      ],
    };
    assert.deepEqual(recordTasksForVisit(v, COURSES), []);
  });
});

// ---------------------------------------------------------------------------
// 取消類的待辦記得它收的是哪幾段（`.scratch/asks-2026-09-13/issues/02`）。
//
// 她 2026-09-13：「我一天幫A押三個時段，然後我取消了其中一段後，其他兩段的這一項的待辦
// 就多了"取消Aobvee" ?」—— 查下去同一個缺口長出三個症狀，這一段釘的是資料那一側。

describe('那一段確認了，那一段的掛號才長出來（ADR-0097）', () => {
  // 她 2026-09-16 拍板：只確認兩段裡的一段時，那一段的 Examine／耀聖要當場長。
  // 不跟的話有一個她看不見的洞：整筆停在 pending_confirm，於是那一段的登記
  // 一張都不長 —— 而她已經可以去 Abovee 壓那一格了。
  const COURSES = {
    'c-followup': { id: 'c-followup', name: '二返', category: 'A' },
    'c-recovery': { id: 'c-recovery', name: '復能', category: 'C' },
  };
  const ctx2 = { coursesById: COURSES, today: '2026-09-13' };
  const v = (...statuses) => {
    const doc = {
      id: 'v1', customerId: 'c1', customerName: '客戶A', date: '2026-09-20',
      slots: statuses.map(([courseId, status]) => ({ courseId, status })),
    };
    return { ...doc, status: visitStatusFrom(doc) };
  };
  const kinds = (visit, existing = []) =>
    syncTasksForVisit(visit, existing, ctx2).create
      .filter((t) => !isCancelKind(t.kind))
      .map((t) => t.kind)
      .sort();

  test('只確認 A 類那一段 → 那一段的掛號長出來', () => {
    const visit = v(['c-followup', 'confirmed'], ['c-recovery', 'pending_confirm']);
    assert.equal(visit.status, 'pending_confirm', '整筆還是待確認 —— 復能那一段還沒問');
    assert.deepEqual(kinds(visit), ['Examine', '耀聖']);
  });

  test('只確認 C 類那一段 → 一張都不長（C 類本來就沒有後續登記）', () => {
    const visit = v(['c-followup', 'pending_confirm'], ['c-recovery', 'confirmed']);
    assert.deepEqual(kinds(visit), []);
  });

  test('整天都還沒確認 → 一張都不長', () => {
    assert.deepEqual(kinds(v(['c-followup', 'pending_confirm'], ['c-recovery', 'pending_confirm'])), []);
  });

  test('兩段都是 A 類、只確認一段 → 那一種只長一張（去重照舊）', () => {
    const visit = v(['c-followup', 'confirmed'], ['c-followup', 'pending_confirm']);
    assert.deepEqual(kinds(visit), ['Examine', '耀聖']);
  });

  test('取消掉的那一段不算 —— 它長不出任何登記', () => {
    const visit = v(['c-followup', 'cancelled'], ['c-recovery', 'confirmed']);
    assert.deepEqual(kinds(visit), []);
  });

  // ---- ADR-0027 的兩條邊界照樣成立 ----

  test('補記一筆已經上完的課（pending_confirm → done）照樣一張都不長', () => {
    const visit = v(['c-followup', 'done'], ['c-recovery', 'done']);
    assert.equal(visit.status, 'done');
    assert.deepEqual(kinds(visit), []);
  });

  test('confirmed → done：她還沒做完的登記一張都不能少', () => {
    const existing = [
      { id: 'e', visitId: 'v1', kind: 'Examine', done: false, autoGenerated: true, dueDate: '2026-09-19' },
    ];
    const visit = v(['c-followup', 'done'], ['c-recovery', 'done']);
    const { remove } = syncTasksForVisit(visit, existing, ctx2);
    assert.deepEqual(remove, [], '結案不可以把沒做完的 Examine 靜默收掉');
  });

  test('存兩次不會多長（冪等）', () => {
    const visit = v(['c-followup', 'confirmed'], ['c-recovery', 'pending_confirm']);
    const first = syncTasksForVisit(visit, [], ctx2).create.map((t, i) => ({ ...t, id: `n${i}` }));
    assert.deepEqual(kinds(visit, first), []);
  });
});

describe('取消類的待辦逐段（slotIndexes）', () => {
  const COURSES = {
    'c-recovery': { id: 'c-recovery', name: '復能', category: 'C' },
    'c-followup': { id: 'c-followup', name: '二返', category: 'A' },
    'c-checkup': { id: 'c-checkup', name: '健檢', category: 'B' },
  };
  const ctx = { coursesById: COURSES, today: '2026-09-13' };
  const v = (statuses, over = {}) => ({
    id: 'v1', customerId: 'c1', customerName: '客戶A', date: '2026-09-20', status: 'confirmed',
    slots: statuses.map(([courseId, status]) => ({ courseId, status })),
    ...over,
  });
  const cancelsOf = (create) => create.filter((t) => isCancelKind(t.kind))
    .map((t) => ({ kind: t.kind, slotIndexes: t.slotIndexes }));

  test('一段取消 → 那一張記著是哪一段', () => {
    const visit = v([['c-recovery', 'confirmed'], ['c-recovery', 'cancelled'], ['c-recovery', 'confirmed']]);
    const { create } = syncTasksForVisit(visit, [], ctx);
    assert.deepEqual(cancelsOf(create), [{ kind: '取消 Abovee', slotIndexes: [1] }]);
  });

  test('第一張勾掉之後隔天再取消另一段 → 長第二張，只收那一段', () => {
    // 以前「同一個系統，含已經勾掉的，只准一張」—— 第二段在 Abovee 上永遠沒人去放
    const visit = v([['c-recovery', 'cancelled'], ['c-recovery', 'confirmed'], ['c-recovery', 'cancelled']]);
    const existing = [{
      id: 't1', visitId: 'v1', kind: '取消 Abovee', done: true, autoGenerated: true, slotIndexes: [0],
    }];
    const { create } = syncTasksForVisit(visit, existing, ctx);
    assert.deepEqual(cancelsOf(create), [{ kind: '取消 Abovee', slotIndexes: [2] }]);
  });

  test('同一次存檔取消兩段 → 收成一張，兩段都記著', () => {
    const visit = v([['c-recovery', 'cancelled'], ['c-recovery', 'cancelled'], ['c-recovery', 'confirmed']]);
    const { create } = syncTasksForVisit(visit, [], ctx);
    assert.deepEqual(cancelsOf(create), [{ kind: '取消 Abovee', slotIndexes: [0, 1] }]);
  });

  test('存兩次不會多長（冪等）', () => {
    const visit = v([['c-recovery', 'cancelled'], ['c-recovery', 'confirmed']]);
    const first = syncTasksForVisit(visit, [], ctx).create.map((t, i) => ({ ...t, id: `n${i}` }));
    const again = syncTasksForVisit(visit, first, ctx).create;
    assert.deepEqual(cancelsOf(again), []);
  });

  test('整天取消 → 每個系統一張，記著用得到它的那幾段', () => {
    const visit = v(
      [['c-recovery', 'cancelled'], ['c-checkup', 'cancelled'], ['c-recovery', 'cancelled']],
      { status: 'cancelled' },
    );
    const { create } = syncTasksForVisit(visit, [], ctx);
    assert.deepEqual(cancelsOf(create), [
      { kind: '取消 Abovee', slotIndexes: [0, 2] },
      { kind: '取消 Examine', slotIndexes: [1] },
    ]);
  });

  // **2026-09-16 定案**（她原話：「收，但是就只收那個時段的，反正現在就是
  // 每個時段和每個時段都是分開獨立的」）。2026-09-13 的暫定值＝定案，
  // 所以底下這幾條是行為的規格，不再是暫定的。見 `docs/adr/0091`。
  test('只取消二返那一段、Examine 與耀聖都勾過 → 那兩個登記也要收，只收那一段', () => {
    const visit = v([['c-followup', 'cancelled'], ['c-recovery', 'confirmed']]);
    const existing = [
      { id: 'e', visitId: 'v1', kind: 'Examine', done: true, autoGenerated: true },
      { id: 'y', visitId: 'v1', kind: '耀聖', done: true, autoGenerated: true },
    ];
    const { create } = syncTasksForVisit(visit, existing, ctx);
    assert.deepEqual(cancelsOf(create), [
      { kind: '取消 Abovee', slotIndexes: [0] },
      { kind: '取消 Examine', slotIndexes: [0] },
      { kind: '取消 耀聖', slotIndexes: [0] },
    ]);
  });

  test('只取消復能那一段 → 不長「取消 Examine」（那一段沒在 Examine 登記過）', () => {
    const visit = v([['c-followup', 'confirmed'], ['c-recovery', 'cancelled']]);
    const existing = [{ id: 'e', visitId: 'v1', kind: 'Examine', done: true, autoGenerated: true }];
    const { create } = syncTasksForVisit(visit, existing, ctx);
    assert.deepEqual(cancelsOf(create), [{ kind: '取消 Abovee', slotIndexes: [1] }]);
  });

  // 2026-09-16 定案那一條真正的判準：同一天**兩段都是 A 類**，只取消其中一段。
  // 「只收那個時段的」在這裡才分得出來 —— 上面那幾條同一天只有一段 A 類，
  // 收整天與收那一段長得一模一樣。
  test('同一天兩段 A 類，只取消一段 → 取消 Examine 只記那一段', () => {
    const visit = v([['c-followup', 'cancelled'], ['c-followup', 'confirmed']]);
    const existing = [
      { id: 'e', visitId: 'v1', kind: 'Examine', done: true, autoGenerated: true },
      { id: 'y', visitId: 'v1', kind: '耀聖', done: true, autoGenerated: true },
    ];
    const { create } = syncTasksForVisit(visit, existing, ctx);
    assert.deepEqual(cancelsOf(create), [
      { kind: '取消 Abovee', slotIndexes: [0] },
      { kind: '取消 Examine', slotIndexes: [0] },
      { kind: '取消 耀聖', slotIndexes: [0] },
    ], '第 1 段還活著，一個索引都不可以跟著進去');
  });

  test('Examine 還沒勾就取消那一段 → 沒登記過就不用收', () => {
    const visit = v([['c-followup', 'cancelled'], ['c-recovery', 'confirmed']]);
    const existing = [{ id: 'e', visitId: 'v1', kind: 'Examine', done: false, autoGenerated: true }];
    const { create, remove } = syncTasksForVisit(visit, existing, ctx);
    assert.ok(!create.some((t) => t.kind === '取消 Examine'));
    assert.deepEqual(remove.map((r) => r.id), ['e'], '那一張沒勾的 Examine 照舊收掉');
  });

  test('一天兩段二返、只取消一段、Examine 勾過 → 收那一段；另一段的 Examine 照舊留著', () => {
    const visit = v([['c-followup', 'confirmed'], ['c-followup', 'cancelled']]);
    const existing = [{ id: 'e', visitId: 'v1', kind: 'Examine', done: true, autoGenerated: true }];
    const { create, remove } = syncTasksForVisit(visit, existing, ctx);
    assert.deepEqual(cancelsOf(create).find((t) => t.kind === '取消 Examine'),
      { kind: '取消 Examine', slotIndexes: [1] });
    assert.deepEqual(remove, []);
  });

  test('沒記段落的舊「取消 Abovee」當成蓋住整天 —— 不會多長一張', () => {
    const visit = v([['c-recovery', 'cancelled'], ['c-recovery', 'cancelled']]);
    const existing = [{ id: 'old', visitId: 'v1', kind: '取消 Abovee', done: true, autoGenerated: true }];
    const { create } = syncTasksForVisit(visit, existing, ctx);
    assert.deepEqual(cancelsOf(create), []);
  });
});

// ---------- 清掉已完成的待辦之後再存一次（報告 §2.2） ----------
//
// 「清掉這 N 筆」與已完成那一列的垃圾桶都是**軟刪除**（SPEC 第 6.1 節）。
// 2026-09-16 之前 `syncTasksForVisit()` 與 `cancelTasksFor()` 都濾掉
// `deletedAt`，而讀那一份的 `listByVisit()` 也濾 —— 兩層各濾一次。
// 於是清掉之後同一筆來訪再存一次，做過的那幾張會重新長出來，
// 而那幾張假的待辦會叫她**再去 Examine 掛一次號**。

describe('軟刪除的任務照樣算在比對裡', () => {
  const COURSES2 = { 'c-rehab': { category: 'A' }, 'c-recovery': { category: 'C' } };
  const ctx2 = { coursesById: COURSES2, today: '2026-09-16' };
  const slotAt = (courseId, status, startsAt) => ({
    courseId, entitlementId: 'e1', startsAt, endsAt: startsAt, status,
  });
  const v2 = (slots, status = 'confirmed') => ({
    id: 'v1', customerId: 'c1', customerName: '客戶A', date: '2026-09-20', status, slots,
  });
  const cleared = (t) => ({ ...t, visitId: 'v1', done: true, doneAt: '2026-09-16', autoGenerated: true, deletedAt: '2026-09-16' });

  test('清掉的「取消 Abovee」照樣蓋住那一段 —— 不再長一張死線已過的', () => {
    const visit = v2([slotAt('c-recovery', 'cancelled', '09:00'), slotAt('c-recovery', 'confirmed', '10:00')]);
    const existing = [cleared({ id: 't1', kind: '取消 Abovee', slotIndexes: [0] })];
    const { create } = syncTasksForVisit(visit, existing, ctx2);
    assert.deepEqual(create.filter((t) => isCancelKind(t.kind)), []);
  });

  test('清掉的 Examine／耀聖照樣算登記過 —— 改個時間再存不會重長', () => {
    const visit = v2([slotAt('c-rehab', 'confirmed', '09:00')]);
    const existing = [cleared({ id: 't1', kind: 'Examine' }), cleared({ id: 't2', kind: '耀聖' })];
    const { create } = syncTasksForVisit(visit, existing, ctx2);
    assert.deepEqual(create.map((t) => t.kind), []);
  });

  test('已經登記過那一件（就算那一列被清掉）→ 取消時照樣要收回來', () => {
    const visit = v2([slotAt('c-rehab', 'cancelled', '09:00')]);
    const existing = [cleared({ id: 't1', kind: 'Examine' })];
    const { create } = syncTasksForVisit(visit, existing, ctx2);
    assert.ok(create.some((t) => t.kind === '取消 Examine'),
      '她真的去 Examine 掛過號了，那一格要回去放掉');
  });

  test('**軟刪除的那幾張一個字都不會被改**', () => {
    // 課程被移出來訪 → 沒做完的會被收掉，但已經刪掉的不可以再被 remove 一次
    //（那會把它從「已刪除項目」裡救回來，而她按下刪除時並沒有要那樣）
    const visit = v2([slotAt('c-recovery', 'confirmed', '09:00')]);
    const existing = [{
      id: 't1', visitId: 'v1', kind: 'Examine', done: false,
      autoGenerated: true, deletedAt: '2026-09-16', dueDate: '1999-01-01',
    }];
    const { update, remove } = syncTasksForVisit(visit, existing, ctx2);
    assert.deepEqual(remove, []);
    assert.deepEqual(update, []);
  });

  test('死線改了也不去動已經刪掉的那一張', () => {
    const visit = v2([slotAt('c-rehab', 'confirmed', '09:00')]);
    const existing = [{
      id: 't1', visitId: 'v1', kind: 'Examine', done: false,
      autoGenerated: true, deletedAt: '2026-09-16', dueDate: '1999-01-01',
    }];
    const { update, create } = syncTasksForVisit(visit, existing, ctx2);
    assert.deepEqual(update, []);
    // 沒勾過就被刪掉的只可能是復原或系統收掉的（「清掉」只有已完成那一格有）——
    // 那件事沒有人做過，所以要重新長一張（prelaunch-audit-2026-09-23/issues/01）
    assert.ok(create.some((t) => t.kind === 'Examine'), '沒勾過的刪掉就是不存在');
  });

  test('沒刪掉的那幾張行為一個字都沒變', () => {
    const visit = v2([slotAt('c-rehab', 'confirmed', '09:00')]);
    const existing = [{
      id: 't1', visitId: 'v1', kind: 'Examine', done: false,
      autoGenerated: true, dueDate: '1999-01-01', customerName: '客戶A',
    }];
    const { update } = syncTasksForVisit(visit, existing, ctx2);
    assert.deepEqual(update, [{ id: 't1', changes: { dueDate: '2026-09-19' } }]);
  });
});

// 兩層各濾一次，所以兩層都要盯。
describe('比對用的那一份要連軟刪除的一起讀', () => {
  const DATA_TASKS = readFileSync(
    new URL('../public/js/data/tasks.js', import.meta.url), 'utf8',
  );
  const DATA_VISITS = readFileSync(
    new URL('../public/js/data/visits.js', import.meta.url), 'utf8',
  );

  test('listByVisitForSync() 走 listWithDeleted()', () => {
    const at = DATA_TASKS.indexOf('export function listByVisitForSync(');
    assert.ok(at > 0, '這一支不在了 —— 比對會退回看不到被清掉的那幾張');
    assert.match(DATA_TASKS.slice(at, at + 200), /repo\.listWithDeleted\(/);
  });

  test('taskOps() 用的是它，不是 listByVisit()', () => {
    const at = DATA_VISITS.indexOf('async function taskOps(');
    assert.ok(at > 0);
    const body = DATA_VISITS.slice(at, at + 400);
    assert.match(body, /tasksData\.listByVisitForSync\(visit\.id\)/);
    assert.ok(!body.includes('tasksData.listByVisit(visit.id)'),
      '濾掉 deletedAt 的那一支會讓清掉過的登記重新長一次');
  });

  test('待辦中心那幾頁照舊走 listByVisit() —— 她清掉的就是要消失', () => {
    assert.match(DATA_TASKS, /export function listByVisit\(visitId\) \{\s*\n\s*return repo\.list\(/);
  });
});

// ---------- 復原過的、系統收掉的不算做過（prelaunch-audit-2026-09-23/issues/01） ----------
//
// 軟刪除有三種來源，只有「清掉」（已勾）是真的做過了。復原（`inverseOps()` 把新增的那幾張
// softDelete）與系統收掉（`syncTasksForVisit()` 的 remove）身上都是 `done: false`。

describe('軟刪除的只有勾過的算做過', () => {
  const C = { 'c-rehab': { category: 'A' }, 'c-recovery': { category: 'C' }, 'c-followup': { category: 'A', needsRecord: true } };
  const cx = { coursesById: C, today: '2026-09-16' };
  const slotAt = (courseId, status) => ({ courseId, entitlementId: 'e1', startsAt: '09:00', endsAt: '10:00', status });
  const day = (slots, status) => ({
    id: 'v1', customerId: 'c1', customerName: '客戶A', date: '2026-09-20', status: status ?? visitStatusFrom({ slots }), slots,
  });
  // `repo.commit()` 替 create 配 id；復原把它們 softDelete（reason 復原、done 照舊 false）
  const born = (create) => create.map((t, i) => ({ ...t, id: `t${i}` }));
  const undone = (tasks) => tasks.map((t) => ({ ...t, deletedAt: '2026-09-16' }));

  test('確認 → 復原 → 再確認：Examine、耀聖各長一張', () => {
    const first = syncTasksForVisit(day([slotAt('c-rehab', 'confirmed')]), [], cx).create;
    assert.deepEqual(first.map((t) => t.kind).sort(), ['Examine', '耀聖'].sort());
    const again = syncTasksForVisit(day([slotAt('c-rehab', 'confirmed')]), undone(born(first)), cx);
    assert.deepEqual(again.create.map((t) => t.kind).sort(), ['Examine', '耀聖'].sort());
    assert.deepEqual(again.update, [], '刪掉的那幾張一個字都不動');
  });

  test('結案 → 復原 → 再結案：寫紀錄長一張', () => {
    const doneDay = day([slotAt('c-followup', 'done')]);
    const first = syncTasksForVisit(doneDay, [], cx).create;
    assert.ok(first.some((t) => t.kind === RECORD_TASK_KIND));
    const again = syncTasksForVisit(doneDay, undone(born(first)), cx).create;
    assert.deepEqual(again.map((t) => t.kind), [RECORD_TASK_KIND]);
  });

  test('取消這一段 → 復原 → 再取消：「取消 Abovee」長一張', () => {
    const cut = day([slotAt('c-recovery', 'cancelled'), slotAt('c-recovery', 'confirmed')]);
    const first = syncTasksForVisit(cut, [], cx).create;
    assert.deepEqual(first.map((t) => t.kind), ['取消 Abovee']);
    const again = syncTasksForVisit(cut, undone(born(first)), cx).create;
    assert.deepEqual(again.map((t) => [t.kind, t.slotIndexes]), [['取消 Abovee', [0]]]);
  });

  test('A 類換成 C 類（系統收掉）再換回 A 類：Examine、耀聖重新長', () => {
    const tasks = born(syncTasksForVisit(day([slotAt('c-rehab', 'confirmed')]), [], cx).create);
    const swapped = syncTasksForVisit(day([slotAt('c-recovery', 'confirmed')]), tasks, cx);
    assert.equal(swapped.remove.length, 2);
    const gone = new Set(swapped.remove.map((r) => r.id));
    const after = tasks.map((t) => (gone.has(t.id) ? { ...t, deletedAt: '2026-09-16' } : t));
    const back = syncTasksForVisit(day([slotAt('c-rehab', 'confirmed')]), after, cx).create;
    assert.deepEqual(back.map((t) => t.kind).sort(), ['Examine', '耀聖'].sort());
  });

  test('復原掉的 Examine 沒掛過號 —— 取消那一段不長「取消 Examine」', () => {
    const cut = day([slotAt('c-rehab', 'cancelled')], 'cancelled');
    const existing = [{ id: 't1', visitId: 'v1', kind: 'Examine', done: true, doneAt: '2026-09-16', autoGenerated: true, deletedAt: '2026-09-16' }];
    // 勾過又被刪掉的（「清掉」）照樣算掛過
    assert.ok(syncTasksForVisit(cut, existing, cx).create.some((t) => t.kind === '取消 Examine'));
    // 沒勾過就被刪掉的不算
    const never = [{ ...existing[0], done: false, doneAt: null }];
    assert.ok(!syncTasksForVisit(cut, never, cx).create.some((t) => t.kind === '取消 Examine'));
  });

  test('seenTasks()：沒刪掉的全部、刪掉的只有勾過的', () => {
    const rows = [
      { id: 'a', done: false },
      { id: 'b', done: true },
      { id: 'c', done: true, deletedAt: 'x' },
      { id: 'd', done: false, deletedAt: 'x' },
    ];
    assert.deepEqual(seenTasks(rows).map((t) => t.id), ['a', 'b', 'c']);
  });
});

// 確認框與真的寫入要讀同一份（ADR-0070）。確認框讀的是不含軟刪除的那一支的話，
// 清掉過的 Examine 在框上看不到、寫下去卻長出「取消 Examine」。
describe('取消的確認框讀比對用的那一份', () => {
  for (const file of ['ui/views/calendar.js', 'ui/views/visitEditor.js', 'ui/views/bulkCancel.js']) {
    test(file, () => {
      const src = readFileSync(new URL(`../public/js/${file}`, import.meta.url), 'utf8');
      assert.ok(!/tasksData\.listByVisit\(/.test(src), '確認框要讀 listByVisitForSync()');
      assert.match(src, /tasksData\.listByVisitForSync\(/);
    });
  }
});

// ---------- 掛號那一族也逐段（prelaunch-audit-2026-09-23/issues/02） ----------
//
// 她 2026-09-13：「Examine 上是一段登記一筆，不會是一天一筆」；2026-09-23：同一天兩段 A 類
// 是**掛兩筆、待辦一張**。所以每一張記著它掛的是哪幾段（`slotIndexes`），同一次存檔談定的
// 幾段收成同一張；之後同一天補排的那一段談定了，另外長一張。

describe('掛號那一族逐段長', () => {
  const C = { 'c-rehab': { category: 'A' }, 'c-cardio': { category: 'A' }, 'c-recovery': { category: 'C' } };
  const cx = { coursesById: C, today: '2026-09-16' };
  const at = (courseId, status, startsAt = '09:00') => ({ courseId, entitlementId: 'e1', startsAt, endsAt: startsAt, status });
  const day = (slots) => ({
    id: 'v1', customerId: 'c1', customerName: '客戶A', date: '2026-09-20', status: visitStatusFrom({ slots }), slots,
  });
  const reg = (kind, slotIndexes, over = {}) => ({
    id: `t-${kind}-${slotIndexes.join('')}`, visitId: 'v1', kind, slotIndexes,
    done: true, doneAt: '2026-09-15', autoGenerated: true, dueDate: '2026-09-19', customerName: '客戶A', ...over,
  });
  const kindsAt = (create) => create.filter((t) => !isCancelKind(t.kind)).map((t) => [t.kind, t.slotIndexes]);

  test('同一次存檔談定兩段 A 類 → Examine、耀聖各一張，蓋兩段', () => {
    const { create } = syncTasksForVisit(day([at('c-rehab', 'confirmed'), at('c-cardio', 'confirmed', '14:00')]), [], cx);
    assert.deepEqual(kindsAt(create), [['Examine', [0, 1]], ['耀聖', [0, 1]]]);
  });

  test('取消 10:00 那一段、同一天補一段 15:00 談定 → 那一段自己長一張 Examine、一張耀聖', () => {
    const v = day([at('c-recovery', 'confirmed', '08:00'), at('c-rehab', 'cancelled', '10:00'), at('c-rehab', 'confirmed', '15:00')]);
    const existing = [reg('Examine', [1]), reg('耀聖', [1], { done: false, doneAt: null }), reg('取消 Examine', [1], { done: false })];
    const { create } = syncTasksForVisit(v, existing, cx);
    assert.deepEqual(kindsAt(create), [['Examine', [2]], ['耀聖', [2]]]);
  });

  test('取消沒掛號的那一段 → 不長「取消 Examine」', () => {
    // 早上那一段掛好了（勾掉），下午那一段的 Examine 還沒掛（沒勾）
    const v = day([at('c-rehab', 'confirmed'), at('c-cardio', 'cancelled', '14:00')]);
    const existing = [reg('Examine', [0]), reg('Examine', [1], { id: 't-open', done: false, doneAt: null })];
    const { create, remove } = syncTasksForVisit(v, existing, cx);
    assert.ok(!create.some((t) => t.kind === '取消 Examine'), '下午那一段沒掛過號');
    assert.deepEqual(remove.map((r) => r.id), ['t-open'], '沒掛的那一張不用掛了');
  });

  test('一張蓋兩段、還沒掛；其中一段取消了 → 那一張只剩另一段', () => {
    const v = day([at('c-rehab', 'confirmed'), at('c-cardio', 'cancelled', '14:00')]);
    const existing = [reg('Examine', [0, 1], { id: 't-both', done: false, doneAt: null })];
    const { update, remove, create } = syncTasksForVisit(v, existing, cx);
    assert.deepEqual(remove, []);
    assert.deepEqual(update, [{ id: 't-both', changes: { slotIndexes: [0] } }]);
    assert.ok(!create.some((t) => t.kind === '取消 Examine'));
  });

  test('舊資料（沒有 slotIndexes）當成蓋住整天 —— 補一段談定也一張都不多長', () => {
    const v = day([at('c-rehab', 'confirmed'), at('c-cardio', 'confirmed', '14:00')]);
    const legacy = [{ ...reg('Examine', [0]), slotIndexes: undefined }, { ...reg('耀聖', [0]), slotIndexes: undefined }];
    const { create, update } = syncTasksForVisit(v, legacy, cx);
    assert.deepEqual(kindsAt(create), []);
    assert.deepEqual(update, [], '舊的那幾張不補 slotIndexes');
  });

  test('確認抽屜那一句跟真的會長的走同一份：同一天早上掛過，確認下午那一段照樣說會多一張', async () => {
    const { confirmConsequences } = await import('../public/js/domain/consequences.js');
    const before = day([at('c-rehab', 'confirmed'), at('c-cardio', 'pending_confirm', '14:00')]);
    const lines = confirmConsequences([before], C, false, new Set(), { v1: [reg('Examine', [0]), reg('耀聖', [0])] });
    assert.ok(lines.some((l) => l.includes('Examine') && l.includes('耀聖')), lines.join('\n'));
  });
});
