// 清掉已完成的待辦之後，同一筆來訪再存一次，那幾張不可以重新長出來。
//
// 「清掉這 N 筆」與已完成那一列的垃圾桶都是**軟刪除**（SPEC 第 6.1 節），
// 而比對問的是「這一件事**有沒有人做過**」—— 做過了就是做過了。
//
// 2026-09-16 之前兩層各濾一次（`listByVisit()` 走 `repo.list()`，而
// `syncTasksForVisit()` 自己又濾 `!t.deletedAt`），於是清掉之後再存一次會長出
// 一張假的 Examine，**叫她再去掛一次號**。單元測試在 `tests/tasks.test.js`，
// 這一支從瀏覽器那一端問同一件事 —— 掃描擋不住「接線那一端根本沒把值傳進來」。

import { test, expect } from '../fixtures/app.js';
import { masterDocs, customer, entitlement, visit, slot, task, TODAY } from '../fixtures/data.js';

/**
 * 一位客戶、一筆**已確認**的復健科門診（A 類 → Examine、耀聖），
 * 而那兩張登記待辦**已經勾掉、而且被清掉了**（軟刪除）。
 */
function seedClearedTasks() {
  return [
    ...masterDocs(),
    customer({ id: 'cust-z', name: '客戶A' }),
    entitlement('cust-z', {
      id: 'ent-rehab', label: '復健科醫師門診', type: 'single',
      courseId: 'course-rehab', totalQty: 6, bookedCount: 1,
    }),
    visit({
      id: 'v-rehab', customerId: 'cust-z', customerName: '客戶A',
      date: TODAY, status: 'confirmed',
      slots: [{
        ...slot({
          courseId: 'course-rehab', entitlementId: 'ent-rehab',
          startsAt: '14:00', endsAt: '14:30',
        }),
        status: 'confirmed',
      }],
    }),
    ...['Examine', '耀聖'].map((kind, i) => ({
      ...task({
        id: `t-${i}`, customerId: 'cust-z', customerName: '客戶A', kind,
        dueDate: TODAY, visitId: 'v-rehab', done: true, doneAt: TODAY,
      }),
      // 她在待辦中心按了「清掉這 2 筆」
      data: {
        customerId: 'cust-z', customerName: '客戶A', kind, dueDate: TODAY,
        visitId: 'v-rehab', done: true, doneAt: TODAY, autoGenerated: true, note: null,
        deletedAt: `${TODAY}T10:00:00.000Z`,
      },
    })),
  ];
}

test('T1 清掉之後改那一段的時間再存：Examine 與耀聖不可以重新長出來', async ({ app, page }) => {
  await app.seed(seedClearedTasks());
  await app.signIn('/calendar');

  await page.locator(`[data-day="${TODAY}"]`).first().click();
  await app.layer('[data-open^="visit:"]');
  await page.locator('[data-open^="visit:v-rehab:"]').first().click();
  await app.layer('.popcard');
  await page.locator('[data-card-edit]').click();
  await app.layer('.slotcard');

  await page.locator('input[name="s0-start"]').fill('15:00');
  await page.locator('button[type="submit"]').first().click();
  await app.saved();

  const alive = (await app.readAll('tasks')).filter((t) => !t.deletedAt);
  expect(
    alive.map((t) => t.kind),
    '那兩件她真的去掛過號了 —— 清掉的只是那一列',
  ).toEqual([]);
});

test('T2 沒清掉的那幾張行為一個字都沒變（死線跟著搬）', async ({ app, page }) => {
  const seed = seedClearedTasks();
  for (const doc of seed.filter((d) => d.path === 'tasks')) doc.data.deletedAt = null;

  await app.seed(seed);
  await app.signIn('/calendar');

  await page.locator(`[data-day="${TODAY}"]`).first().click();
  await app.layer('[data-open^="visit:"]');
  await page.locator('[data-open^="visit:v-rehab:"]').first().click();
  await app.layer('.popcard');
  await page.locator('[data-card-edit]').click();
  await app.layer('.slotcard');

  await page.locator('input[name="s0-start"]').fill('15:00');
  await page.locator('button[type="submit"]').first().click();
  await app.saved();

  const alive = (await app.readAll('tasks')).filter((t) => !t.deletedAt);
  expect(alive.map((t) => t.kind).sort(), '本來就在的那兩張留著，不多也不少')
    .toEqual(['Examine', '耀聖']);
});
